// Code generated by protoc-gen-ent. DO NOT EDIT.
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
)

// Token holds the ent schema definition for the Token entity.
type Token struct {
	ent.Schema
}

// Fields defines the fields of Token.
func (Token) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").StorageKey("id").Immutable(),
		field.String("label").Optional(),
	}
}
