// Code generated by protoc-gen-svc. DO NOT EDIT.
// source: (proto input)
// Hand-maintained handler logic follows the generated registration scaffold.

package widgetsv1

import (
	"context"
	"fmt"
	"time"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/infobloxopen/devedge-sdk/authz/grpcauthz"
	"github.com/infobloxopen/devedge-sdk/lro"
	"github.com/infobloxopen/devedge-sdk/middleware"
	"github.com/infobloxopen/devedge-sdk/server"
)

// RegisterWidgetService wires srv into the server's gRPC handler and HTTP gateway.
// It asserts at startup that all methods are declared in the authz rules;
// if any method lacks a declaration, an error is returned (fail-closed boot gate).
func RegisterWidgetService(s *server.Server, srv WidgetServiceServer) error {
	methods := []string{
		WidgetService_CreateWidget_FullMethodName,
		WidgetService_GetWidget_FullMethodName,
		WidgetService_ListWidgets_FullMethodName,
		WidgetService_UpdateWidget_FullMethodName,
		WidgetService_DeleteWidget_FullMethodName,
		WidgetService_ArchiveWidget_FullMethodName,
		WidgetService_BatchGetWidgets_FullMethodName,
		WidgetService_BatchDeleteWidgets_FullMethodName,
		WidgetService_ProcessWidget_FullMethodName,
		WidgetService_GetOperationStatus_FullMethodName,
	}
	if err := grpcauthz.AssertMethodsDeclared(methods, grpcauthz.WithRules(s.Rules()...)); err != nil {
		return err
	}
	RegisterWidgetServiceServer(s.GRPCServer(), srv)
	s.RegisterGateway(func(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
		return RegisterWidgetServiceHandlerClient(ctx, mux, NewWidgetServiceClient(conn))
	})
	return nil
}

// WidgetServer is a concrete WidgetServiceServer backed by a WidgetRepository.
type WidgetServer struct {
	UnimplementedWidgetServiceServer
	repo   *WidgetRepository
	lroMgr *lro.Manager
}

// NewWidgetServer creates a WidgetServer backed by the given repository.
// lroStore is optional; when nil a MemoryStore with a 1-hour TTL is used.
func NewWidgetServer(repo *WidgetRepository, lroStore lro.Store) *WidgetServer {
	if lroStore == nil {
		lroStore = lro.NewMemoryStore(time.Hour)
	}
	return &WidgetServer{repo: repo, lroMgr: lro.NewManager(lroStore)}
}

// CreateWidget implements AIP-133 create. When validate_only is true (AIP-163)
// the widget is constructed and validated but not persisted.
func (s *WidgetServer) CreateWidget(ctx context.Context, req *CreateWidgetRequest) (*Widget, error) {
	w := req.Widget
	if w == nil {
		w = &Widget{}
	}

	if middleware.ValidateOnlyFromContext(ctx) {
		return w, nil // dry-run: return constructed widget without persisting
	}

	created, err := s.repo.Create(ctx, w)
	if err != nil {
		return nil, err
	}
	return created, nil
}

// ProcessWidget starts an async processing job for the given widget ID (AIP-151).
// It returns a pending OperationStatus immediately; the background work completes
// after ~50ms and stores the result under the operation name.
func (s *WidgetServer) ProcessWidget(ctx context.Context, req *ProcessWidgetRequest) (*OperationStatus, error) {
	id := req.Id
	op, err := s.lroMgr.Submit(ctx, id, func(ctx context.Context) (any, error) {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-time.After(50 * time.Millisecond):
		}
		return fmt.Sprintf("processed:%s", id), nil
	})
	if err != nil {
		return nil, status.Errorf(codes.Internal, "submit operation: %v", err)
	}
	return &OperationStatus{Name: op.Name, Done: op.Done}, nil
}

// GetOperationStatus retrieves the current status of a ProcessWidget operation (AIP-151).
func (s *WidgetServer) GetOperationStatus(ctx context.Context, req *GetOperationStatusRequest) (*OperationStatus, error) {
	op, err := s.lroMgr.Store().Get(ctx, req.Name)
	if err != nil {
		return nil, status.Errorf(codes.NotFound, "operation %q not found", req.Name)
	}
	result := ""
	if op.Done && op.Response != nil {
		if r, ok := op.Response.(string); ok {
			result = r
		}
	}
	return &OperationStatus{Name: op.Name, Done: op.Done, Result: result}, nil
}
