// Code generated by protoc-gen-storage. DO NOT EDIT.
// source: (proto input)

package widgetsv1

import (
	"context"
	"encoding/base64"
	"fmt"
	"strconv"
	"time"

	"gorm.io/gorm"
	"google.golang.org/protobuf/types/known/timestamppb"

	"github.com/infobloxopen/devedge-sdk/persistence"
	"github.com/infobloxopen/devedge-sdk/persistence/filter"
	"github.com/infobloxopen/devedge-sdk/persistence/resourcename"
	"github.com/infobloxopen/devedge-sdk/middleware/etag"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

var (
	_ = base64.StdEncoding
	_ = fmt.Sprintf
	_ = strconv.Itoa
	_ = filter.Parse
	_ = codes.OK
	_ = status.Error
	_ = resourcename.IDVarName
	_ = timestamppb.New
)

// WidgetModel is the GORM model for Widget.
type WidgetModel struct {
	ID          string `gorm:"primaryKey;type:varchar(36)"`
	DisplayName string `gorm:"column:display_name"`
	Color       string `gorm:"column:color"`
	Weight      int32  `gorm:"column:weight"`
	ETag        string `gorm:"column:etag"`
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   gorm.DeletedAt `gorm:"index"`
}

func toModel_Widget(p *Widget) *WidgetModel {
	if p == nil {
		return nil
	}
	m := &WidgetModel{ID: p.Id}
	m.DisplayName = p.DisplayName
	m.Color = p.Color
	m.Weight = p.Weight
	return m
}

func fromModel_Widget(m *WidgetModel) *Widget {
	if m == nil {
		return nil
	}
	p := &Widget{Id: m.ID}
	p.Name = FormatWidgetName(m.ID)
	p.DisplayName = m.DisplayName
	p.Color = m.Color
	p.Weight = m.Weight
	if m.DeletedAt.Valid {
		p.DeleteTime = timestamppb.New(m.DeletedAt.Time)
	}
	p.Etag = m.ETag
	if FromModelWidgetCustom != nil {
		FromModelWidgetCustom(m, p)
	}
	return p
}

// FromModelWidgetCustom, if set, runs at the end of fromModel_Widget to populate
// fields the generator cannot derive (computed/derived values). Register it
// from your own (regen-safe) file — e.g. in an init(); never assigned here.
var FromModelWidgetCustom func(m *WidgetModel, p *Widget)

// ToModelWidgetOnCreate, if set, runs in Create just before the database write,
// to set columns the generator does not (e.g. a custom-encoded field).
var ToModelWidgetOnCreate func(p *Widget, m *WidgetModel)

// ToModelWidgetOnUpdate, if set, runs in Update just before the database write.
var ToModelWidgetOnUpdate func(p *Widget, m *WidgetModel)

// WidgetColumns maps proto field names to DB column names for safe filter/order_by parsing.
var WidgetColumns = map[string]string{
	"id":           "id",
	"display_name": "display_name",
	"color":        "color",
	"weight":       "weight",
	"delete_time":  "deleted_at",
}

// WidgetNamePattern is the AIP-122 resource name pattern for Widget.
const WidgetNamePattern = "widgets/{widget}"

// FormatWidgetName builds the resource name for the given ID.
func FormatWidgetName(id string) string {
	name, _ := resourcename.Format(WidgetNamePattern, map[string]string{"widget": id})
	return name
}

// ParseWidgetName extracts the resource ID from the given name.
func ParseWidgetName(name string) (string, error) {
	return resourcename.IDFromName(WidgetNamePattern, name)
}

// WidgetRepository is a GORM-backed persistence.Repository for *Widget.
type WidgetRepository struct{ db *gorm.DB }

// NewWidgetRepository creates a repository backed by db.
func NewWidgetRepository(db *gorm.DB) *WidgetRepository {
	return &WidgetRepository{db: db}
}

func (r *WidgetRepository) Get(ctx context.Context, key string) (*Widget, error) {
	var m WidgetModel
	if err := r.db.WithContext(ctx).Where("id = ?", key).First(&m).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, persistence.ErrNotFound
		}
		return nil, fmt.Errorf("get Widget: %w", err)
	}
	return fromModel_Widget(&m), nil
}

func (r *WidgetRepository) List(ctx context.Context, opts persistence.ListOptions) ([]*Widget, string, error) {
	var models []WidgetModel
	q := r.db.WithContext(ctx)
	if opts.ShowDeleted {
		q = q.Unscoped()
	}
	if opts.Filter != "" {
		cond, err := filter.Parse(opts.Filter, WidgetColumns)
		if err != nil {
			return nil, "", status.Errorf(codes.InvalidArgument, "invalid filter: %v", err)
		}
		sql, args := cond.SQL()
		q = q.Where(sql, args...)
	}
	if opts.OrderBy != "" {
		clauses, err := filter.ParseOrderBy(opts.OrderBy, WidgetColumns)
		if err != nil {
			return nil, "", status.Errorf(codes.InvalidArgument, "invalid order_by: %v", err)
		}
		for _, c := range clauses {
			q = q.Order(c.GORMExpr())
		}
	}
	pageSize := opts.PageSize
	if pageSize <= 0 {
		pageSize = 50
	}
	offset := 0
	if opts.PageToken != "" {
		if dec, err := base64.StdEncoding.DecodeString(opts.PageToken); err == nil {
			offset, _ = strconv.Atoi(string(dec))
		}
	}
	if err := q.Limit(pageSize).Offset(offset).Find(&models).Error; err != nil {
		return nil, "", fmt.Errorf("list Widget: %w", err)
	}
	out := make([]*Widget, len(models))
	for i := range models {
		out[i] = fromModel_Widget(&models[i])
	}
	nextToken := ""
	if len(models) == pageSize {
		nextToken = base64.StdEncoding.EncodeToString([]byte(strconv.Itoa(offset + pageSize)))
	}
	return out, nextToken, nil
}

func (r *WidgetRepository) Create(ctx context.Context, entity *Widget) (*Widget, error) {
	m := toModel_Widget(entity)
	m.ETag = etag.New() // AIP-154: fresh ETag on create
	if ToModelWidgetOnCreate != nil {
		ToModelWidgetOnCreate(entity, m)
	}
	if err := r.db.WithContext(ctx).Create(m).Error; err != nil {
		// Map driver constraint violations to clean sentinels so callers see
		// AlreadyExists/FailedPrecondition (not 500), and no SQL leaks to the client.
		if ce := persistence.ConstraintError(err); ce != nil {
			return nil, ce
		}
		return nil, fmt.Errorf("create Widget: %w", err)
	}
	return fromModel_Widget(m), nil
}

func (r *WidgetRepository) Update(ctx context.Context, key string, entity *Widget, fieldMask ...string) (*Widget, error) {
	m := toModel_Widget(entity)
	m.ID = key
	m.ETag = etag.New() // AIP-154: bump the ETag on every update
	if ToModelWidgetOnUpdate != nil {
		ToModelWidgetOnUpdate(entity, m)
	}
	q := r.db.WithContext(ctx).Model(m).Where("id = ?", key)
	if len(fieldMask) > 0 {
		dbCols := make([]string, 0, len(fieldMask))
		for _, f := range fieldMask {
			col, ok := WidgetColumns[f]
			if !ok {
				return nil, status.Errorf(codes.InvalidArgument, "unknown field in update_mask: %q", f)
			}
			dbCols = append(dbCols, col)
		}
		dbCols = append(dbCols, "etag") // a masked update still changes the resource
		// Select makes GORM write the named columns even when their value is
		// the zero value (false, 0, ""); a bare struct Updates would skip them.
		if err := q.Select(dbCols).Updates(m).Error; err != nil {
			if ce := persistence.ConstraintError(err); ce != nil {
				return nil, ce
			}
			return nil, fmt.Errorf("update Widget: %w", err)
		}
	} else {
		// No field mask: full update of every writable column via a map, so
		// zero values (false, 0, "") persist — a struct Updates skips zero fields
		// and would silently drop "disable this" / "clear that" updates.
		updates := map[string]interface{}{
			"display_name": m.DisplayName,
			"color":        m.Color,
			"weight":       m.Weight,
		}
		updates["etag"] = m.ETag
		if err := q.Updates(updates).Error; err != nil {
			if ce := persistence.ConstraintError(err); ce != nil {
				return nil, ce
			}
			return nil, fmt.Errorf("update Widget: %w", err)
		}
	}
	return r.Get(ctx, key)
}

func (r *WidgetRepository) Delete(ctx context.Context, key string) error {
	res := r.db.WithContext(ctx).Where("id = ?", key).Delete(&WidgetModel{})
	if res.Error != nil {
		return fmt.Errorf("delete Widget: %w", res.Error)
	}
	if res.RowsAffected == 0 {
		return persistence.ErrNotFound
	}
	return nil
}

func (r *WidgetRepository) Undelete(ctx context.Context, key string) (*Widget, error) {
	q := r.db.WithContext(ctx).Unscoped().Model(&WidgetModel{}).
		Where("id = ?", key).Where("deleted_at IS NOT NULL")
	res := q.Update("deleted_at", nil)
	if res.Error != nil {
		return nil, fmt.Errorf("undelete Widget: %w", res.Error)
	}
	if res.RowsAffected == 0 {
		return nil, persistence.ErrNotFound
	}
	return r.Get(ctx, key)
}

func (r *WidgetRepository) BatchGet(ctx context.Context, keys []string) ([]*Widget, error) {
	if len(keys) == 0 {
		return []*Widget{}, nil
	}
	var models []WidgetModel
	q := r.db.WithContext(ctx).Where("id IN ?", keys)
	if err := q.Find(&models).Error; err != nil {
		return nil, fmt.Errorf("batch get Widget: %w", err)
	}
	byID := make(map[string]*Widget, len(models))
	for i := range models {
		byID[models[i].ID] = fromModel_Widget(&models[i])
	}
	out := make([]*Widget, 0, len(keys))
	for _, k := range keys {
		p, ok := byID[k]
		if !ok {
			return nil, persistence.ErrNotFound
		}
		out = append(out, p)
	}
	return out, nil
}

func (r *WidgetRepository) BatchUpdate(ctx context.Context, items []persistence.BatchUpdateItem[*Widget, string]) ([]*Widget, error) {
	if len(items) == 0 {
		return []*Widget{}, nil
	}
	out := make([]*Widget, 0, len(items))
	err := r.db.Transaction(func(tx *gorm.DB) error {
		txRepo := &WidgetRepository{db: tx}
		for _, it := range items {
			updated, err := txRepo.Update(ctx, it.Key, it.Entity, it.FieldMask...)
			if err != nil {
				return err
			}
			out = append(out, updated)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (r *WidgetRepository) BatchDelete(ctx context.Context, keys []string) error {
	if len(keys) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(keys))
	uniq := make([]string, 0, len(keys))
	for _, k := range keys {
		if _, ok := seen[k]; ok {
			continue
		}
		seen[k] = struct{}{}
		uniq = append(uniq, k)
	}
	return r.db.Transaction(func(tx *gorm.DB) error {
		q := tx.WithContext(ctx).Where("id IN ?", uniq)
		res := q.Delete(&WidgetModel{})
		if res.Error != nil {
			return fmt.Errorf("batch delete Widget: %w", res.Error)
		}
		if res.RowsAffected != int64(len(uniq)) {
			return persistence.ErrNotFound
		}
		return nil
	})
}

// compile-time check.
var _ persistence.BatchRepository[*Widget, string] = (*WidgetRepository)(nil)
