// Code generated by protoc-gen-storage. DO NOT EDIT.
// source: (proto input)

package widgetsv1

import (
	"context"
	"encoding/base64"
	"fmt"
	"strconv"
	"time"

	"gorm.io/gorm"

	"github.com/infobloxopen/devedge-sdk/persistence"
)

var (
	_ = base64.StdEncoding
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

// WidgetModel is the GORM model for Widget.
type WidgetModel struct {
	ID        string `gorm:"primaryKey;type:varchar(36)"`
	Name      string `gorm:"column:name"`
	Color     string `gorm:"column:color"`
	Weight    int32  `gorm:"column:weight"`
	Etag      string `gorm:"column:etag"`
	ETag      string `gorm:"column:etag"`
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt gorm.DeletedAt `gorm:"index"`
}

func toModel_Widget(p *Widget) *WidgetModel {
	if p == nil {
		return nil
	}
	m := &WidgetModel{ID: p.Id}
	m.Name = p.Name
	m.Color = p.Color
	m.Weight = p.Weight
	m.Etag = p.Etag
	return m
}

func fromModel_Widget(m *WidgetModel) *Widget {
	if m == nil {
		return nil
	}
	p := &Widget{Id: m.ID}
	p.Name = m.Name
	p.Color = m.Color
	p.Weight = m.Weight
	p.Etag = m.Etag
	return p
}

// WidgetRepository is a GORM-backed persistence.Repository for *Widget.
type WidgetRepository struct{ db *gorm.DB }

// NewWidgetRepository creates a repository backed by db.
func NewWidgetRepository(db *gorm.DB) *WidgetRepository {
	return &WidgetRepository{db: db}
}

func (r *WidgetRepository) Get(ctx context.Context, key string) (*Widget, error) {
	var m WidgetModel
	if err := r.db.WithContext(ctx).Where("id = ?", key).First(&m).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, persistence.ErrNotFound
		}
		return nil, fmt.Errorf("get Widget: %w", err)
	}
	return fromModel_Widget(&m), nil
}

func (r *WidgetRepository) List(ctx context.Context, opts persistence.ListOptions) ([]*Widget, string, error) {
	var models []WidgetModel
	q := r.db.WithContext(ctx)
	if opts.Filter != "" {
		q = q.Where(opts.Filter)
	}
	pageSize := opts.PageSize
	if pageSize <= 0 {
		pageSize = 50
	}
	offset := 0
	if opts.PageToken != "" {
		if dec, err := base64.StdEncoding.DecodeString(opts.PageToken); err == nil {
			offset, _ = strconv.Atoi(string(dec))
		}
	}
	if err := q.Limit(pageSize).Offset(offset).Find(&models).Error; err != nil {
		return nil, "", fmt.Errorf("list Widget: %w", err)
	}
	out := make([]*Widget, len(models))
	for i := range models {
		out[i] = fromModel_Widget(&models[i])
	}
	nextToken := ""
	if len(models) == pageSize {
		nextToken = base64.StdEncoding.EncodeToString([]byte(strconv.Itoa(offset + pageSize)))
	}
	return out, nextToken, nil
}

func (r *WidgetRepository) Create(ctx context.Context, entity *Widget) (*Widget, error) {
	m := toModel_Widget(entity)
	if err := r.db.WithContext(ctx).Create(m).Error; err != nil {
		return nil, fmt.Errorf("create Widget: %w", err)
	}
	return fromModel_Widget(m), nil
}

func (r *WidgetRepository) Update(ctx context.Context, key string, entity *Widget, fieldMask ...string) (*Widget, error) {
	m := toModel_Widget(entity)
	m.ID = key
	q := r.db.WithContext(ctx).Model(m).Where("id = ?", key)
	if len(fieldMask) > 0 {
		q = q.Select(fieldMask)
	}
	if err := q.Updates(m).Error; err != nil {
		return nil, fmt.Errorf("update Widget: %w", err)
	}
	return r.Get(ctx, key)
}

func (r *WidgetRepository) Delete(ctx context.Context, key string) error {
	if err := r.db.WithContext(ctx).Where("id = ?", key).Delete(&WidgetModel{}).Error; err != nil {
		return fmt.Errorf("delete Widget: %w", err)
	}
	return nil
}

// compile-time check.
var _ persistence.Repository[*Widget, string] = (*WidgetRepository)(nil)
