// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: widgets.proto

// Test fixture for protoc-gen-svc + protoc-gen-storage (W3-4 checkpoint).
// This proto exercises both plugins: a resource message (Widget) and a service
// (WidgetService) with authz annotations on all five standard AIP methods.

package widgetsv1

import (
	_ "github.com/infobloxopen/apis/proto/infoblox/authz/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Widget is the resource managed by WidgetService.
type Widget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Weight        int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Widget) Reset() {
	*x = Widget{}
	mi := &file_widgets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Widget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Widget) ProtoMessage() {}

func (x *Widget) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Widget.ProtoReflect.Descriptor instead.
func (*Widget) Descriptor() ([]byte, []int) {
	return file_widgets_proto_rawDescGZIP(), []int{0}
}

func (x *Widget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Widget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Widget) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Widget) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type CreateWidgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Widget        *Widget                `protobuf:"bytes,1,opt,name=widget,proto3" json:"widget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWidgetRequest) Reset() {
	*x = CreateWidgetRequest{}
	mi := &file_widgets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWidgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWidgetRequest) ProtoMessage() {}

func (x *CreateWidgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWidgetRequest.ProtoReflect.Descriptor instead.
func (*CreateWidgetRequest) Descriptor() ([]byte, []int) {
	return file_widgets_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWidgetRequest) GetWidget() *Widget {
	if x != nil {
		return x.Widget
	}
	return nil
}

type GetWidgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWidgetRequest) Reset() {
	*x = GetWidgetRequest{}
	mi := &file_widgets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWidgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWidgetRequest) ProtoMessage() {}

func (x *GetWidgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWidgetRequest.ProtoReflect.Descriptor instead.
func (*GetWidgetRequest) Descriptor() ([]byte, []int) {
	return file_widgets_proto_rawDescGZIP(), []int{2}
}

func (x *GetWidgetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListWidgetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWidgetsRequest) Reset() {
	*x = ListWidgetsRequest{}
	mi := &file_widgets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWidgetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWidgetsRequest) ProtoMessage() {}

func (x *ListWidgetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWidgetsRequest.ProtoReflect.Descriptor instead.
func (*ListWidgetsRequest) Descriptor() ([]byte, []int) {
	return file_widgets_proto_rawDescGZIP(), []int{3}
}

func (x *ListWidgetsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWidgetsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListWidgetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Widgets       []*Widget              `protobuf:"bytes,1,rep,name=widgets,proto3" json:"widgets,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWidgetsResponse) Reset() {
	*x = ListWidgetsResponse{}
	mi := &file_widgets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWidgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWidgetsResponse) ProtoMessage() {}

func (x *ListWidgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWidgetsResponse.ProtoReflect.Descriptor instead.
func (*ListWidgetsResponse) Descriptor() ([]byte, []int) {
	return file_widgets_proto_rawDescGZIP(), []int{4}
}

func (x *ListWidgetsResponse) GetWidgets() []*Widget {
	if x != nil {
		return x.Widgets
	}
	return nil
}

func (x *ListWidgetsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateWidgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Widget        *Widget                `protobuf:"bytes,1,opt,name=widget,proto3" json:"widget,omitempty"`
	UpdateMask    []string               `protobuf:"bytes,2,rep,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWidgetRequest) Reset() {
	*x = UpdateWidgetRequest{}
	mi := &file_widgets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWidgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWidgetRequest) ProtoMessage() {}

func (x *UpdateWidgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWidgetRequest.ProtoReflect.Descriptor instead.
func (*UpdateWidgetRequest) Descriptor() ([]byte, []int) {
	return file_widgets_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateWidgetRequest) GetWidget() *Widget {
	if x != nil {
		return x.Widget
	}
	return nil
}

func (x *UpdateWidgetRequest) GetUpdateMask() []string {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteWidgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWidgetRequest) Reset() {
	*x = DeleteWidgetRequest{}
	mi := &file_widgets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWidgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWidgetRequest) ProtoMessage() {}

func (x *DeleteWidgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWidgetRequest.ProtoReflect.Descriptor instead.
func (*DeleteWidgetRequest) Descriptor() ([]byte, []int) {
	return file_widgets_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteWidgetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWidgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWidgetResponse) Reset() {
	*x = DeleteWidgetResponse{}
	mi := &file_widgets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWidgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWidgetResponse) ProtoMessage() {}

func (x *DeleteWidgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWidgetResponse.ProtoReflect.Descriptor instead.
func (*DeleteWidgetResponse) Descriptor() ([]byte, []int) {
	return file_widgets_proto_rawDescGZIP(), []int{7}
}

var File_widgets_proto protoreflect.FileDescriptor

const file_widgets_proto_rawDesc = "" +
	"\n" +
	"\rwidgets.proto\x12\x06toy.v1\x1a\x1dinfoblox/authz/v1/authz.proto\"Z\n" +
	"\x06Widget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\"=\n" +
	"\x13CreateWidgetRequest\x12&\n" +
	"\x06widget\x18\x01 \x01(\v2\x0e.toy.v1.WidgetR\x06widget\"\"\n" +
	"\x10GetWidgetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"P\n" +
	"\x12ListWidgetsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"g\n" +
	"\x13ListWidgetsResponse\x12(\n" +
	"\awidgets\x18\x01 \x03(\v2\x0e.toy.v1.WidgetR\awidgets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"^\n" +
	"\x13UpdateWidgetRequest\x12&\n" +
	"\x06widget\x18\x01 \x01(\v2\x0e.toy.v1.WidgetR\x06widget\x12\x1f\n" +
	"\vupdate_mask\x18\x02 \x03(\tR\n" +
	"updateMask\"%\n" +
	"\x13DeleteWidgetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteWidgetResponse2\xc2\x03\n" +
	"\rWidgetService\x12R\n" +
	"\fCreateWidget\x12\x1b.toy.v1.CreateWidgetRequest\x1a\x0e.toy.v1.Widget\"\x15\x8a\xb5\x18\x11\n" +
	"\x06create\x12\awidgets\x12J\n" +
	"\tGetWidget\x12\x18.toy.v1.GetWidgetRequest\x1a\x0e.toy.v1.Widget\"\x13\x8a\xb5\x18\x0f\n" +
	"\x04read\x12\awidgets\x12[\n" +
	"\vListWidgets\x12\x1a.toy.v1.ListWidgetsRequest\x1a\x1b.toy.v1.ListWidgetsResponse\"\x13\x8a\xb5\x18\x0f\n" +
	"\x04read\x12\awidgets\x12R\n" +
	"\fUpdateWidget\x12\x1b.toy.v1.UpdateWidgetRequest\x1a\x0e.toy.v1.Widget\"\x15\x8a\xb5\x18\x11\n" +
	"\x06update\x12\awidgets\x12`\n" +
	"\fDeleteWidget\x12\x1b.toy.v1.DeleteWidgetRequest\x1a\x1c.toy.v1.DeleteWidgetResponse\"\x15\x8a\xb5\x18\x11\n" +
	"\x06delete\x12\awidgetsBFZDgithub.com/infobloxopen/devedge-sdk/testdata/toy/widgetsv1;widgetsv1b\x06proto3"

var (
	file_widgets_proto_rawDescOnce sync.Once
	file_widgets_proto_rawDescData []byte
)

func file_widgets_proto_rawDescGZIP() []byte {
	file_widgets_proto_rawDescOnce.Do(func() {
		file_widgets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_widgets_proto_rawDesc), len(file_widgets_proto_rawDesc)))
	})
	return file_widgets_proto_rawDescData
}

var file_widgets_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_widgets_proto_goTypes = []any{
	(*Widget)(nil),               // 0: toy.v1.Widget
	(*CreateWidgetRequest)(nil),  // 1: toy.v1.CreateWidgetRequest
	(*GetWidgetRequest)(nil),     // 2: toy.v1.GetWidgetRequest
	(*ListWidgetsRequest)(nil),   // 3: toy.v1.ListWidgetsRequest
	(*ListWidgetsResponse)(nil),  // 4: toy.v1.ListWidgetsResponse
	(*UpdateWidgetRequest)(nil),  // 5: toy.v1.UpdateWidgetRequest
	(*DeleteWidgetRequest)(nil),  // 6: toy.v1.DeleteWidgetRequest
	(*DeleteWidgetResponse)(nil), // 7: toy.v1.DeleteWidgetResponse
}
var file_widgets_proto_depIdxs = []int32{
	0, // 0: toy.v1.CreateWidgetRequest.widget:type_name -> toy.v1.Widget
	0, // 1: toy.v1.ListWidgetsResponse.widgets:type_name -> toy.v1.Widget
	0, // 2: toy.v1.UpdateWidgetRequest.widget:type_name -> toy.v1.Widget
	1, // 3: toy.v1.WidgetService.CreateWidget:input_type -> toy.v1.CreateWidgetRequest
	2, // 4: toy.v1.WidgetService.GetWidget:input_type -> toy.v1.GetWidgetRequest
	3, // 5: toy.v1.WidgetService.ListWidgets:input_type -> toy.v1.ListWidgetsRequest
	5, // 6: toy.v1.WidgetService.UpdateWidget:input_type -> toy.v1.UpdateWidgetRequest
	6, // 7: toy.v1.WidgetService.DeleteWidget:input_type -> toy.v1.DeleteWidgetRequest
	0, // 8: toy.v1.WidgetService.CreateWidget:output_type -> toy.v1.Widget
	0, // 9: toy.v1.WidgetService.GetWidget:output_type -> toy.v1.Widget
	4, // 10: toy.v1.WidgetService.ListWidgets:output_type -> toy.v1.ListWidgetsResponse
	0, // 11: toy.v1.WidgetService.UpdateWidget:output_type -> toy.v1.Widget
	7, // 12: toy.v1.WidgetService.DeleteWidget:output_type -> toy.v1.DeleteWidgetResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_widgets_proto_init() }
func file_widgets_proto_init() {
	if File_widgets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_widgets_proto_rawDesc), len(file_widgets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_widgets_proto_goTypes,
		DependencyIndexes: file_widgets_proto_depIdxs,
		MessageInfos:      file_widgets_proto_msgTypes,
	}.Build()
	File_widgets_proto = out.File
	file_widgets_proto_goTypes = nil
	file_widgets_proto_depIdxs = nil
}
