// Code generated by protoc-gen-ent. DO NOT EDIT.
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"entgo.io/ent/dialect/entsql"

	"github.com/infobloxopen/devedge-sdk/persistence/entrepo"
)

// Group holds the ent schema definition for the Group entity.
type Group struct {
	ent.Schema
}

// Mixin returns the mixins applied to Group.
func (Group) Mixin() []ent.Mixin {
	return []ent.Mixin{
		entrepo.TenantMixin{},
		entrepo.EtagMixin{},
	}
}

// Fields defines the fields of Group.
func (Group) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").StorageKey("id").Immutable(),
		field.String("display_name").Optional(),
	}
}

// Edges defines the edges (relationships) of Group.
func (Group) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("memberships", Membership.Type).Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

// Indexes defines the indexes of Group.
func (Group) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("account_id", "display_name").Unique().StorageKey("ux_group_account_display_name"),
	}
}
