// Code generated by protoc-gen-ent. DO NOT EDIT.
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"

	"github.com/infobloxopen/devedge-sdk/persistence/entrepo"
)

// Membership holds the ent schema definition for the Membership entity.
type Membership struct {
	ent.Schema
}

// Mixin returns the mixins applied to Membership.
func (Membership) Mixin() []ent.Mixin {
	return []ent.Mixin{
		entrepo.TenantMixin{},
	}
}

// Fields defines the fields of Membership.
func (Membership) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").StorageKey("id").Immutable(),
		field.String("group_id").Optional(),
		field.String("user_id").Optional(),
		field.String("role").Optional(),
	}
}

// Edges defines the edges (relationships) of Membership.
func (Membership) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("group", Group.Type).Ref("memberships").Unique().Field("group_id"),
	}
}
