// Code generated by protoc-gen-ent. DO NOT EDIT.
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"

	"github.com/infobloxopen/devedge-sdk/persistence/entrepo"
)

// User holds the ent schema definition for the User entity.
type User struct {
	ent.Schema
}

// Mixin returns the mixins applied to User.
func (User) Mixin() []ent.Mixin {
	return []ent.Mixin{
		entrepo.TenantMixin{},
		entrepo.EtagMixin{},
	}
}

// Fields defines the fields of User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").StorageKey("id").Immutable(),
		field.String("email").Optional(),
		field.String("display_name").Optional(),
	}
}

// Indexes defines the indexes of User.
func (User) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("account_id", "email").Unique().StorageKey("ux_user_account_email"),
	}
}
