package main

import (
	"fmt"
	"strings"
)

// serviceInfo describes a proto service for code generation.
type serviceInfo struct {
	ServiceName string
	Methods     []methodInfo
}

// methodInfo describes a single RPC method.
type methodInfo struct {
	Name          string
	InputGoIdent  string // Go type name for the request (within the same package)
	OutputGoIdent string // Go type name for the response
}

// renderSvcFile generates the .svc.go content for the given package and
// services. Returns an empty string when services is empty.
func renderSvcFile(pkgName, _ string, services []serviceInfo) string {
	if len(services) == 0 {
		return ""
	}

	var b strings.Builder

	b.WriteString("// Code generated by protoc-gen-svc. DO NOT EDIT.\n")
	b.WriteString("// source: (proto input)\n")
	b.WriteString("\n")
	fmt.Fprintf(&b, "package %s\n\n", pkgName)
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n\n")
	b.WriteString("\t\"google.golang.org/grpc\"\n")
	b.WriteString("\t\"google.golang.org/grpc/codes\"\n")
	b.WriteString("\t\"google.golang.org/grpc/status\"\n")
	b.WriteString(")\n\n")

	for _, svc := range services {
		lower := lcFirst(svc.ServiceName)

		// Handler interface.
		fmt.Fprintf(&b, "// %sServer is the application-layer handler interface for %s.\n", svc.ServiceName, svc.ServiceName)
		fmt.Fprintf(&b, "// Implement this type; Register%s wires it into a *grpc.Server.\n", svc.ServiceName)
		fmt.Fprintf(&b, "type %sServer interface {\n", svc.ServiceName)
		for _, m := range svc.Methods {
			fmt.Fprintf(&b, "\t%s(context.Context, *%s) (*%s, error)\n", m.Name, m.InputGoIdent, m.OutputGoIdent)
		}
		b.WriteString("}\n\n")

		// Unimplemented stub.
		fmt.Fprintf(&b, "// Unimplemented%sServer returns codes.Unimplemented for every method.\n", svc.ServiceName)
		fmt.Fprintf(&b, "// Embed it in your implementation for forward-compatible stubs.\n")
		fmt.Fprintf(&b, "type Unimplemented%sServer struct{}\n\n", svc.ServiceName)
		for _, m := range svc.Methods {
			fmt.Fprintf(&b, "func (Unimplemented%sServer) %s(context.Context, *%s) (*%s, error) {\n", svc.ServiceName, m.Name, m.InputGoIdent, m.OutputGoIdent)
			fmt.Fprintf(&b, "\treturn nil, status.Error(codes.Unimplemented, %q)\n", m.Name+" not implemented")
			b.WriteString("}\n\n")
		}

		// Registration function.
		fmt.Fprintf(&b, "// Register%s wires srv into s using an internal delegation adapter.\n", svc.ServiceName)
		fmt.Fprintf(&b, "// W5-6 will inject authz/tracing/request-id middleware into the adapter.\n")
		fmt.Fprintf(&b, "func Register%s(s *grpc.Server, srv %sServer) {\n", svc.ServiceName, svc.ServiceName)
		fmt.Fprintf(&b, "\t// TODO(W5-6): register via pb.Register%sServer once grpc-gateway dep is added.\n", svc.ServiceName)
		fmt.Fprintf(&b, "\t_ = &%sAdapter{srv: srv} // compile-time check\n", lower)
		b.WriteString("\t_ = s\n")
		b.WriteString("}\n\n")

		// Adapter struct (unexported).
		fmt.Fprintf(&b, "type %sAdapter struct{ srv %sServer }\n\n", lower, svc.ServiceName)
		for _, m := range svc.Methods {
			fmt.Fprintf(&b, "func (a *%sAdapter) %s(ctx context.Context, req *%s) (*%s, error) {\n", lower, m.Name, m.InputGoIdent, m.OutputGoIdent)
			fmt.Fprintf(&b, "\treturn a.srv.%s(ctx, req)\n", m.Name)
			b.WriteString("}\n\n")
		}
	}

	return b.String()
}

func lcFirst(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToLower(s[:1]) + s[1:]
}
