package main

import (
	"fmt"
	"strings"
)

// messageInfo describes a proto message for storage code generation.
type messageInfo struct {
	MessageName  string
	PbPkgName    string // Go package name of the generated proto package (e.g. "widgetsv1")
	PbImportPath string // Go import path of the generated proto package
	Fields       []fieldInfo
}

// fieldInfo describes a single proto message field.
type fieldInfo struct {
	Name        string
	GoFieldName string // Go struct field name (e.g. "PageSize" for proto "page_size")
	GoType      string
	SnakeName   string
	IsID        bool // this field is the resource primary key
	IsRepeated  bool // repeated field — skipped in GORM model with a TODO
	IsMessage   bool // nested message field — skipped with a TODO
}

// renderStorageFile generates the .storage.go content for the given storage
// package and messages. Returns an empty string when messages is empty.
func renderStorageFile(storagePkgName string, messages []messageInfo) string {
	if len(messages) == 0 {
		return ""
	}

	var b strings.Builder

	b.WriteString("// Code generated by protoc-gen-storage. DO NOT EDIT.\n")
	b.WriteString("// source: (proto input)\n\n")
	fmt.Fprintf(&b, "package %s\n\n", storagePkgName)
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"encoding/base64\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"strconv\"\n")
	b.WriteString("\t\"time\"\n\n")
	b.WriteString("\t\"gorm.io/gorm\"\n\n")
	b.WriteString("\t\"github.com/infobloxopen/devedge-sdk/persistence\"\n")
	b.WriteString(")\n\n")

	// Suppress unused import warnings for packages that may not be referenced
	// in the small toy case. Generated code always references them via CRUD methods.
	b.WriteString("var (\n")
	b.WriteString("\t_ = base64.StdEncoding\n")
	b.WriteString("\t_ = fmt.Sprintf\n")
	b.WriteString("\t_ = strconv.Itoa\n")
	b.WriteString(")\n\n")

	for _, msg := range messages {
		renderMessage(&b, msg)
	}

	return b.String()
}

func renderMessage(b *strings.Builder, msg messageInfo) {
	// GORM model struct.
	fmt.Fprintf(b, "// %sModel is the GORM model for %s.\n", msg.MessageName, msg.MessageName)
	fmt.Fprintf(b, "type %sModel struct {\n", msg.MessageName)
	fmt.Fprintf(b, "\tID        string         `gorm:\"primaryKey;type:varchar(36)\"`\n")

	for _, f := range msg.Fields {
		if f.IsID {
			continue // ID is already emitted above
		}
		if f.IsRepeated {
			fmt.Fprintf(b, "\t// TODO: repeated field %s skipped — JSONB serialization needed (W5-6)\n", f.Name)
			continue
		}
		if f.IsMessage {
			fmt.Fprintf(b, "\t// TODO: nested message %s skipped — serialization strategy TBD (W5-6)\n", f.Name)
			continue
		}
		goFieldName := goFieldName(f)
		fmt.Fprintf(b, "\t%s %s `gorm:\"column:%s\"`\n", goFieldName, f.GoType, f.SnakeName)
	}

	b.WriteString("\tETag      string         `gorm:\"column:etag\"`\n")
	b.WriteString("\tCreatedAt time.Time\n")
	b.WriteString("\tUpdatedAt time.Time\n")
	b.WriteString("\tDeletedAt gorm.DeletedAt `gorm:\"index\"`\n")
	b.WriteString("}\n\n")

	pbType := fmt.Sprintf("*%s", msg.MessageName)
	pbPkg := msg.PbPkgName
	if pbPkg != "" {
		pbType = fmt.Sprintf("*%s.%s", pbPkg, msg.MessageName)
	}

	// toModel helper.
	fmt.Fprintf(b, "func toModel_%s(p %s) *%sModel {\n", msg.MessageName, pbType, msg.MessageName)
	b.WriteString("\tif p == nil {\n\t\treturn nil\n\t}\n")
	fmt.Fprintf(b, "\tm := &%sModel{ID: p.Id}\n", msg.MessageName)
	for _, f := range msg.Fields {
		if f.IsID || f.IsRepeated || f.IsMessage {
			continue
		}
		gfn := goFieldName(f)
		fmt.Fprintf(b, "\tm.%s = p.%s\n", gfn, gfn)
	}
	b.WriteString("\treturn m\n}\n\n")

	// fromModel helper.
	fmt.Fprintf(b, "func fromModel_%s(m *%sModel) %s {\n", msg.MessageName, msg.MessageName, pbType)
	b.WriteString("\tif m == nil {\n\t\treturn nil\n\t}\n")
	if pbPkg != "" {
		fmt.Fprintf(b, "\tp := &%s.%s{Id: m.ID}\n", pbPkg, msg.MessageName)
	} else {
		fmt.Fprintf(b, "\tp := &%s{Id: m.ID}\n", msg.MessageName)
	}
	for _, f := range msg.Fields {
		if f.IsID || f.IsRepeated || f.IsMessage {
			continue
		}
		gfn := goFieldName(f)
		fmt.Fprintf(b, "\tp.%s = m.%s\n", gfn, gfn)
	}
	b.WriteString("\treturn p\n}\n\n")

	// Repository struct + constructor.
	fmt.Fprintf(b, "// %sRepository is a GORM-backed persistence.Repository for %s.\n", msg.MessageName, pbType)
	fmt.Fprintf(b, "type %sRepository struct{ db *gorm.DB }\n\n", msg.MessageName)
	fmt.Fprintf(b, "// New%sRepository creates a repository backed by db.\n", msg.MessageName)
	fmt.Fprintf(b, "func New%sRepository(db *gorm.DB) *%sRepository {\n", msg.MessageName, msg.MessageName)
	fmt.Fprintf(b, "\treturn &%sRepository{db: db}\n}\n\n", msg.MessageName)

	// Get.
	fmt.Fprintf(b, "func (r *%sRepository) Get(ctx context.Context, key string) (%s, error) {\n", msg.MessageName, pbType)
	fmt.Fprintf(b, "\tvar m %sModel\n", msg.MessageName)
	b.WriteString("\tif err := r.db.WithContext(ctx).Where(\"id = ?\", key).First(&m).Error; err != nil {\n")
	b.WriteString("\t\tif err == gorm.ErrRecordNotFound {\n")
	fmt.Fprintf(b, "\t\t\treturn nil, persistence.ErrNotFound\n")
	b.WriteString("\t\t}\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"get %s: %%w\", err)\n", msg.MessageName)
	b.WriteString("\t}\n")
	fmt.Fprintf(b, "\treturn fromModel_%s(&m), nil\n}\n\n", msg.MessageName)

	// List.
	fmt.Fprintf(b, "func (r *%sRepository) List(ctx context.Context, opts persistence.ListOptions) ([]%s, string, error) {\n", msg.MessageName, pbType)
	fmt.Fprintf(b, "\tvar models []%sModel\n", msg.MessageName)
	b.WriteString("\tq := r.db.WithContext(ctx)\n")
	b.WriteString("\tif opts.Filter != \"\" {\n\t\tq = q.Where(opts.Filter)\n\t}\n")
	b.WriteString("\tpageSize := opts.PageSize\n")
	b.WriteString("\tif pageSize <= 0 {\n\t\tpageSize = 50\n\t}\n")
	b.WriteString("\toffset := 0\n")
	b.WriteString("\tif opts.PageToken != \"\" {\n")
	b.WriteString("\t\tif dec, err := base64.StdEncoding.DecodeString(opts.PageToken); err == nil {\n")
	b.WriteString("\t\t\toffset, _ = strconv.Atoi(string(dec))\n")
	b.WriteString("\t\t}\n\t}\n")
	b.WriteString("\tif err := q.Limit(pageSize).Offset(offset).Find(&models).Error; err != nil {\n")
	fmt.Fprintf(b, "\t\treturn nil, \"\", fmt.Errorf(\"list %s: %%w\", err)\n", msg.MessageName)
	b.WriteString("\t}\n")
	fmt.Fprintf(b, "\tout := make([]%s, len(models))\n", pbType)
	b.WriteString("\tfor i := range models {\n")
	fmt.Fprintf(b, "\t\tout[i] = fromModel_%s(&models[i])\n", msg.MessageName)
	b.WriteString("\t}\n")
	b.WriteString("\tnextToken := \"\"\n")
	fmt.Fprintf(b, "\tif len(models) == pageSize {\n")
	b.WriteString("\t\tnextToken = base64.StdEncoding.EncodeToString([]byte(strconv.Itoa(offset + pageSize)))\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn out, nextToken, nil\n}\n\n")

	// Create.
	fmt.Fprintf(b, "func (r *%sRepository) Create(ctx context.Context, entity %s) (%s, error) {\n", msg.MessageName, pbType, pbType)
	fmt.Fprintf(b, "\tm := toModel_%s(entity)\n", msg.MessageName)
	b.WriteString("\tif err := r.db.WithContext(ctx).Create(m).Error; err != nil {\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"create %s: %%w\", err)\n", msg.MessageName)
	b.WriteString("\t}\n")
	fmt.Fprintf(b, "\treturn fromModel_%s(m), nil\n}\n\n", msg.MessageName)

	// Update.
	fmt.Fprintf(b, "func (r *%sRepository) Update(ctx context.Context, key string, entity %s, fieldMask ...string) (%s, error) {\n", msg.MessageName, pbType, pbType)
	fmt.Fprintf(b, "\tm := toModel_%s(entity)\n", msg.MessageName)
	b.WriteString("\tm.ID = key\n")
	b.WriteString("\tq := r.db.WithContext(ctx).Model(m).Where(\"id = ?\", key)\n")
	b.WriteString("\tif len(fieldMask) > 0 {\n")
	b.WriteString("\t\tq = q.Select(fieldMask)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := q.Updates(m).Error; err != nil {\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"update %s: %%w\", err)\n", msg.MessageName)
	b.WriteString("\t}\n")
	fmt.Fprintf(b, "\treturn r.Get(ctx, key)\n}\n\n")

	// Delete.
	fmt.Fprintf(b, "func (r *%sRepository) Delete(ctx context.Context, key string) error {\n", msg.MessageName)
	fmt.Fprintf(b, "\tif err := r.db.WithContext(ctx).Where(\"id = ?\", key).Delete(&%sModel{}).Error; err != nil {\n", msg.MessageName)
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(\"delete %s: %%w\", err)\n", msg.MessageName)
	b.WriteString("\t}\n\treturn nil\n}\n\n")

	// Compile-time interface check.
	fmt.Fprintf(b, "// compile-time check.\n")
	fmt.Fprintf(b, "var _ persistence.Repository[%s, string] = (*%sRepository)(nil)\n\n", pbType, msg.MessageName)
}

func ucFirst(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// goFieldName returns the Go struct field name for a proto field.
// When GoFieldName is populated by the protogen plugin (the authoritative source),
// use it. Otherwise fall back to ucFirst of the proto field name (unit-test path).
func goFieldName(f fieldInfo) string {
	if f.GoFieldName != "" {
		return f.GoFieldName
	}
	return ucFirst(f.Name)
}
