// Code generated by protoc-gen-ent. DO NOT EDIT.
package ent

import entapikey "github.com/infobloxopen/devedge-sdk/testdata/apikey/ent/apikey"

// WhereAccountID scopes the query to rows belonging to the given tenant. It
// satisfies entrepo.TenantFilterer, which the TenantMixin interceptor calls to
// automatically scope Get/List queries to the calling tenant.
func (q *APIKeyQuery) WhereAccountID(id string) {
	q.Where(entapikey.AccountID(id))
}

// WhereDeleteTimeIsNil restricts the query to live (not soft-deleted) rows. It
// satisfies entrepo.SoftDeleteFilterer, which the SoftDeleteMixin interceptor
// calls to hide soft-deleted rows unless the context opts in via show_deleted.
func (q *APIKeyQuery) WhereDeleteTimeIsNil() {
	q.Where(entapikey.DeleteTimeIsNil())
}
