// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/infobloxopen/devedge-sdk/testdata/apikey/ent/apikey"
	"github.com/infobloxopen/devedge-sdk/testdata/apikey/ent/predicate"
)

// APIKeyUpdate is the builder for updating APIKey entities.
type APIKeyUpdate struct {
	config
	hooks    []Hook
	mutation *APIKeyMutation
}

// Where appends a list predicates to the APIKeyUpdate builder.
func (_u *APIKeyUpdate) Where(ps ...predicate.APIKey) *APIKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *APIKeyUpdate) SetName(v string) *APIKeyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableName(v *string) *APIKeyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *APIKeyUpdate) ClearName() *APIKeyUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetKeyValueHash sets the "key_value_hash" field.
func (_u *APIKeyUpdate) SetKeyValueHash(v string) *APIKeyUpdate {
	_u.mutation.SetKeyValueHash(v)
	return _u
}

// SetNillableKeyValueHash sets the "key_value_hash" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableKeyValueHash(v *string) *APIKeyUpdate {
	if v != nil {
		_u.SetKeyValueHash(*v)
	}
	return _u
}

// ClearKeyValueHash clears the value of the "key_value_hash" field.
func (_u *APIKeyUpdate) ClearKeyValueHash() *APIKeyUpdate {
	_u.mutation.ClearKeyValueHash()
	return _u
}

// SetKeyValueCipher sets the "key_value_cipher" field.
func (_u *APIKeyUpdate) SetKeyValueCipher(v string) *APIKeyUpdate {
	_u.mutation.SetKeyValueCipher(v)
	return _u
}

// SetNillableKeyValueCipher sets the "key_value_cipher" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableKeyValueCipher(v *string) *APIKeyUpdate {
	if v != nil {
		_u.SetKeyValueCipher(*v)
	}
	return _u
}

// ClearKeyValueCipher clears the value of the "key_value_cipher" field.
func (_u *APIKeyUpdate) ClearKeyValueCipher() *APIKeyUpdate {
	_u.mutation.ClearKeyValueCipher()
	return _u
}

// SetKeyPrefix sets the "key_prefix" field.
func (_u *APIKeyUpdate) SetKeyPrefix(v string) *APIKeyUpdate {
	_u.mutation.SetKeyPrefix(v)
	return _u
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableKeyPrefix(v *string) *APIKeyUpdate {
	if v != nil {
		_u.SetKeyPrefix(*v)
	}
	return _u
}

// ClearKeyPrefix clears the value of the "key_prefix" field.
func (_u *APIKeyUpdate) ClearKeyPrefix() *APIKeyUpdate {
	_u.mutation.ClearKeyPrefix()
	return _u
}

// Mutation returns the APIKeyMutation object of the builder.
func (_u *APIKeyUpdate) Mutation() *APIKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *APIKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(apikey.Table, apikey.Columns, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apikey.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(apikey.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.KeyValueHash(); ok {
		_spec.SetField(apikey.FieldKeyValueHash, field.TypeString, value)
	}
	if _u.mutation.KeyValueHashCleared() {
		_spec.ClearField(apikey.FieldKeyValueHash, field.TypeString)
	}
	if value, ok := _u.mutation.KeyValueCipher(); ok {
		_spec.SetField(apikey.FieldKeyValueCipher, field.TypeString, value)
	}
	if _u.mutation.KeyValueCipherCleared() {
		_spec.ClearField(apikey.FieldKeyValueCipher, field.TypeString)
	}
	if value, ok := _u.mutation.KeyPrefix(); ok {
		_spec.SetField(apikey.FieldKeyPrefix, field.TypeString, value)
	}
	if _u.mutation.KeyPrefixCleared() {
		_spec.ClearField(apikey.FieldKeyPrefix, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIKeyUpdateOne is the builder for updating a single APIKey entity.
type APIKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APIKeyMutation
}

// SetName sets the "name" field.
func (_u *APIKeyUpdateOne) SetName(v string) *APIKeyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableName(v *string) *APIKeyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *APIKeyUpdateOne) ClearName() *APIKeyUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetKeyValueHash sets the "key_value_hash" field.
func (_u *APIKeyUpdateOne) SetKeyValueHash(v string) *APIKeyUpdateOne {
	_u.mutation.SetKeyValueHash(v)
	return _u
}

// SetNillableKeyValueHash sets the "key_value_hash" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableKeyValueHash(v *string) *APIKeyUpdateOne {
	if v != nil {
		_u.SetKeyValueHash(*v)
	}
	return _u
}

// ClearKeyValueHash clears the value of the "key_value_hash" field.
func (_u *APIKeyUpdateOne) ClearKeyValueHash() *APIKeyUpdateOne {
	_u.mutation.ClearKeyValueHash()
	return _u
}

// SetKeyValueCipher sets the "key_value_cipher" field.
func (_u *APIKeyUpdateOne) SetKeyValueCipher(v string) *APIKeyUpdateOne {
	_u.mutation.SetKeyValueCipher(v)
	return _u
}

// SetNillableKeyValueCipher sets the "key_value_cipher" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableKeyValueCipher(v *string) *APIKeyUpdateOne {
	if v != nil {
		_u.SetKeyValueCipher(*v)
	}
	return _u
}

// ClearKeyValueCipher clears the value of the "key_value_cipher" field.
func (_u *APIKeyUpdateOne) ClearKeyValueCipher() *APIKeyUpdateOne {
	_u.mutation.ClearKeyValueCipher()
	return _u
}

// SetKeyPrefix sets the "key_prefix" field.
func (_u *APIKeyUpdateOne) SetKeyPrefix(v string) *APIKeyUpdateOne {
	_u.mutation.SetKeyPrefix(v)
	return _u
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableKeyPrefix(v *string) *APIKeyUpdateOne {
	if v != nil {
		_u.SetKeyPrefix(*v)
	}
	return _u
}

// ClearKeyPrefix clears the value of the "key_prefix" field.
func (_u *APIKeyUpdateOne) ClearKeyPrefix() *APIKeyUpdateOne {
	_u.mutation.ClearKeyPrefix()
	return _u
}

// Mutation returns the APIKeyMutation object of the builder.
func (_u *APIKeyUpdateOne) Mutation() *APIKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the APIKeyUpdate builder.
func (_u *APIKeyUpdateOne) Where(ps ...predicate.APIKey) *APIKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIKeyUpdateOne) Select(field string, fields ...string) *APIKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIKey entity.
func (_u *APIKeyUpdateOne) Save(ctx context.Context) (*APIKey, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyUpdateOne) SaveX(ctx context.Context) *APIKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *APIKeyUpdateOne) sqlSave(ctx context.Context) (_node *APIKey, err error) {
	_spec := sqlgraph.NewUpdateSpec(apikey.Table, apikey.Columns, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikey.FieldID)
		for _, f := range fields {
			if !apikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apikey.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(apikey.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.KeyValueHash(); ok {
		_spec.SetField(apikey.FieldKeyValueHash, field.TypeString, value)
	}
	if _u.mutation.KeyValueHashCleared() {
		_spec.ClearField(apikey.FieldKeyValueHash, field.TypeString)
	}
	if value, ok := _u.mutation.KeyValueCipher(); ok {
		_spec.SetField(apikey.FieldKeyValueCipher, field.TypeString, value)
	}
	if _u.mutation.KeyValueCipherCleared() {
		_spec.ClearField(apikey.FieldKeyValueCipher, field.TypeString)
	}
	if value, ok := _u.mutation.KeyPrefix(); ok {
		_spec.SetField(apikey.FieldKeyPrefix, field.TypeString, value)
	}
	if _u.mutation.KeyPrefixCleared() {
		_spec.ClearField(apikey.FieldKeyPrefix, field.TypeString)
	}
	_node = &APIKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
