// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/infobloxopen/devedge-sdk/testdata/apikey/ent/servicetoken"
)

// ServiceTokenCreate is the builder for creating a ServiceToken entity.
type ServiceTokenCreate struct {
	config
	mutation *ServiceTokenMutation
	hooks    []Hook
}

// SetLabel sets the "label" field.
func (_c *ServiceTokenCreate) SetLabel(v string) *ServiceTokenCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *ServiceTokenCreate) SetNillableLabel(v *string) *ServiceTokenCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetSecretValuePublicID sets the "secret_value_public_id" field.
func (_c *ServiceTokenCreate) SetSecretValuePublicID(v string) *ServiceTokenCreate {
	_c.mutation.SetSecretValuePublicID(v)
	return _c
}

// SetNillableSecretValuePublicID sets the "secret_value_public_id" field if the given value is not nil.
func (_c *ServiceTokenCreate) SetNillableSecretValuePublicID(v *string) *ServiceTokenCreate {
	if v != nil {
		_c.SetSecretValuePublicID(*v)
	}
	return _c
}

// SetSecretValueSalt sets the "secret_value_salt" field.
func (_c *ServiceTokenCreate) SetSecretValueSalt(v string) *ServiceTokenCreate {
	_c.mutation.SetSecretValueSalt(v)
	return _c
}

// SetNillableSecretValueSalt sets the "secret_value_salt" field if the given value is not nil.
func (_c *ServiceTokenCreate) SetNillableSecretValueSalt(v *string) *ServiceTokenCreate {
	if v != nil {
		_c.SetSecretValueSalt(*v)
	}
	return _c
}

// SetSecretValueHash sets the "secret_value_hash" field.
func (_c *ServiceTokenCreate) SetSecretValueHash(v string) *ServiceTokenCreate {
	_c.mutation.SetSecretValueHash(v)
	return _c
}

// SetNillableSecretValueHash sets the "secret_value_hash" field if the given value is not nil.
func (_c *ServiceTokenCreate) SetNillableSecretValueHash(v *string) *ServiceTokenCreate {
	if v != nil {
		_c.SetSecretValueHash(*v)
	}
	return _c
}

// SetSecretValueHashspec sets the "secret_value_hashspec" field.
func (_c *ServiceTokenCreate) SetSecretValueHashspec(v string) *ServiceTokenCreate {
	_c.mutation.SetSecretValueHashspec(v)
	return _c
}

// SetNillableSecretValueHashspec sets the "secret_value_hashspec" field if the given value is not nil.
func (_c *ServiceTokenCreate) SetNillableSecretValueHashspec(v *string) *ServiceTokenCreate {
	if v != nil {
		_c.SetSecretValueHashspec(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ServiceTokenCreate) SetID(v string) *ServiceTokenCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ServiceTokenMutation object of the builder.
func (_c *ServiceTokenCreate) Mutation() *ServiceTokenMutation {
	return _c.mutation
}

// Save creates the ServiceToken in the database.
func (_c *ServiceTokenCreate) Save(ctx context.Context) (*ServiceToken, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ServiceTokenCreate) SaveX(ctx context.Context) *ServiceToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ServiceTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ServiceTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ServiceTokenCreate) check() error {
	return nil
}

func (_c *ServiceTokenCreate) sqlSave(ctx context.Context) (*ServiceToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ServiceToken.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ServiceTokenCreate) createSpec() (*ServiceToken, *sqlgraph.CreateSpec) {
	var (
		_node = &ServiceToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(servicetoken.Table, sqlgraph.NewFieldSpec(servicetoken.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(servicetoken.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.SecretValuePublicID(); ok {
		_spec.SetField(servicetoken.FieldSecretValuePublicID, field.TypeString, value)
		_node.SecretValuePublicID = value
	}
	if value, ok := _c.mutation.SecretValueSalt(); ok {
		_spec.SetField(servicetoken.FieldSecretValueSalt, field.TypeString, value)
		_node.SecretValueSalt = value
	}
	if value, ok := _c.mutation.SecretValueHash(); ok {
		_spec.SetField(servicetoken.FieldSecretValueHash, field.TypeString, value)
		_node.SecretValueHash = value
	}
	if value, ok := _c.mutation.SecretValueHashspec(); ok {
		_spec.SetField(servicetoken.FieldSecretValueHashspec, field.TypeString, value)
		_node.SecretValueHashspec = value
	}
	return _node, _spec
}

// ServiceTokenCreateBulk is the builder for creating many ServiceToken entities in bulk.
type ServiceTokenCreateBulk struct {
	config
	err      error
	builders []*ServiceTokenCreate
}

// Save creates the ServiceToken entities in the database.
func (_c *ServiceTokenCreateBulk) Save(ctx context.Context) ([]*ServiceToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ServiceToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServiceTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ServiceTokenCreateBulk) SaveX(ctx context.Context) []*ServiceToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ServiceTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ServiceTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
