// Code generated by protoc-gen-ent. DO NOT EDIT.
package iamv1

// AccountEntColumns maps proto field names to ent DB column names for safe
// AIP-160 filter / AIP-132 order_by parsing on the ent backend.
var AccountEntColumns = map[string]string{
	"id":           "id",
	"display_name": "display_name",
}
