// Code generated by protoc-gen-svc. DO NOT EDIT.
// source: (proto input)

package iamv1

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"

	"github.com/infobloxopen/devedge-sdk/persistence"
	"github.com/infobloxopen/devedge-sdk/server"
)

// RegisterAccountService wires srv into the server's gRPC handler and HTTP gateway,
// records its methods, and contributes AccountServiceAuthzRules to the server. The
// boot-time authz completeness gate runs at server.Serve over the accumulated
// rule set (fail-closed).
func RegisterAccountService(s *server.Server, srv AccountServiceServer) error {
	s.RecordMethods(
		AccountService_GetAccount_FullMethodName,
		AccountService_ListAccounts_FullMethodName,
		AccountService_CreateAccount_FullMethodName,
	)
	s.AddRules(AccountServiceAuthzRules...)
	RegisterAccountServiceServer(s.GRPCServer(), srv)
	s.RegisterGateway(func(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
		return RegisterAccountServiceHandlerClient(ctx, mux, NewAccountServiceClient(conn))
	})
	return nil
}

// AccountServiceCRUDHandler is the generated default handler for AccountService. It implements the
// detected AIP standard methods by delegating to Repo; custom or unmatched RPCs
// remain Unimplemented (override by embedding this type). Tenant stamping and
// read_mask/field_mask are handled by the repository and the interceptor chain,
// so the handler does not duplicate them. DO NOT EDIT.
type AccountServiceCRUDHandler struct {
	UnimplementedAccountServiceServer
	Repo persistence.Repository[*Account, string]
}

func (h *AccountServiceCRUDHandler) GetAccount(ctx context.Context, req *GetAccountRequest) (*Account, error) {
	key := req.GetId()
	return h.Repo.Get(ctx, key)
}

func (h *AccountServiceCRUDHandler) ListAccounts(ctx context.Context, req *ListAccountsRequest) (*ListAccountsResponse, error) {
	items, next, err := h.Repo.List(ctx, persistence.ListOptions{
		PageSize:  int(req.GetPageSize()),
		PageToken: req.GetPageToken(),
	})
	if err != nil {
		return nil, err
	}
	return &ListAccountsResponse{Accounts: items, NextPageToken: next}, nil
}

func (h *AccountServiceCRUDHandler) CreateAccount(ctx context.Context, req *CreateAccountRequest) (*Account, error) {
	return h.Repo.Create(ctx, req.GetAccount())
}

// NewAccountServiceHandler returns the generated default CRUD handler backed by repo. Embed
// the returned type (or this struct) to override individual methods before
// registering it via RegisterAccountService.
func NewAccountServiceHandler(repo persistence.Repository[*Account, string]) *AccountServiceCRUDHandler {
	return &AccountServiceCRUDHandler{Repo: repo}
}

// RegisterAccountServiceWithRepository is the one-call CRUD path: it constructs the
// generated default handler over repo and registers it via RegisterAccountService
// (gRPC + REST gateway + authz rules). Use the New<Svc>Handler + Register<Svc>
// pair instead when you need to wrap/override the default handler.
func RegisterAccountServiceWithRepository(s *server.Server, repo persistence.Repository[*Account, string]) error {
	return RegisterAccountService(s, NewAccountServiceHandler(repo))
}

// RegisterUserService wires srv into the server's gRPC handler and HTTP gateway,
// records its methods, and contributes UserServiceAuthzRules to the server. The
// boot-time authz completeness gate runs at server.Serve over the accumulated
// rule set (fail-closed).
func RegisterUserService(s *server.Server, srv UserServiceServer) error {
	s.RecordMethods(
		UserService_GetUser_FullMethodName,
		UserService_ListUsers_FullMethodName,
		UserService_CreateUser_FullMethodName,
	)
	s.AddRules(UserServiceAuthzRules...)
	RegisterUserServiceServer(s.GRPCServer(), srv)
	s.RegisterGateway(func(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
		return RegisterUserServiceHandlerClient(ctx, mux, NewUserServiceClient(conn))
	})
	return nil
}

// UserServiceCRUDHandler is the generated default handler for UserService. It implements the
// detected AIP standard methods by delegating to Repo; custom or unmatched RPCs
// remain Unimplemented (override by embedding this type). Tenant stamping and
// read_mask/field_mask are handled by the repository and the interceptor chain,
// so the handler does not duplicate them. DO NOT EDIT.
type UserServiceCRUDHandler struct {
	UnimplementedUserServiceServer
	Repo persistence.Repository[*User, string]
}

func (h *UserServiceCRUDHandler) GetUser(ctx context.Context, req *GetUserRequest) (*User, error) {
	key := req.GetId()
	return h.Repo.Get(ctx, key)
}

func (h *UserServiceCRUDHandler) ListUsers(ctx context.Context, req *ListUsersRequest) (*ListUsersResponse, error) {
	items, next, err := h.Repo.List(ctx, persistence.ListOptions{
		PageSize:  int(req.GetPageSize()),
		PageToken: req.GetPageToken(),
	})
	if err != nil {
		return nil, err
	}
	return &ListUsersResponse{Users: items, NextPageToken: next}, nil
}

func (h *UserServiceCRUDHandler) CreateUser(ctx context.Context, req *CreateUserRequest) (*User, error) {
	return h.Repo.Create(ctx, req.GetUser())
}

// NewUserServiceHandler returns the generated default CRUD handler backed by repo. Embed
// the returned type (or this struct) to override individual methods before
// registering it via RegisterUserService.
func NewUserServiceHandler(repo persistence.Repository[*User, string]) *UserServiceCRUDHandler {
	return &UserServiceCRUDHandler{Repo: repo}
}

// RegisterUserServiceWithRepository is the one-call CRUD path: it constructs the
// generated default handler over repo and registers it via RegisterUserService
// (gRPC + REST gateway + authz rules). Use the New<Svc>Handler + Register<Svc>
// pair instead when you need to wrap/override the default handler.
func RegisterUserServiceWithRepository(s *server.Server, repo persistence.Repository[*User, string]) error {
	return RegisterUserService(s, NewUserServiceHandler(repo))
}

// RegisterGroupService wires srv into the server's gRPC handler and HTTP gateway,
// records its methods, and contributes GroupServiceAuthzRules to the server. The
// boot-time authz completeness gate runs at server.Serve over the accumulated
// rule set (fail-closed).
func RegisterGroupService(s *server.Server, srv GroupServiceServer) error {
	s.RecordMethods(
		GroupService_GetGroup_FullMethodName,
		GroupService_ListGroups_FullMethodName,
		GroupService_CreateGroup_FullMethodName,
	)
	s.AddRules(GroupServiceAuthzRules...)
	RegisterGroupServiceServer(s.GRPCServer(), srv)
	s.RegisterGateway(func(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
		return RegisterGroupServiceHandlerClient(ctx, mux, NewGroupServiceClient(conn))
	})
	return nil
}

// GroupServiceCRUDHandler is the generated default handler for GroupService. It implements the
// detected AIP standard methods by delegating to Repo; custom or unmatched RPCs
// remain Unimplemented (override by embedding this type). Tenant stamping and
// read_mask/field_mask are handled by the repository and the interceptor chain,
// so the handler does not duplicate them. DO NOT EDIT.
type GroupServiceCRUDHandler struct {
	UnimplementedGroupServiceServer
	Repo persistence.Repository[*Group, string]
}

func (h *GroupServiceCRUDHandler) GetGroup(ctx context.Context, req *GetGroupRequest) (*Group, error) {
	key := req.GetId()
	return h.Repo.Get(ctx, key)
}

func (h *GroupServiceCRUDHandler) ListGroups(ctx context.Context, req *ListGroupsRequest) (*ListGroupsResponse, error) {
	items, next, err := h.Repo.List(ctx, persistence.ListOptions{
		PageSize:  int(req.GetPageSize()),
		PageToken: req.GetPageToken(),
	})
	if err != nil {
		return nil, err
	}
	return &ListGroupsResponse{Groups: items, NextPageToken: next}, nil
}

func (h *GroupServiceCRUDHandler) CreateGroup(ctx context.Context, req *CreateGroupRequest) (*Group, error) {
	return h.Repo.Create(ctx, req.GetGroup())
}

// NewGroupServiceHandler returns the generated default CRUD handler backed by repo. Embed
// the returned type (or this struct) to override individual methods before
// registering it via RegisterGroupService.
func NewGroupServiceHandler(repo persistence.Repository[*Group, string]) *GroupServiceCRUDHandler {
	return &GroupServiceCRUDHandler{Repo: repo}
}

// RegisterGroupServiceWithRepository is the one-call CRUD path: it constructs the
// generated default handler over repo and registers it via RegisterGroupService
// (gRPC + REST gateway + authz rules). Use the New<Svc>Handler + Register<Svc>
// pair instead when you need to wrap/override the default handler.
func RegisterGroupServiceWithRepository(s *server.Server, repo persistence.Repository[*Group, string]) error {
	return RegisterGroupService(s, NewGroupServiceHandler(repo))
}

// RegisterMembershipService wires srv into the server's gRPC handler and HTTP gateway,
// records its methods, and contributes MembershipServiceAuthzRules to the server. The
// boot-time authz completeness gate runs at server.Serve over the accumulated
// rule set (fail-closed).
func RegisterMembershipService(s *server.Server, srv MembershipServiceServer) error {
	s.RecordMethods(
		MembershipService_GetMembership_FullMethodName,
		MembershipService_ListMemberships_FullMethodName,
	)
	s.AddRules(MembershipServiceAuthzRules...)
	s.RecordMemberBinding(server.MemberBinding{
		Resource:     "Membership",
		Root:         "Group",
		WriteMethods: []string{},
	})
	RegisterMembershipServiceServer(s.GRPCServer(), srv)
	s.RegisterGateway(func(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
		return RegisterMembershipServiceHandlerClient(ctx, mux, NewMembershipServiceClient(conn))
	})
	return nil
}

// MembershipServiceCRUDHandler is the generated default handler for MembershipService. It implements the
// detected AIP standard methods by delegating to Repo; custom or unmatched RPCs
// remain Unimplemented (override by embedding this type). Tenant stamping and
// read_mask/field_mask are handled by the repository and the interceptor chain,
// so the handler does not duplicate them. DO NOT EDIT.
type MembershipServiceCRUDHandler struct {
	UnimplementedMembershipServiceServer
	Repo persistence.Repository[*Membership, string]
}

func (h *MembershipServiceCRUDHandler) GetMembership(ctx context.Context, req *GetMembershipRequest) (*Membership, error) {
	key := req.GetId()
	return h.Repo.Get(ctx, key)
}

func (h *MembershipServiceCRUDHandler) ListMemberships(ctx context.Context, req *ListMembershipsRequest) (*ListMembershipsResponse, error) {
	items, next, err := h.Repo.List(ctx, persistence.ListOptions{
		PageSize:  int(req.GetPageSize()),
		PageToken: req.GetPageToken(),
	})
	if err != nil {
		return nil, err
	}
	return &ListMembershipsResponse{Memberships: items, NextPageToken: next}, nil
}

// NewMembershipServiceHandler returns the generated default CRUD handler backed by repo. Embed
// the returned type (or this struct) to override individual methods before
// registering it via RegisterMembershipService.
func NewMembershipServiceHandler(repo persistence.Repository[*Membership, string]) *MembershipServiceCRUDHandler {
	return &MembershipServiceCRUDHandler{Repo: repo}
}

// RegisterMembershipServiceWithRepository is the one-call CRUD path: it constructs the
// generated default handler over repo and registers it via RegisterMembershipService
// (gRPC + REST gateway + authz rules). Use the New<Svc>Handler + Register<Svc>
// pair instead when you need to wrap/override the default handler.
func RegisterMembershipServiceWithRepository(s *server.Server, repo persistence.Repository[*Membership, string]) error {
	return RegisterMembershipService(s, NewMembershipServiceHandler(repo))
}

// RegisterApiKeyService wires srv into the server's gRPC handler and HTTP gateway,
// records its methods, and contributes ApiKeyServiceAuthzRules to the server. The
// boot-time authz completeness gate runs at server.Serve over the accumulated
// rule set (fail-closed).
func RegisterApiKeyService(s *server.Server, srv ApiKeyServiceServer) error {
	s.RecordMethods(
		ApiKeyService_GetApiKey_FullMethodName,
		ApiKeyService_ListApiKeys_FullMethodName,
		ApiKeyService_CreateApiKey_FullMethodName,
	)
	s.AddRules(ApiKeyServiceAuthzRules...)
	RegisterApiKeyServiceServer(s.GRPCServer(), srv)
	s.RegisterGateway(func(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
		return RegisterApiKeyServiceHandlerClient(ctx, mux, NewApiKeyServiceClient(conn))
	})
	return nil
}

// ApiKeyServiceCRUDHandler is the generated default handler for ApiKeyService. It implements the
// detected AIP standard methods by delegating to Repo; custom or unmatched RPCs
// remain Unimplemented (override by embedding this type). Tenant stamping and
// read_mask/field_mask are handled by the repository and the interceptor chain,
// so the handler does not duplicate them. DO NOT EDIT.
type ApiKeyServiceCRUDHandler struct {
	UnimplementedApiKeyServiceServer
	Repo persistence.Repository[*ApiKey, string]
}

func (h *ApiKeyServiceCRUDHandler) GetApiKey(ctx context.Context, req *GetApiKeyRequest) (*ApiKey, error) {
	key := req.GetId()
	return h.Repo.Get(ctx, key)
}

func (h *ApiKeyServiceCRUDHandler) ListApiKeys(ctx context.Context, req *ListApiKeysRequest) (*ListApiKeysResponse, error) {
	items, next, err := h.Repo.List(ctx, persistence.ListOptions{
		PageSize:  int(req.GetPageSize()),
		PageToken: req.GetPageToken(),
	})
	if err != nil {
		return nil, err
	}
	return &ListApiKeysResponse{ApiKeys: items, NextPageToken: next}, nil
}

func (h *ApiKeyServiceCRUDHandler) CreateApiKey(ctx context.Context, req *CreateApiKeyRequest) (*ApiKey, error) {
	return h.Repo.Create(ctx, req.GetApiKey())
}

// NewApiKeyServiceHandler returns the generated default CRUD handler backed by repo. Embed
// the returned type (or this struct) to override individual methods before
// registering it via RegisterApiKeyService.
func NewApiKeyServiceHandler(repo persistence.Repository[*ApiKey, string]) *ApiKeyServiceCRUDHandler {
	return &ApiKeyServiceCRUDHandler{Repo: repo}
}

// RegisterApiKeyServiceWithRepository is the one-call CRUD path: it constructs the
// generated default handler over repo and registers it via RegisterApiKeyService
// (gRPC + REST gateway + authz rules). Use the New<Svc>Handler + Register<Svc>
// pair instead when you need to wrap/override the default handler.
func RegisterApiKeyServiceWithRepository(s *server.Server, repo persistence.Repository[*ApiKey, string]) error {
	return RegisterApiKeyService(s, NewApiKeyServiceHandler(repo))
}
