// Code generated by protoc-gen-ent. DO NOT EDIT.
package iamv1

import (
	"context"
	"fmt"

	"github.com/infobloxopen/devedge-sdk/middleware"
	"github.com/infobloxopen/devedge-sdk/persistence"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	ent "github.com/infobloxopen/devedge-sdk/testdata/iam/ent"
	entmembership "github.com/infobloxopen/devedge-sdk/testdata/iam/ent/membership"
)

// MembershipEntRepository adds atomic AIP-137 batch methods to the ent-backed Membership,
// making it a persistence.BatchRepository. Standard methods come from the
// embedded hand-written adapter.
type MembershipEntRepository struct {
	persistence.Repository[*Membership, string]
	client *ent.Client
}

// NewMembershipEntBatchRepository wraps the hand-written ent adapter with batch support.
func NewMembershipEntBatchRepository(client *ent.Client) *MembershipEntRepository {
	return &MembershipEntRepository{Repository: NewMembershipEntRepository(client), client: client}
}

func membershipInMask(mask []string, field string) bool {
	if len(mask) == 0 {
		return true
	}
	for _, m := range mask {
		if m == field {
			return true
		}
	}
	return false
}

func (r *MembershipEntRepository) batchModelClient(ctx context.Context) *ent.MembershipClient {
	if h, ok := persistence.TxFromContext(ctx); ok {
		if tx, ok := h.(*ent.Tx); ok {
			return tx.Membership
		}
	}
	return r.client.Membership
}

func (r *MembershipEntRepository) batchTx(ctx context.Context) (*ent.Tx, bool, error) {
	if h, ok := persistence.TxFromContext(ctx); ok {
		if tx, ok := h.(*ent.Tx); ok {
			return tx, false, nil
		}
	}
	tx, err := r.client.Tx(ctx)
	return tx, true, err
}

func (r *MembershipEntRepository) BatchGet(ctx context.Context, keys []string) ([]*Membership, error) {
	if len(keys) == 0 {
		return []*Membership{}, nil
	}
	rows, err := r.batchModelClient(ctx).Query().Where(entmembership.IDIn(keys...)).All(ctx)
	if err != nil {
		return nil, fmt.Errorf("batch get membership: %w", err)
	}
	byID := make(map[string]*Membership, len(rows))
	for _, e := range rows {
		byID[e.ID] = fromEntMembership(e)
	}
	out := make([]*Membership, 0, len(keys))
	for _, k := range keys {
		p, ok := byID[k]
		if !ok {
			return nil, persistence.ErrNotFound
		}
		out = append(out, p)
	}
	return out, nil
}

func (r *MembershipEntRepository) BatchUpdate(ctx context.Context, items []persistence.BatchUpdateItem[*Membership, string]) ([]*Membership, error) {
	if len(items) == 0 {
		return []*Membership{}, nil
	}
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) && tenantID == "" {
		return nil, status.Error(codes.PermissionDenied, "membership: no tenant on a tenant-scoped batch update")
	}
	tx, ownTx, err := r.batchTx(ctx)
	if err != nil {
		return nil, fmt.Errorf("begin tx: %w", err)
	}
	rollback := func() {
		if ownTx {
			_ = tx.Rollback()
		}
	}
	out := make([]*Membership, 0, len(items))
	for _, it := range items {
		u := tx.Membership.UpdateOneID(it.Key)
		if !middleware.IsSystemContext(ctx) {
			u = u.Where(entmembership.AccountID(tenantID))
		}
		if membershipInMask(it.FieldMask, "group_id") {
			u = u.SetGroupID(it.Entity.GetGroupId())
		}
		if membershipInMask(it.FieldMask, "user_id") {
			u = u.SetUserID(it.Entity.GetUserId())
		}
		if membershipInMask(it.FieldMask, "role") {
			u = u.SetRole(it.Entity.GetRole())
		}
		saved, serr := u.Save(ctx)
		if serr != nil {
			rollback()
			if ent.IsNotFound(serr) {
				return nil, persistence.ErrNotFound
			}
			return nil, fmt.Errorf("batch update membership: %w", serr)
		}
		out = append(out, fromEntMembership(saved))
	}
	if ownTx {
		if err := tx.Commit(); err != nil {
			return nil, fmt.Errorf("commit tx: %w", err)
		}
	}
	return out, nil
}

func (r *MembershipEntRepository) BatchDelete(ctx context.Context, keys []string) error {
	if len(keys) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(keys))
	uniq := make([]string, 0, len(keys))
	for _, k := range keys {
		if _, ok := seen[k]; ok {
			continue
		}
		seen[k] = struct{}{}
		uniq = append(uniq, k)
	}
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) && tenantID == "" {
		return status.Error(codes.PermissionDenied, "membership: no tenant on a tenant-scoped batch delete")
	}
	tx, ownTx, err := r.batchTx(ctx)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	rollback := func() {
		if ownTx {
			_ = tx.Rollback()
		}
	}
	del := tx.Membership.Delete().Where(entmembership.IDIn(uniq...))
	if !middleware.IsSystemContext(ctx) {
		del = del.Where(entmembership.AccountID(tenantID))
	}
	n, derr := del.Exec(ctx)
	if derr != nil {
		rollback()
		return fmt.Errorf("batch delete membership: %w", derr)
	}
	if n != len(uniq) {
		rollback()
		return persistence.ErrNotFound
	}
	if ownTx {
		return tx.Commit()
	}
	return nil
}

// compile-time check.
var _ persistence.BatchRepository[*Membership, string] = (*MembershipEntRepository)(nil)
