// Code generated by protoc-gen-ent. DO NOT EDIT.
package iamv1

// UserEntColumns maps proto field names to ent DB column names for safe
// AIP-160 filter / AIP-132 order_by parsing on the ent backend.
var UserEntColumns = map[string]string{
	"id":           "id",
	"account_id":   "account_id",
	"email":        "email",
	"display_name": "display_name",
}
