// Code generated by protoc-gen-ent. DO NOT EDIT.
package iamv1

import (
	"context"
	"fmt"

	"github.com/infobloxopen/devedge-sdk/middleware"
	"github.com/infobloxopen/devedge-sdk/middleware/etag"
	"github.com/infobloxopen/devedge-sdk/persistence"
	"github.com/infobloxopen/devedge-sdk/persistence/entrepo"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	ent "github.com/infobloxopen/devedge-sdk/testdata/iam/ent"
	entuser "github.com/infobloxopen/devedge-sdk/testdata/iam/ent/user"
	entpredicate "github.com/infobloxopen/devedge-sdk/testdata/iam/ent/predicate"
)

// NewUserEntRepository wires the generated ent client into a
// persistence.Repository[*User, string].
func NewUserEntRepository(client *ent.Client, opts ...persistence.RepoOption) persistence.Repository[*User, string] {
	userClient := func(ctx context.Context) *ent.UserClient {
		if h, ok := persistence.TxFromContext(ctx); ok {
			if tx, ok := h.(*ent.Tx); ok {
				return tx.User
			}
		}
		return client.User
	}
	idGen := persistence.NewRepoConfig(persistence.UUID7Generator(), opts...).IDGenerator
	return &entrepo.EntRepository[*User, string]{
		Create_: func(ctx context.Context, entity *User) (*User, error) {
			if entity.GetId() == "" {
				entity.Id = idGen.NewID()
			}
			tenantID := middleware.TenantIDFromContext(ctx)
			if !middleware.IsSystemContext(ctx) {
				if tenantID == "" {
					return nil, status.Error(codes.PermissionDenied, "user: no tenant on a tenant-scoped create")
				}
				entity.AccountId = tenantID
			}
			b := userClient(ctx).Create().
				SetID(entity.GetId()).
				SetAccountID(entity.GetAccountId()).
				SetEmail(entity.GetEmail()).
				SetDisplayName(entity.GetDisplayName())
			if ToEntUserOnCreate != nil {
				ToEntUserOnCreate(entity, b)
			}
			created, err := b.Save(ctx)
			if err != nil {
				if ce := persistence.ConstraintError(err); ce != nil {
					return nil, ce
				}
				return nil, fmt.Errorf("create user: %w", err)
			}
			return fromEntUser(created), nil
		},
		Get_: func(ctx context.Context, key string) (*User, error) {
			q := userClient(ctx).Query().Where(entuser.ID(key))
			tenantID := middleware.TenantIDFromContext(ctx)
			if !middleware.IsSystemContext(ctx) {
				if tenantID == "" {
					return nil, status.Error(codes.PermissionDenied, "user: no tenant on a tenant-scoped get")
				}
				q = q.Where(entuser.AccountID(tenantID))
			}
			e, err := q.Only(ctx)
			if err != nil {
				if ent.IsNotFound(err) {
					return nil, persistence.ErrNotFound
				}
				return nil, err
			}
			return fromEntUser(e), nil
		},
		List_: func(ctx context.Context, opts persistence.ListOptions) ([]*User, string, error) {
			q := userClient(ctx).Query()
			if opts.Filter != "" {
				pred, perr := entrepo.FilterPredicate(opts.Filter, UserEntColumns, nil)
				if perr != nil {
					return nil, "", perr
				}
				if pred != nil {
					q = q.Where(entpredicate.User(pred))
				}
			}
			if opts.Search != "" {
				search := opts.Search
				q = q.Where(entpredicate.User(func(sel *sql.Selector) {
					sel.Where(sql.P(func(bld *sql.Builder) {
						switch bld.Dialect() {
						case dialect.Postgres:
							bld.WriteString("to_tsvector('simple', replace(replace(coalesce(CAST(\"email\" AS text), ''), '@', ' '), '.', ' ') || ' ' || replace(replace(coalesce(CAST(\"display_name\" AS text), ''), '@', ' '), '.', ' ')) @@ websearch_to_tsquery('simple', ")
							bld.Arg(search)
							bld.WriteString(")")
						default:
							bld.WriteString("lower(coalesce(CAST(\"email\" AS text), '') || ' ' || coalesce(CAST(\"display_name\" AS text), '')) LIKE '%' || lower(")
							bld.Arg(search)
							bld.WriteString(") || '%'")
						}
					}))
				}))
			}
			if opts.PageSize <= 0 {
				opts.PageSize = 50
			}
			if opts.PageSize > persistence.MaxPageSize {
				opts.PageSize = persistence.MaxPageSize
			}
			offset := 0
			if opts.PageToken != "" {
				fmt.Sscanf(opts.PageToken, "%d", &offset) //nolint:errcheck
			}
			items, err := q.Limit(opts.PageSize).Offset(offset).All(ctx)
			if err != nil {
				return nil, "", err
			}
			out := make([]*User, len(items))
			for i, e := range items {
				out[i] = fromEntUser(e)
			}
			nextToken := ""
			if len(items) == opts.PageSize {
				nextToken = fmt.Sprintf("%d", offset+opts.PageSize)
			}
			return out, nextToken, nil
		},
		Update_: func(ctx context.Context, key string, entity *User, fieldMask ...string) (*User, error) {
			u := userClient(ctx).UpdateOneID(key)
			if userInMask(fieldMask, "email") {
				u = u.SetEmail(entity.GetEmail())
			}
			if userInMask(fieldMask, "display_name") {
				u = u.SetDisplayName(entity.GetDisplayName())
			}
			tenantID := middleware.TenantIDFromContext(ctx)
			if !middleware.IsSystemContext(ctx) {
				if tenantID == "" {
					return nil, status.Error(codes.PermissionDenied, "user: no tenant on a tenant-scoped update")
				}
				u = u.Where(entuser.AccountID(tenantID))
			}
			ifMatch := etag.IfMatchFromContext(ctx)
			if ifMatch != "" {
				u = u.Where(entuser.Etag(ifMatch))
			}
			if ToEntUserOnUpdate != nil {
				ToEntUserOnUpdate(entity, u)
			}
			updated, err := u.Save(ctx)
			if err != nil {
				if ent.IsNotFound(err) && ifMatch != "" {
					check := userClient(ctx).Query().Where(entuser.ID(key))
					if !middleware.IsSystemContext(ctx) {
						check = check.Where(entuser.AccountID(tenantID))
					}
					exists, cerr := check.Exist(ctx)
					if cerr != nil {
						return nil, cerr
					}
					if exists {
						// Row present but its stored etag no longer matches If-Match → stale precondition.
						return nil, persistence.ErrPreconditionFailed
					}
					return nil, persistence.ErrNotFound
				}
				if ent.IsNotFound(err) {
					return nil, persistence.ErrNotFound
				}
				if ce := persistence.ConstraintError(err); ce != nil {
					return nil, ce
				}
				return nil, err
			}
			return fromEntUser(updated), nil
		},
		Delete_: func(ctx context.Context, key string) error {
			del := userClient(ctx).Delete().Where(entuser.ID(key))
			tenantID := middleware.TenantIDFromContext(ctx)
			if !middleware.IsSystemContext(ctx) {
				if tenantID == "" {
					return status.Error(codes.PermissionDenied, "user: no tenant on a tenant-scoped delete")
				}
				del = del.Where(entuser.AccountID(tenantID))
			}
			n, err := del.Exec(ctx)
			if err != nil {
				return err
			}
			if n == 0 {
				return persistence.ErrNotFound
			}
			return nil
		},
	}
}

// FromEntUserCustom, if set, runs at the end of fromEntUser to populate fields the
// generator cannot derive (computed/derived values). Register it from your own
// (regen-safe) file — e.g. in an init(); this generated file never assigns it.
var FromEntUserCustom func(e *ent.User, p *User)

// ToEntUserOnCreate / ToEntUserOnUpdate, if set, run just before the ent builder is
// saved, to set columns the generator does not (e.g. a custom-encoded field).
var ToEntUserOnCreate func(p *User, b *ent.UserCreate)
var ToEntUserOnUpdate func(p *User, u *ent.UserUpdateOne)

// fromEntUser converts a generated ent.User to the proto *User. Secret fields are
// intentionally omitted — they are never returned from storage after creation.
func fromEntUser(e *ent.User) *User {
	if e == nil {
		return nil
	}
	p := &User{
		Id:          e.ID,
		AccountId:   e.AccountID,
		Email:       e.Email,
		DisplayName: e.DisplayName,
		Etag:        e.Etag, // AIP-154: the EtagMixin-stamped token a client echoes as If-Match
	}
	if FromEntUserCustom != nil {
		FromEntUserCustom(e, p)
	}
	return p
}

// GetUserByEmail looks up the User by its unique email value. Tenant-scoped; excludes
// soft-deleted rows. Returns persistence.ErrNotFound when no record matches.
func GetUserByEmail(ctx context.Context, client *ent.Client, value string) (*User, error) {
	if value == "" {
		return nil, persistence.ErrNotFound
	}
	q := client.User.Query().Where(entuser.Email(value))
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) {
		if tenantID == "" {
			return nil, status.Error(codes.PermissionDenied, "user: no tenant on a tenant-scoped get")
		}
		q = q.Where(entuser.AccountID(tenantID))
	}
	e, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, persistence.ErrNotFound
		}
		return nil, err
	}
	return fromEntUser(e), nil
}
