// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/infobloxopen/devedge-sdk/testdata/fleet/ent/fleet"
	"github.com/infobloxopen/devedge-sdk/testdata/fleet/ent/predicate"
	"github.com/infobloxopen/devedge-sdk/testdata/fleet/ent/vehicle"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeFleet   = "Fleet"
	TypeVehicle = "Vehicle"
)

// FleetMutation represents an operation that mutates the Fleet nodes in the graph.
type FleetMutation struct {
	config
	op              Op
	typ             string
	id              *string
	account_id      *string
	delete_time     *time.Time
	display_name    *string
	clearedFields   map[string]struct{}
	vehicles        map[string]struct{}
	removedvehicles map[string]struct{}
	clearedvehicles bool
	done            bool
	oldValue        func(context.Context) (*Fleet, error)
	predicates      []predicate.Fleet
}

var _ ent.Mutation = (*FleetMutation)(nil)

// fleetOption allows management of the mutation configuration using functional options.
type fleetOption func(*FleetMutation)

// newFleetMutation creates new mutation for the Fleet entity.
func newFleetMutation(c config, op Op, opts ...fleetOption) *FleetMutation {
	m := &FleetMutation{
		config:        c,
		op:            op,
		typ:           TypeFleet,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withFleetID sets the ID field of the mutation.
func withFleetID(id string) fleetOption {
	return func(m *FleetMutation) {
		var (
			err   error
			once  sync.Once
			value *Fleet
		)
		m.oldValue = func(ctx context.Context) (*Fleet, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Fleet.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withFleet sets the old Fleet of the mutation.
func withFleet(node *Fleet) fleetOption {
	return func(m *FleetMutation) {
		m.oldValue = func(context.Context) (*Fleet, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m FleetMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m FleetMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Fleet entities.
func (m *FleetMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *FleetMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *FleetMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Fleet.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetAccountID sets the "account_id" field.
func (m *FleetMutation) SetAccountID(s string) {
	m.account_id = &s
}

// AccountID returns the value of the "account_id" field in the mutation.
func (m *FleetMutation) AccountID() (r string, exists bool) {
	v := m.account_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAccountID returns the old "account_id" field's value of the Fleet entity.
// If the Fleet object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FleetMutation) OldAccountID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccountID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccountID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccountID: %w", err)
	}
	return oldValue.AccountID, nil
}

// ResetAccountID resets all changes to the "account_id" field.
func (m *FleetMutation) ResetAccountID() {
	m.account_id = nil
}

// SetDeleteTime sets the "delete_time" field.
func (m *FleetMutation) SetDeleteTime(t time.Time) {
	m.delete_time = &t
}

// DeleteTime returns the value of the "delete_time" field in the mutation.
func (m *FleetMutation) DeleteTime() (r time.Time, exists bool) {
	v := m.delete_time
	if v == nil {
		return
	}
	return *v, true
}

// OldDeleteTime returns the old "delete_time" field's value of the Fleet entity.
// If the Fleet object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FleetMutation) OldDeleteTime(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeleteTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeleteTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeleteTime: %w", err)
	}
	return oldValue.DeleteTime, nil
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (m *FleetMutation) ClearDeleteTime() {
	m.delete_time = nil
	m.clearedFields[fleet.FieldDeleteTime] = struct{}{}
}

// DeleteTimeCleared returns if the "delete_time" field was cleared in this mutation.
func (m *FleetMutation) DeleteTimeCleared() bool {
	_, ok := m.clearedFields[fleet.FieldDeleteTime]
	return ok
}

// ResetDeleteTime resets all changes to the "delete_time" field.
func (m *FleetMutation) ResetDeleteTime() {
	m.delete_time = nil
	delete(m.clearedFields, fleet.FieldDeleteTime)
}

// SetDisplayName sets the "display_name" field.
func (m *FleetMutation) SetDisplayName(s string) {
	m.display_name = &s
}

// DisplayName returns the value of the "display_name" field in the mutation.
func (m *FleetMutation) DisplayName() (r string, exists bool) {
	v := m.display_name
	if v == nil {
		return
	}
	return *v, true
}

// OldDisplayName returns the old "display_name" field's value of the Fleet entity.
// If the Fleet object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FleetMutation) OldDisplayName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDisplayName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDisplayName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDisplayName: %w", err)
	}
	return oldValue.DisplayName, nil
}

// ClearDisplayName clears the value of the "display_name" field.
func (m *FleetMutation) ClearDisplayName() {
	m.display_name = nil
	m.clearedFields[fleet.FieldDisplayName] = struct{}{}
}

// DisplayNameCleared returns if the "display_name" field was cleared in this mutation.
func (m *FleetMutation) DisplayNameCleared() bool {
	_, ok := m.clearedFields[fleet.FieldDisplayName]
	return ok
}

// ResetDisplayName resets all changes to the "display_name" field.
func (m *FleetMutation) ResetDisplayName() {
	m.display_name = nil
	delete(m.clearedFields, fleet.FieldDisplayName)
}

// AddVehicleIDs adds the "vehicles" edge to the Vehicle entity by ids.
func (m *FleetMutation) AddVehicleIDs(ids ...string) {
	if m.vehicles == nil {
		m.vehicles = make(map[string]struct{})
	}
	for i := range ids {
		m.vehicles[ids[i]] = struct{}{}
	}
}

// ClearVehicles clears the "vehicles" edge to the Vehicle entity.
func (m *FleetMutation) ClearVehicles() {
	m.clearedvehicles = true
}

// VehiclesCleared reports if the "vehicles" edge to the Vehicle entity was cleared.
func (m *FleetMutation) VehiclesCleared() bool {
	return m.clearedvehicles
}

// RemoveVehicleIDs removes the "vehicles" edge to the Vehicle entity by IDs.
func (m *FleetMutation) RemoveVehicleIDs(ids ...string) {
	if m.removedvehicles == nil {
		m.removedvehicles = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.vehicles, ids[i])
		m.removedvehicles[ids[i]] = struct{}{}
	}
}

// RemovedVehicles returns the removed IDs of the "vehicles" edge to the Vehicle entity.
func (m *FleetMutation) RemovedVehiclesIDs() (ids []string) {
	for id := range m.removedvehicles {
		ids = append(ids, id)
	}
	return
}

// VehiclesIDs returns the "vehicles" edge IDs in the mutation.
func (m *FleetMutation) VehiclesIDs() (ids []string) {
	for id := range m.vehicles {
		ids = append(ids, id)
	}
	return
}

// ResetVehicles resets all changes to the "vehicles" edge.
func (m *FleetMutation) ResetVehicles() {
	m.vehicles = nil
	m.clearedvehicles = false
	m.removedvehicles = nil
}

// Where appends a list predicates to the FleetMutation builder.
func (m *FleetMutation) Where(ps ...predicate.Fleet) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the FleetMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *FleetMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Fleet, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *FleetMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *FleetMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Fleet).
func (m *FleetMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *FleetMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.account_id != nil {
		fields = append(fields, fleet.FieldAccountID)
	}
	if m.delete_time != nil {
		fields = append(fields, fleet.FieldDeleteTime)
	}
	if m.display_name != nil {
		fields = append(fields, fleet.FieldDisplayName)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *FleetMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case fleet.FieldAccountID:
		return m.AccountID()
	case fleet.FieldDeleteTime:
		return m.DeleteTime()
	case fleet.FieldDisplayName:
		return m.DisplayName()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *FleetMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case fleet.FieldAccountID:
		return m.OldAccountID(ctx)
	case fleet.FieldDeleteTime:
		return m.OldDeleteTime(ctx)
	case fleet.FieldDisplayName:
		return m.OldDisplayName(ctx)
	}
	return nil, fmt.Errorf("unknown Fleet field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FleetMutation) SetField(name string, value ent.Value) error {
	switch name {
	case fleet.FieldAccountID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccountID(v)
		return nil
	case fleet.FieldDeleteTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeleteTime(v)
		return nil
	case fleet.FieldDisplayName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDisplayName(v)
		return nil
	}
	return fmt.Errorf("unknown Fleet field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *FleetMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *FleetMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FleetMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Fleet numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *FleetMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(fleet.FieldDeleteTime) {
		fields = append(fields, fleet.FieldDeleteTime)
	}
	if m.FieldCleared(fleet.FieldDisplayName) {
		fields = append(fields, fleet.FieldDisplayName)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *FleetMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *FleetMutation) ClearField(name string) error {
	switch name {
	case fleet.FieldDeleteTime:
		m.ClearDeleteTime()
		return nil
	case fleet.FieldDisplayName:
		m.ClearDisplayName()
		return nil
	}
	return fmt.Errorf("unknown Fleet nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *FleetMutation) ResetField(name string) error {
	switch name {
	case fleet.FieldAccountID:
		m.ResetAccountID()
		return nil
	case fleet.FieldDeleteTime:
		m.ResetDeleteTime()
		return nil
	case fleet.FieldDisplayName:
		m.ResetDisplayName()
		return nil
	}
	return fmt.Errorf("unknown Fleet field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *FleetMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.vehicles != nil {
		edges = append(edges, fleet.EdgeVehicles)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *FleetMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case fleet.EdgeVehicles:
		ids := make([]ent.Value, 0, len(m.vehicles))
		for id := range m.vehicles {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *FleetMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedvehicles != nil {
		edges = append(edges, fleet.EdgeVehicles)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *FleetMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case fleet.EdgeVehicles:
		ids := make([]ent.Value, 0, len(m.removedvehicles))
		for id := range m.removedvehicles {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *FleetMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedvehicles {
		edges = append(edges, fleet.EdgeVehicles)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *FleetMutation) EdgeCleared(name string) bool {
	switch name {
	case fleet.EdgeVehicles:
		return m.clearedvehicles
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *FleetMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Fleet unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *FleetMutation) ResetEdge(name string) error {
	switch name {
	case fleet.EdgeVehicles:
		m.ResetVehicles()
		return nil
	}
	return fmt.Errorf("unknown Fleet edge %s", name)
}

// VehicleMutation represents an operation that mutates the Vehicle nodes in the graph.
type VehicleMutation struct {
	config
	op            Op
	typ           string
	id            *string
	account_id    *string
	vin           *string
	clearedFields map[string]struct{}
	fleet         *string
	clearedfleet  bool
	done          bool
	oldValue      func(context.Context) (*Vehicle, error)
	predicates    []predicate.Vehicle
}

var _ ent.Mutation = (*VehicleMutation)(nil)

// vehicleOption allows management of the mutation configuration using functional options.
type vehicleOption func(*VehicleMutation)

// newVehicleMutation creates new mutation for the Vehicle entity.
func newVehicleMutation(c config, op Op, opts ...vehicleOption) *VehicleMutation {
	m := &VehicleMutation{
		config:        c,
		op:            op,
		typ:           TypeVehicle,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withVehicleID sets the ID field of the mutation.
func withVehicleID(id string) vehicleOption {
	return func(m *VehicleMutation) {
		var (
			err   error
			once  sync.Once
			value *Vehicle
		)
		m.oldValue = func(ctx context.Context) (*Vehicle, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Vehicle.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withVehicle sets the old Vehicle of the mutation.
func withVehicle(node *Vehicle) vehicleOption {
	return func(m *VehicleMutation) {
		m.oldValue = func(context.Context) (*Vehicle, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m VehicleMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m VehicleMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Vehicle entities.
func (m *VehicleMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *VehicleMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *VehicleMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Vehicle.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetAccountID sets the "account_id" field.
func (m *VehicleMutation) SetAccountID(s string) {
	m.account_id = &s
}

// AccountID returns the value of the "account_id" field in the mutation.
func (m *VehicleMutation) AccountID() (r string, exists bool) {
	v := m.account_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAccountID returns the old "account_id" field's value of the Vehicle entity.
// If the Vehicle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VehicleMutation) OldAccountID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccountID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccountID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccountID: %w", err)
	}
	return oldValue.AccountID, nil
}

// ResetAccountID resets all changes to the "account_id" field.
func (m *VehicleMutation) ResetAccountID() {
	m.account_id = nil
}

// SetVin sets the "vin" field.
func (m *VehicleMutation) SetVin(s string) {
	m.vin = &s
}

// Vin returns the value of the "vin" field in the mutation.
func (m *VehicleMutation) Vin() (r string, exists bool) {
	v := m.vin
	if v == nil {
		return
	}
	return *v, true
}

// OldVin returns the old "vin" field's value of the Vehicle entity.
// If the Vehicle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VehicleMutation) OldVin(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldVin is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldVin requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVin: %w", err)
	}
	return oldValue.Vin, nil
}

// ClearVin clears the value of the "vin" field.
func (m *VehicleMutation) ClearVin() {
	m.vin = nil
	m.clearedFields[vehicle.FieldVin] = struct{}{}
}

// VinCleared returns if the "vin" field was cleared in this mutation.
func (m *VehicleMutation) VinCleared() bool {
	_, ok := m.clearedFields[vehicle.FieldVin]
	return ok
}

// ResetVin resets all changes to the "vin" field.
func (m *VehicleMutation) ResetVin() {
	m.vin = nil
	delete(m.clearedFields, vehicle.FieldVin)
}

// SetFleetID sets the "fleet_id" field.
func (m *VehicleMutation) SetFleetID(s string) {
	m.fleet = &s
}

// FleetID returns the value of the "fleet_id" field in the mutation.
func (m *VehicleMutation) FleetID() (r string, exists bool) {
	v := m.fleet
	if v == nil {
		return
	}
	return *v, true
}

// OldFleetID returns the old "fleet_id" field's value of the Vehicle entity.
// If the Vehicle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VehicleMutation) OldFleetID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFleetID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFleetID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFleetID: %w", err)
	}
	return oldValue.FleetID, nil
}

// ClearFleetID clears the value of the "fleet_id" field.
func (m *VehicleMutation) ClearFleetID() {
	m.fleet = nil
	m.clearedFields[vehicle.FieldFleetID] = struct{}{}
}

// FleetIDCleared returns if the "fleet_id" field was cleared in this mutation.
func (m *VehicleMutation) FleetIDCleared() bool {
	_, ok := m.clearedFields[vehicle.FieldFleetID]
	return ok
}

// ResetFleetID resets all changes to the "fleet_id" field.
func (m *VehicleMutation) ResetFleetID() {
	m.fleet = nil
	delete(m.clearedFields, vehicle.FieldFleetID)
}

// ClearFleet clears the "fleet" edge to the Fleet entity.
func (m *VehicleMutation) ClearFleet() {
	m.clearedfleet = true
	m.clearedFields[vehicle.FieldFleetID] = struct{}{}
}

// FleetCleared reports if the "fleet" edge to the Fleet entity was cleared.
func (m *VehicleMutation) FleetCleared() bool {
	return m.FleetIDCleared() || m.clearedfleet
}

// FleetIDs returns the "fleet" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// FleetID instead. It exists only for internal usage by the builders.
func (m *VehicleMutation) FleetIDs() (ids []string) {
	if id := m.fleet; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetFleet resets all changes to the "fleet" edge.
func (m *VehicleMutation) ResetFleet() {
	m.fleet = nil
	m.clearedfleet = false
}

// Where appends a list predicates to the VehicleMutation builder.
func (m *VehicleMutation) Where(ps ...predicate.Vehicle) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the VehicleMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *VehicleMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Vehicle, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *VehicleMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *VehicleMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Vehicle).
func (m *VehicleMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *VehicleMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.account_id != nil {
		fields = append(fields, vehicle.FieldAccountID)
	}
	if m.vin != nil {
		fields = append(fields, vehicle.FieldVin)
	}
	if m.fleet != nil {
		fields = append(fields, vehicle.FieldFleetID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *VehicleMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case vehicle.FieldAccountID:
		return m.AccountID()
	case vehicle.FieldVin:
		return m.Vin()
	case vehicle.FieldFleetID:
		return m.FleetID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *VehicleMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case vehicle.FieldAccountID:
		return m.OldAccountID(ctx)
	case vehicle.FieldVin:
		return m.OldVin(ctx)
	case vehicle.FieldFleetID:
		return m.OldFleetID(ctx)
	}
	return nil, fmt.Errorf("unknown Vehicle field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *VehicleMutation) SetField(name string, value ent.Value) error {
	switch name {
	case vehicle.FieldAccountID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccountID(v)
		return nil
	case vehicle.FieldVin:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVin(v)
		return nil
	case vehicle.FieldFleetID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFleetID(v)
		return nil
	}
	return fmt.Errorf("unknown Vehicle field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *VehicleMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *VehicleMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *VehicleMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Vehicle numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *VehicleMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(vehicle.FieldVin) {
		fields = append(fields, vehicle.FieldVin)
	}
	if m.FieldCleared(vehicle.FieldFleetID) {
		fields = append(fields, vehicle.FieldFleetID)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *VehicleMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *VehicleMutation) ClearField(name string) error {
	switch name {
	case vehicle.FieldVin:
		m.ClearVin()
		return nil
	case vehicle.FieldFleetID:
		m.ClearFleetID()
		return nil
	}
	return fmt.Errorf("unknown Vehicle nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *VehicleMutation) ResetField(name string) error {
	switch name {
	case vehicle.FieldAccountID:
		m.ResetAccountID()
		return nil
	case vehicle.FieldVin:
		m.ResetVin()
		return nil
	case vehicle.FieldFleetID:
		m.ResetFleetID()
		return nil
	}
	return fmt.Errorf("unknown Vehicle field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *VehicleMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.fleet != nil {
		edges = append(edges, vehicle.EdgeFleet)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *VehicleMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case vehicle.EdgeFleet:
		if id := m.fleet; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *VehicleMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *VehicleMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *VehicleMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedfleet {
		edges = append(edges, vehicle.EdgeFleet)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *VehicleMutation) EdgeCleared(name string) bool {
	switch name {
	case vehicle.EdgeFleet:
		return m.clearedfleet
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *VehicleMutation) ClearEdge(name string) error {
	switch name {
	case vehicle.EdgeFleet:
		m.ClearFleet()
		return nil
	}
	return fmt.Errorf("unknown Vehicle unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *VehicleMutation) ResetEdge(name string) error {
	switch name {
	case vehicle.EdgeFleet:
		m.ResetFleet()
		return nil
	}
	return fmt.Errorf("unknown Vehicle edge %s", name)
}
