// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/infobloxopen/devedge-sdk/testdata/fleet/ent/fleet"
	"github.com/infobloxopen/devedge-sdk/testdata/fleet/ent/predicate"
	"github.com/infobloxopen/devedge-sdk/testdata/fleet/ent/vehicle"
)

// VehicleUpdate is the builder for updating Vehicle entities.
type VehicleUpdate struct {
	config
	hooks    []Hook
	mutation *VehicleMutation
}

// Where appends a list predicates to the VehicleUpdate builder.
func (_u *VehicleUpdate) Where(ps ...predicate.Vehicle) *VehicleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVin sets the "vin" field.
func (_u *VehicleUpdate) SetVin(v string) *VehicleUpdate {
	_u.mutation.SetVin(v)
	return _u
}

// SetNillableVin sets the "vin" field if the given value is not nil.
func (_u *VehicleUpdate) SetNillableVin(v *string) *VehicleUpdate {
	if v != nil {
		_u.SetVin(*v)
	}
	return _u
}

// ClearVin clears the value of the "vin" field.
func (_u *VehicleUpdate) ClearVin() *VehicleUpdate {
	_u.mutation.ClearVin()
	return _u
}

// SetFleetID sets the "fleet_id" field.
func (_u *VehicleUpdate) SetFleetID(v string) *VehicleUpdate {
	_u.mutation.SetFleetID(v)
	return _u
}

// SetNillableFleetID sets the "fleet_id" field if the given value is not nil.
func (_u *VehicleUpdate) SetNillableFleetID(v *string) *VehicleUpdate {
	if v != nil {
		_u.SetFleetID(*v)
	}
	return _u
}

// ClearFleetID clears the value of the "fleet_id" field.
func (_u *VehicleUpdate) ClearFleetID() *VehicleUpdate {
	_u.mutation.ClearFleetID()
	return _u
}

// SetFleet sets the "fleet" edge to the Fleet entity.
func (_u *VehicleUpdate) SetFleet(v *Fleet) *VehicleUpdate {
	return _u.SetFleetID(v.ID)
}

// Mutation returns the VehicleMutation object of the builder.
func (_u *VehicleUpdate) Mutation() *VehicleMutation {
	return _u.mutation
}

// ClearFleet clears the "fleet" edge to the Fleet entity.
func (_u *VehicleUpdate) ClearFleet() *VehicleUpdate {
	_u.mutation.ClearFleet()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VehicleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VehicleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VehicleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VehicleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *VehicleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(vehicle.Table, vehicle.Columns, sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Vin(); ok {
		_spec.SetField(vehicle.FieldVin, field.TypeString, value)
	}
	if _u.mutation.VinCleared() {
		_spec.ClearField(vehicle.FieldVin, field.TypeString)
	}
	if _u.mutation.FleetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vehicle.FleetTable,
			Columns: []string{vehicle.FleetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fleet.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FleetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vehicle.FleetTable,
			Columns: []string{vehicle.FleetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fleet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vehicle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VehicleUpdateOne is the builder for updating a single Vehicle entity.
type VehicleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VehicleMutation
}

// SetVin sets the "vin" field.
func (_u *VehicleUpdateOne) SetVin(v string) *VehicleUpdateOne {
	_u.mutation.SetVin(v)
	return _u
}

// SetNillableVin sets the "vin" field if the given value is not nil.
func (_u *VehicleUpdateOne) SetNillableVin(v *string) *VehicleUpdateOne {
	if v != nil {
		_u.SetVin(*v)
	}
	return _u
}

// ClearVin clears the value of the "vin" field.
func (_u *VehicleUpdateOne) ClearVin() *VehicleUpdateOne {
	_u.mutation.ClearVin()
	return _u
}

// SetFleetID sets the "fleet_id" field.
func (_u *VehicleUpdateOne) SetFleetID(v string) *VehicleUpdateOne {
	_u.mutation.SetFleetID(v)
	return _u
}

// SetNillableFleetID sets the "fleet_id" field if the given value is not nil.
func (_u *VehicleUpdateOne) SetNillableFleetID(v *string) *VehicleUpdateOne {
	if v != nil {
		_u.SetFleetID(*v)
	}
	return _u
}

// ClearFleetID clears the value of the "fleet_id" field.
func (_u *VehicleUpdateOne) ClearFleetID() *VehicleUpdateOne {
	_u.mutation.ClearFleetID()
	return _u
}

// SetFleet sets the "fleet" edge to the Fleet entity.
func (_u *VehicleUpdateOne) SetFleet(v *Fleet) *VehicleUpdateOne {
	return _u.SetFleetID(v.ID)
}

// Mutation returns the VehicleMutation object of the builder.
func (_u *VehicleUpdateOne) Mutation() *VehicleMutation {
	return _u.mutation
}

// ClearFleet clears the "fleet" edge to the Fleet entity.
func (_u *VehicleUpdateOne) ClearFleet() *VehicleUpdateOne {
	_u.mutation.ClearFleet()
	return _u
}

// Where appends a list predicates to the VehicleUpdate builder.
func (_u *VehicleUpdateOne) Where(ps ...predicate.Vehicle) *VehicleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VehicleUpdateOne) Select(field string, fields ...string) *VehicleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Vehicle entity.
func (_u *VehicleUpdateOne) Save(ctx context.Context) (*Vehicle, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VehicleUpdateOne) SaveX(ctx context.Context) *Vehicle {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VehicleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VehicleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *VehicleUpdateOne) sqlSave(ctx context.Context) (_node *Vehicle, err error) {
	_spec := sqlgraph.NewUpdateSpec(vehicle.Table, vehicle.Columns, sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Vehicle.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vehicle.FieldID)
		for _, f := range fields {
			if !vehicle.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != vehicle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Vin(); ok {
		_spec.SetField(vehicle.FieldVin, field.TypeString, value)
	}
	if _u.mutation.VinCleared() {
		_spec.ClearField(vehicle.FieldVin, field.TypeString)
	}
	if _u.mutation.FleetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vehicle.FleetTable,
			Columns: []string{vehicle.FleetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fleet.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FleetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vehicle.FleetTable,
			Columns: []string{vehicle.FleetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fleet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Vehicle{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vehicle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
