// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"github.com/infobloxopen/devedge-sdk/testdata/apikey/ent/apikey"
	"github.com/infobloxopen/devedge-sdk/testdata/apikey/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apikeyMixin := schema.APIKey{}.Mixin()
	apikeyMixinInters0 := apikeyMixin[0].Interceptors()
	apikey.Interceptors[0] = apikeyMixinInters0[0]
	apikeyMixinFields0 := apikeyMixin[0].Fields()
	_ = apikeyMixinFields0
	apikeyFields := schema.APIKey{}.Fields()
	_ = apikeyFields
	// apikeyDescAccountID is the schema descriptor for account_id field.
	apikeyDescAccountID := apikeyMixinFields0[0].Descriptor()
	// apikey.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	apikey.AccountIDValidator = apikeyDescAccountID.Validators[0].(func(string) error)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
