-- Code generated by devedge-sdk full-text search (WS-041). DO NOT EDIT.
-- INDEXED strategy: a persisted tsvector generated column for the "gizmos" table.
ALTER TABLE gizmos
    ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (to_tsvector('simple', replace(replace(coalesce(CAST("label" AS text), ''), '@', ' '), '.', ' ') || ' ' || (CASE category WHEN 'premium' THEN 'tier premium deluxe' WHEN 'standard' THEN 'tier standard basic' ELSE 'tier none' END))) STORED;

