-- Code generated by devedge-sdk full-text search (WS-041). DO NOT EDIT.
-- CREATE INDEX CONCURRENTLY must be the SOLE statement in its migration file:
-- Postgres forbids it inside a transaction block and the engine sends a
-- multi-statement file as one implicit transaction (FM-6).
CREATE INDEX CONCURRENTLY gizmos_search_gin ON gizmos USING GIN (search_vector);

