// Code generated by protoc-gen-ent. DO NOT EDIT.
package ent

import entasset "github.com/infobloxopen/devedge-sdk/testdata/federation/ent/asset"

// WhereAccountID scopes the query to rows belonging to the given tenant. It
// satisfies entrepo.TenantFilterer, which the TenantMixin interceptor calls to
// automatically scope Get/List queries to the calling tenant.
func (q *AssetQuery) WhereAccountID(id string) {
	q.Where(entasset.AccountID(id))
}
