// Code generated by protoc-gen-ent. DO NOT EDIT.
package ent

import entregion "github.com/infobloxopen/devedge-sdk/testdata/federation/ent/region"

// WhereAccountID scopes the query to rows belonging to the given tenant. It
// satisfies entrepo.TenantFilterer, which the TenantMixin interceptor calls to
// automatically scope Get/List queries to the calling tenant.
func (q *RegionQuery) WhereAccountID(id string) {
	q.Where(entregion.AccountID(id))
}
