// Code generated by protoc-gen-ent. DO NOT EDIT.
package federationv1

import (
	"context"
	"fmt"

	"github.com/infobloxopen/devedge-sdk/middleware"
	"github.com/infobloxopen/devedge-sdk/persistence"
	ent "github.com/infobloxopen/devedge-sdk/testdata/federation/ent"
	entasset "github.com/infobloxopen/devedge-sdk/testdata/federation/ent/asset"
)

// AssetEntRepository adds atomic AIP-137 batch methods to the ent-backed Asset,
// making it a persistence.BatchRepository. Standard methods come from the
// embedded hand-written adapter.
type AssetEntRepository struct {
	persistence.Repository[*Asset, string]
	client *ent.Client
}

// NewAssetEntBatchRepository wraps the hand-written ent adapter with batch support.
func NewAssetEntBatchRepository(client *ent.Client) *AssetEntRepository {
	return &AssetEntRepository{Repository: NewAssetEntRepository(client), client: client}
}

func assetInMask(mask []string, field string) bool {
	if len(mask) == 0 {
		return true
	}
	for _, m := range mask {
		if m == field {
			return true
		}
	}
	return false
}

func (r *AssetEntRepository) batchModelClient(ctx context.Context) *ent.AssetClient {
	if h, ok := persistence.TxFromContext(ctx); ok {
		if tx, ok := h.(*ent.Tx); ok {
			return tx.Asset
		}
	}
	return r.client.Asset
}

func (r *AssetEntRepository) batchTx(ctx context.Context) (*ent.Tx, bool, error) {
	if h, ok := persistence.TxFromContext(ctx); ok {
		if tx, ok := h.(*ent.Tx); ok {
			return tx, false, nil
		}
	}
	tx, err := r.client.Tx(ctx)
	return tx, true, err
}

func (r *AssetEntRepository) BatchGet(ctx context.Context, keys []string) ([]*Asset, error) {
	if len(keys) == 0 {
		return []*Asset{}, nil
	}
	rows, err := r.batchModelClient(ctx).Query().Where(entasset.IDIn(keys...)).All(ctx)
	if err != nil {
		return nil, fmt.Errorf("batch get asset: %w", err)
	}
	byID := make(map[string]*Asset, len(rows))
	for _, e := range rows {
		byID[e.ID] = fromEntAsset(e)
	}
	out := make([]*Asset, 0, len(keys))
	for _, k := range keys {
		p, ok := byID[k]
		if !ok {
			return nil, persistence.ErrNotFound
		}
		out = append(out, p)
	}
	return out, nil
}

func (r *AssetEntRepository) BatchUpdate(ctx context.Context, items []persistence.BatchUpdateItem[*Asset, string]) ([]*Asset, error) {
	if len(items) == 0 {
		return []*Asset{}, nil
	}
	tenantID := middleware.TenantIDFromContext(ctx)
	tx, ownTx, err := r.batchTx(ctx)
	if err != nil {
		return nil, fmt.Errorf("begin tx: %w", err)
	}
	rollback := func() {
		if ownTx {
			_ = tx.Rollback()
		}
	}
	out := make([]*Asset, 0, len(items))
	for _, it := range items {
		u := tx.Asset.UpdateOneID(it.Key)
		if tenantID != "" {
			u = u.Where(entasset.AccountID(tenantID))
		}
		if assetInMask(it.FieldMask, "display_name") {
			u = u.SetDisplayName(it.Entity.GetDisplayName())
		}
		if assetInMask(it.FieldMask, "region_id") {
			u = u.SetRegionID(it.Entity.GetRegionId())
		}
		saved, serr := u.Save(ctx)
		if serr != nil {
			rollback()
			if ent.IsNotFound(serr) {
				return nil, persistence.ErrNotFound
			}
			return nil, fmt.Errorf("batch update asset: %w", serr)
		}
		out = append(out, fromEntAsset(saved))
	}
	if ownTx {
		if err := tx.Commit(); err != nil {
			return nil, fmt.Errorf("commit tx: %w", err)
		}
	}
	return out, nil
}

func (r *AssetEntRepository) BatchDelete(ctx context.Context, keys []string) error {
	if len(keys) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(keys))
	uniq := make([]string, 0, len(keys))
	for _, k := range keys {
		if _, ok := seen[k]; ok {
			continue
		}
		seen[k] = struct{}{}
		uniq = append(uniq, k)
	}
	tenantID := middleware.TenantIDFromContext(ctx)
	tx, ownTx, err := r.batchTx(ctx)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	rollback := func() {
		if ownTx {
			_ = tx.Rollback()
		}
	}
	del := tx.Asset.Delete().Where(entasset.IDIn(uniq...))
	if tenantID != "" {
		del = del.Where(entasset.AccountID(tenantID))
	}
	n, derr := del.Exec(ctx)
	if derr != nil {
		rollback()
		return fmt.Errorf("batch delete asset: %w", derr)
	}
	if n != len(uniq) {
		rollback()
		return persistence.ErrNotFound
	}
	if ownTx {
		return tx.Commit()
	}
	return nil
}

// compile-time check.
var _ persistence.BatchRepository[*Asset, string] = (*AssetEntRepository)(nil)
