// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: federation.proto

// Two-service cross-service-reference fixture (F041, WS-021 P1 AC-5).
//
// AssetService (SOURCE) owns Asset, whose scalar region_id field carries a
// google.api.resource_reference (AIP-124) at "region.example.com/Region" — the
// resource type RegionService (TARGET) serves. region_id stays a plain scalar
// string: the reference is METADATA only, so protoc-gen-ent emits NO edge from
// Asset to Region and there is no cascade (AC-4). RegionService serves an
// AIP-137 BatchGetRegions, so a composition layer resolves N Asset references in
// exactly ONE BatchGet (the anti-N+1 guarantee, AC-5) via reference.Load. Both
// backends (ent and GORM) are generated so the guarantee is proven on each.

package federationv1

import (
	_ "github.com/infobloxopen/apis/proto/infoblox/authz/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Region is the reference TARGET: RegionService serves BatchGetRegions over it,
// so any resource that references "region.example.com/Region" is batch-fetchable.
type Region struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId   string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DisplayName string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// AIP-154 ETag: framework-managed opaque token stamped on every write.
	Etag          string `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{0}
}

func (x *Region) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Region) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Region) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Region) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

// Asset is the reference SOURCE: its region_id names a Region served by another
// microservice. region_id is a plain scalar FK annotated with the standard
// google.api.resource_reference (AIP-124) — there is no belongs_to/has_one edge,
// so the field stays metadata-only (no ent/GORM edge, no cascade).
type Asset struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId   string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DisplayName string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Cross-service reference: names a Region served by RegionService. A scalar
	// foreign key (NOT a message/edge) so it is resolved above the services, never
	// traversed in-process.
	RegionId string `protobuf:"bytes,4,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	// AIP-154 ETag: framework-managed opaque token stamped on every write.
	Etag          string `protobuf:"bytes,5,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{1}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Asset) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Asset) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *Asset) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type CreateRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        *Region                `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRegionRequest) Reset() {
	*x = CreateRegionRequest{}
	mi := &file_federation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegionRequest) ProtoMessage() {}

func (x *CreateRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegionRequest.ProtoReflect.Descriptor instead.
func (*CreateRegionRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRegionRequest) GetRegion() *Region {
	if x != nil {
		return x.Region
	}
	return nil
}

type GetRegionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// AIP-157: fields to return; empty means all fields.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionRequest) Reset() {
	*x = GetRegionRequest{}
	mi := &file_federation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionRequest) ProtoMessage() {}

func (x *GetRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionRequest.ProtoReflect.Descriptor instead.
func (*GetRegionRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{3}
}

func (x *GetRegionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRegionRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type ListRegionsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PageSize  int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// AIP-157: fields to return; empty means all fields.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegionsRequest) Reset() {
	*x = ListRegionsRequest{}
	mi := &file_federation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegionsRequest) ProtoMessage() {}

func (x *ListRegionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegionsRequest.ProtoReflect.Descriptor instead.
func (*ListRegionsRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{4}
}

func (x *ListRegionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRegionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRegionsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type ListRegionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regions       []*Region              `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegionsResponse) Reset() {
	*x = ListRegionsResponse{}
	mi := &file_federation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegionsResponse) ProtoMessage() {}

func (x *ListRegionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegionsResponse.ProtoReflect.Descriptor instead.
func (*ListRegionsResponse) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{5}
}

func (x *ListRegionsResponse) GetRegions() []*Region {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *ListRegionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BatchGetRegionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetRegionsRequest) Reset() {
	*x = BatchGetRegionsRequest{}
	mi := &file_federation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRegionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRegionsRequest) ProtoMessage() {}

func (x *BatchGetRegionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRegionsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetRegionsRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetRegionsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type BatchGetRegionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regions       []*Region              `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetRegionsResponse) Reset() {
	*x = BatchGetRegionsResponse{}
	mi := &file_federation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRegionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRegionsResponse) ProtoMessage() {}

func (x *BatchGetRegionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRegionsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetRegionsResponse) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetRegionsResponse) GetRegions() []*Region {
	if x != nil {
		return x.Regions
	}
	return nil
}

type CreateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssetRequest) Reset() {
	*x = CreateAssetRequest{}
	mi := &file_federation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetRequest) ProtoMessage() {}

func (x *CreateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetRequest.ProtoReflect.Descriptor instead.
func (*CreateAssetRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAssetRequest) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type GetAssetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// AIP-157: fields to return; empty means all fields.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	mi := &file_federation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{9}
}

func (x *GetAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAssetRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type ListAssetsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PageSize  int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// AIP-157: fields to return; empty means all fields.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsRequest) Reset() {
	*x = ListAssetsRequest{}
	mi := &file_federation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsRequest) ProtoMessage() {}

func (x *ListAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsRequest.ProtoReflect.Descriptor instead.
func (*ListAssetsRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{10}
}

func (x *ListAssetsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAssetsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAssetsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type ListAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsResponse) Reset() {
	*x = ListAssetsResponse{}
	mi := &file_federation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsResponse) ProtoMessage() {}

func (x *ListAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsResponse.ProtoReflect.Descriptor instead.
func (*ListAssetsResponse) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{11}
}

func (x *ListAssetsResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *ListAssetsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_federation_proto protoreflect.FileDescriptor

const file_federation_proto_rawDesc = "" +
	"\n" +
	"\x10federation.proto\x12\rfederation.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\x1a\x1dinfoblox/authz/v1/authz.proto\"\xa5\x01\n" +
	"\x06Region\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x17\n" +
	"\x04etag\x18\x04 \x01(\tB\x03\xe0A\x03R\x04etag:0\xeaA-\n" +
	"\x19region.example.com/Region\x12\x10regions/{region}\"\xdd\x01\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12;\n" +
	"\tregion_id\x18\x04 \x01(\tB\x1e\xfaA\x1b\n" +
	"\x19region.example.com/RegionR\bregionId\x12\x17\n" +
	"\x04etag\x18\x05 \x01(\tB\x03\xe0A\x03R\x04etag:,\xeaA)\n" +
	"\x17asset.example.com/Asset\x12\x0eassets/{asset}\"D\n" +
	"\x13CreateRegionRequest\x12-\n" +
	"\x06region\x18\x01 \x01(\v2\x15.federation.v1.RegionR\x06region\"[\n" +
	"\x10GetRegionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\x89\x01\n" +
	"\x12ListRegionsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x127\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"n\n" +
	"\x13ListRegionsResponse\x12/\n" +
	"\aregions\x18\x01 \x03(\v2\x15.federation.v1.RegionR\aregions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"*\n" +
	"\x16BatchGetRegionsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"J\n" +
	"\x17BatchGetRegionsResponse\x12/\n" +
	"\aregions\x18\x01 \x03(\v2\x15.federation.v1.RegionR\aregions\"@\n" +
	"\x12CreateAssetRequest\x12*\n" +
	"\x05asset\x18\x01 \x01(\v2\x14.federation.v1.AssetR\x05asset\"Z\n" +
	"\x0fGetAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\x88\x01\n" +
	"\x11ListAssetsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x127\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"j\n" +
	"\x12ListAssetsResponse\x12,\n" +
	"\x06assets\x18\x01 \x03(\v2\x14.federation.v1.AssetR\x06assets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\x90\x04\n" +
	"\rRegionService\x12{\n" +
	"\fCreateRegion\x12\".federation.v1.CreateRegionRequest\x1a\x15.federation.v1.Region\"0\x8a\xb5\x18\x11\n" +
	"\x06create\x12\aregions\x82\xd3\xe4\x93\x02\x15:\x06region\"\v/v1/regions\x12p\n" +
	"\tGetRegion\x12\x1f.federation.v1.GetRegionRequest\x1a\x15.federation.v1.Region\"+\x8a\xb5\x18\x0f\n" +
	"\x04read\x12\aregions\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/regions/{id}\x12|\n" +
	"\vListRegions\x12!.federation.v1.ListRegionsRequest\x1a\".federation.v1.ListRegionsResponse\"&\x8a\xb5\x18\x0f\n" +
	"\x04read\x12\aregions\x82\xd3\xe4\x93\x02\r\x12\v/v1/regions\x12\x91\x01\n" +
	"\x0fBatchGetRegions\x12%.federation.v1.BatchGetRegionsRequest\x1a&.federation.v1.BatchGetRegionsResponse\"/\x8a\xb5\x18\x0f\n" +
	"\x04read\x12\aregions\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/regions:batchGet2\xeb\x02\n" +
	"\fAssetService\x12u\n" +
	"\vCreateAsset\x12!.federation.v1.CreateAssetRequest\x1a\x14.federation.v1.Asset\"-\x8a\xb5\x18\x10\n" +
	"\x06create\x12\x06assets\x82\xd3\xe4\x93\x02\x13:\x05asset\"\n" +
	"/v1/assets\x12k\n" +
	"\bGetAsset\x12\x1e.federation.v1.GetAssetRequest\x1a\x14.federation.v1.Asset\")\x8a\xb5\x18\x0e\n" +
	"\x04read\x12\x06assets\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/assets/{id}\x12w\n" +
	"\n" +
	"ListAssets\x12 .federation.v1.ListAssetsRequest\x1a!.federation.v1.ListAssetsResponse\"$\x8a\xb5\x18\x0e\n" +
	"\x04read\x12\x06assets\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/assetsBSZQgithub.com/infobloxopen/devedge-sdk/testdata/federation/federationv1;federationv1b\x06proto3"

var (
	file_federation_proto_rawDescOnce sync.Once
	file_federation_proto_rawDescData []byte
)

func file_federation_proto_rawDescGZIP() []byte {
	file_federation_proto_rawDescOnce.Do(func() {
		file_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_federation_proto_rawDesc), len(file_federation_proto_rawDesc)))
	})
	return file_federation_proto_rawDescData
}

var file_federation_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_federation_proto_goTypes = []any{
	(*Region)(nil),                  // 0: federation.v1.Region
	(*Asset)(nil),                   // 1: federation.v1.Asset
	(*CreateRegionRequest)(nil),     // 2: federation.v1.CreateRegionRequest
	(*GetRegionRequest)(nil),        // 3: federation.v1.GetRegionRequest
	(*ListRegionsRequest)(nil),      // 4: federation.v1.ListRegionsRequest
	(*ListRegionsResponse)(nil),     // 5: federation.v1.ListRegionsResponse
	(*BatchGetRegionsRequest)(nil),  // 6: federation.v1.BatchGetRegionsRequest
	(*BatchGetRegionsResponse)(nil), // 7: federation.v1.BatchGetRegionsResponse
	(*CreateAssetRequest)(nil),      // 8: federation.v1.CreateAssetRequest
	(*GetAssetRequest)(nil),         // 9: federation.v1.GetAssetRequest
	(*ListAssetsRequest)(nil),       // 10: federation.v1.ListAssetsRequest
	(*ListAssetsResponse)(nil),      // 11: federation.v1.ListAssetsResponse
	(*fieldmaskpb.FieldMask)(nil),   // 12: google.protobuf.FieldMask
}
var file_federation_proto_depIdxs = []int32{
	0,  // 0: federation.v1.CreateRegionRequest.region:type_name -> federation.v1.Region
	12, // 1: federation.v1.GetRegionRequest.read_mask:type_name -> google.protobuf.FieldMask
	12, // 2: federation.v1.ListRegionsRequest.read_mask:type_name -> google.protobuf.FieldMask
	0,  // 3: federation.v1.ListRegionsResponse.regions:type_name -> federation.v1.Region
	0,  // 4: federation.v1.BatchGetRegionsResponse.regions:type_name -> federation.v1.Region
	1,  // 5: federation.v1.CreateAssetRequest.asset:type_name -> federation.v1.Asset
	12, // 6: federation.v1.GetAssetRequest.read_mask:type_name -> google.protobuf.FieldMask
	12, // 7: federation.v1.ListAssetsRequest.read_mask:type_name -> google.protobuf.FieldMask
	1,  // 8: federation.v1.ListAssetsResponse.assets:type_name -> federation.v1.Asset
	2,  // 9: federation.v1.RegionService.CreateRegion:input_type -> federation.v1.CreateRegionRequest
	3,  // 10: federation.v1.RegionService.GetRegion:input_type -> federation.v1.GetRegionRequest
	4,  // 11: federation.v1.RegionService.ListRegions:input_type -> federation.v1.ListRegionsRequest
	6,  // 12: federation.v1.RegionService.BatchGetRegions:input_type -> federation.v1.BatchGetRegionsRequest
	8,  // 13: federation.v1.AssetService.CreateAsset:input_type -> federation.v1.CreateAssetRequest
	9,  // 14: federation.v1.AssetService.GetAsset:input_type -> federation.v1.GetAssetRequest
	10, // 15: federation.v1.AssetService.ListAssets:input_type -> federation.v1.ListAssetsRequest
	0,  // 16: federation.v1.RegionService.CreateRegion:output_type -> federation.v1.Region
	0,  // 17: federation.v1.RegionService.GetRegion:output_type -> federation.v1.Region
	5,  // 18: federation.v1.RegionService.ListRegions:output_type -> federation.v1.ListRegionsResponse
	7,  // 19: federation.v1.RegionService.BatchGetRegions:output_type -> federation.v1.BatchGetRegionsResponse
	1,  // 20: federation.v1.AssetService.CreateAsset:output_type -> federation.v1.Asset
	1,  // 21: federation.v1.AssetService.GetAsset:output_type -> federation.v1.Asset
	11, // 22: federation.v1.AssetService.ListAssets:output_type -> federation.v1.ListAssetsResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_federation_proto_init() }
func file_federation_proto_init() {
	if File_federation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_federation_proto_rawDesc), len(file_federation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_federation_proto_goTypes,
		DependencyIndexes: file_federation_proto_depIdxs,
		MessageInfos:      file_federation_proto_msgTypes,
	}.Build()
	File_federation_proto = out.File
	file_federation_proto_goTypes = nil
	file_federation_proto_depIdxs = nil
}
