// Code generated by protoc-gen-storage. DO NOT EDIT.
// source: (proto input)

package federationv1

import (
	"context"
	"encoding/base64"
	"fmt"
	"strconv"
	"time"

	"gorm.io/gorm"

	"github.com/infobloxopen/devedge-sdk/middleware"
	"github.com/infobloxopen/devedge-sdk/middleware/etag"
	"github.com/infobloxopen/devedge-sdk/persistence"
	"github.com/infobloxopen/devedge-sdk/persistence/filter"
	"github.com/infobloxopen/devedge-sdk/persistence/resourcename"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

var (
	_ = base64.StdEncoding
	_ = fmt.Sprintf
	_ = strconv.Itoa
	_ = filter.Parse
	_ = codes.OK
	_ = status.Error
	_ = resourcename.IDVarName
)

// RegionModel is the GORM model for Region.
type RegionModel struct {
	ID          string `gorm:"primaryKey;type:varchar(36)"`
	AccountId   string `gorm:"column:account_id"`
	DisplayName string `gorm:"column:display_name"`
	ETag        string `gorm:"column:etag"`
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func toModel_Region(p *Region) *RegionModel {
	if p == nil {
		return nil
	}
	m := &RegionModel{ID: p.Id}
	m.AccountId = p.AccountId
	m.DisplayName = p.DisplayName
	return m
}

func fromModel_Region(m *RegionModel) *Region {
	if m == nil {
		return nil
	}
	p := &Region{Id: m.ID}
	p.AccountId = m.AccountId
	p.DisplayName = m.DisplayName
	p.Etag = m.ETag
	if FromModelRegionCustom != nil {
		FromModelRegionCustom(m, p)
	}
	return p
}

// FromModelRegionCustom, if set, runs at the end of fromModel_Region to populate
// fields the generator cannot derive (computed/derived values). Register it
// from your own (regen-safe) file — e.g. in an init(); never assigned here.
var FromModelRegionCustom func(m *RegionModel, p *Region)

// ToModelRegionOnCreate, if set, runs in Create just before the database write,
// to set columns the generator does not (e.g. a custom-encoded field).
var ToModelRegionOnCreate func(p *Region, m *RegionModel)

// ToModelRegionOnUpdate, if set, runs in Update just before the database write.
var ToModelRegionOnUpdate func(p *Region, m *RegionModel)

// RegionColumns maps proto field names to DB column names for safe filter/order_by parsing.
var RegionColumns = map[string]string{
	"id":           "id",
	"account_id":   "account_id",
	"display_name": "display_name",
}

// RegionNamePattern is the AIP-122 resource name pattern for Region.
const RegionNamePattern = "regions/{region}"

// FormatRegionName builds the resource name for the given ID.
func FormatRegionName(id string) string {
	name, _ := resourcename.Format(RegionNamePattern, map[string]string{"region": id})
	return name
}

// ParseRegionName extracts the resource ID from the given name.
func ParseRegionName(name string) (string, error) {
	return resourcename.IDFromName(RegionNamePattern, name)
}

// RegionRepository is a GORM-backed persistence.Repository for *Region.
type RegionRepository struct {
	db    *gorm.DB
	idGen persistence.IDGenerator
}

// NewRegionRepository creates a repository backed by db.
func NewRegionRepository(db *gorm.DB, opts ...persistence.RepoOption) *RegionRepository {
	cfg := persistence.NewRepoConfig(persistence.UUID7Generator(), opts...)
	return &RegionRepository{db: db, idGen: cfg.IDGenerator}
}

func (r *RegionRepository) conn(ctx context.Context) *gorm.DB {
	if h, ok := persistence.TxFromContext(ctx); ok {
		if tx, ok := h.(*gorm.DB); ok {
			return tx.WithContext(ctx)
		}
	}
	return r.db.WithContext(ctx)
}

func (r *RegionRepository) Get(ctx context.Context, key string) (*Region, error) {
	var m RegionModel
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) && tenantID == "" {
		return nil, status.Error(codes.PermissionDenied, "Region: no tenant on a tenant-scoped get")
	}
	q := r.conn(ctx).Where("id = ?", key)
	if !middleware.IsSystemContext(ctx) {
		q = q.Where("account_id = ?", tenantID)
	}
	if err := q.First(&m).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, persistence.ErrNotFound
		}
		return nil, fmt.Errorf("get Region: %w", err)
	}
	return fromModel_Region(&m), nil
}

func (r *RegionRepository) List(ctx context.Context, opts persistence.ListOptions) ([]*Region, string, error) {
	var models []RegionModel
	q := r.conn(ctx)
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) && tenantID == "" {
		return nil, "", status.Error(codes.PermissionDenied, "Region: no tenant on a tenant-scoped list")
	}
	if !middleware.IsSystemContext(ctx) {
		q = q.Where("account_id = ?", tenantID)
	}
	if opts.Filter != "" {
		cond, err := filter.Parse(opts.Filter, RegionColumns)
		if err != nil {
			return nil, "", status.Errorf(codes.InvalidArgument, "invalid filter: %v", err)
		}
		sql, args := cond.SQL()
		q = q.Where(sql, args...)
	}
	if opts.OrderBy != "" {
		clauses, err := filter.ParseOrderBy(opts.OrderBy, RegionColumns)
		if err != nil {
			return nil, "", status.Errorf(codes.InvalidArgument, "invalid order_by: %v", err)
		}
		for _, c := range clauses {
			q = q.Order(c.GORMExpr())
		}
	}
	pageSize := opts.PageSize
	if pageSize <= 0 {
		pageSize = 50
	}
	if pageSize > persistence.MaxPageSize {
		pageSize = persistence.MaxPageSize
	}
	offset := 0
	if opts.PageToken != "" {
		if dec, err := base64.StdEncoding.DecodeString(opts.PageToken); err == nil {
			offset, _ = strconv.Atoi(string(dec))
		}
	}
	if err := q.Limit(pageSize).Offset(offset).Find(&models).Error; err != nil {
		return nil, "", fmt.Errorf("list Region: %w", err)
	}
	out := make([]*Region, len(models))
	for i := range models {
		out[i] = fromModel_Region(&models[i])
	}
	nextToken := ""
	if len(models) == pageSize {
		nextToken = base64.StdEncoding.EncodeToString([]byte(strconv.Itoa(offset + pageSize)))
	}
	return out, nextToken, nil
}

func (r *RegionRepository) Create(ctx context.Context, entity *Region) (*Region, error) {
	if entity.GetId() == "" {
		entity.Id = r.idGen.NewID()
	}
	m := toModel_Region(entity)
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) && tenantID == "" {
		return nil, status.Error(codes.PermissionDenied, "Region: no tenant on a tenant-scoped create")
	}
	if !middleware.IsSystemContext(ctx) {
		m.AccountId = tenantID
	}
	m.ETag = etag.New() // AIP-154: fresh ETag on create
	if ToModelRegionOnCreate != nil {
		ToModelRegionOnCreate(entity, m)
	}
	if err := r.conn(ctx).Create(m).Error; err != nil {
		// Map driver constraint violations to clean sentinels so callers see
		// AlreadyExists/FailedPrecondition (not 500), and no SQL leaks to the client.
		if ce := persistence.ConstraintError(err); ce != nil {
			return nil, ce
		}
		return nil, fmt.Errorf("create Region: %w", err)
	}
	return fromModel_Region(m), nil
}

func (r *RegionRepository) Update(ctx context.Context, key string, entity *Region, fieldMask ...string) (*Region, error) {
	m := toModel_Region(entity)
	m.ID = key
	m.ETag = etag.New() // AIP-154: bump the ETag on every update
	if ToModelRegionOnUpdate != nil {
		ToModelRegionOnUpdate(entity, m)
	}
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) && tenantID == "" {
		return nil, status.Error(codes.PermissionDenied, "Region: no tenant on a tenant-scoped update")
	}
	q := r.conn(ctx).Model(m).Where("id = ?", key)
	if !middleware.IsSystemContext(ctx) {
		q = q.Where("account_id = ?", tenantID)
	}
	ifMatch := etag.IfMatchFromContext(ctx)
	if ifMatch != "" {
		q = q.Where("etag = ?", ifMatch)
	}
	if len(fieldMask) > 0 {
		dbCols := make([]string, 0, len(fieldMask))
		for _, f := range fieldMask {
			col, ok := RegionColumns[f]
			if !ok {
				return nil, status.Errorf(codes.InvalidArgument, "unknown field in update_mask: %q", f)
			}
			if col == "account_id" {
				return nil, status.Errorf(codes.InvalidArgument, "account_id is the tenant key and cannot be updated")
			}
			dbCols = append(dbCols, col)
		}
		dbCols = append(dbCols, "etag") // a masked update still changes the resource
		// Select makes GORM write the named columns even when their value is
		// the zero value (false, 0, ""); a bare struct Updates would skip them.
		res := q.Select(dbCols).Updates(m)
		if err := res.Error; err != nil {
			if ce := persistence.ConstraintError(err); ce != nil {
				return nil, ce
			}
			return nil, fmt.Errorf("update Region: %w", err)
		}
		if ifMatch != "" && res.RowsAffected == 0 {
			check := r.conn(ctx).Model(&RegionModel{}).Where("id = ?", key)
			if !middleware.IsSystemContext(ctx) {
				check = check.Where("account_id = ?", tenantID)
			}
			var n int64
			if err := check.Count(&n).Error; err != nil {
				return nil, fmt.Errorf("update Region precondition: %w", err)
			}
			if n > 0 {
				// Row exists but its stored etag no longer matches If-Match → stale precondition.
				return nil, persistence.ErrPreconditionFailed
			}
			return nil, persistence.ErrNotFound
		}
	} else {
		// No field mask: full update of every writable column via a map, so
		// zero values (false, 0, "") persist — a struct Updates skips zero fields
		// and would silently drop "disable this" / "clear that" updates.
		updates := map[string]interface{}{
			"display_name": m.DisplayName,
		}
		updates["etag"] = m.ETag
		res := q.Updates(updates)
		if err := res.Error; err != nil {
			if ce := persistence.ConstraintError(err); ce != nil {
				return nil, ce
			}
			return nil, fmt.Errorf("update Region: %w", err)
		}
		if ifMatch != "" && res.RowsAffected == 0 {
			check := r.conn(ctx).Model(&RegionModel{}).Where("id = ?", key)
			if !middleware.IsSystemContext(ctx) {
				check = check.Where("account_id = ?", tenantID)
			}
			var n int64
			if err := check.Count(&n).Error; err != nil {
				return nil, fmt.Errorf("update Region precondition: %w", err)
			}
			if n > 0 {
				// Row exists but its stored etag no longer matches If-Match → stale precondition.
				return nil, persistence.ErrPreconditionFailed
			}
			return nil, persistence.ErrNotFound
		}
	}
	return r.Get(ctx, key)
}

func (r *RegionRepository) Delete(ctx context.Context, key string) error {
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) && tenantID == "" {
		return status.Error(codes.PermissionDenied, "Region: no tenant on a tenant-scoped delete")
	}
	q := r.conn(ctx).Where("id = ?", key)
	if !middleware.IsSystemContext(ctx) {
		q = q.Where("account_id = ?", tenantID)
	}
	res := q.Unscoped().Delete(&RegionModel{})
	if res.Error != nil {
		return fmt.Errorf("delete Region: %w", res.Error)
	}
	if res.RowsAffected == 0 {
		return persistence.ErrNotFound
	}
	return nil
}

func (r *RegionRepository) Undelete(_ context.Context, _ string) (*Region, error) {
	return nil, persistence.ErrNotFound
}

func (r *RegionRepository) BatchGet(ctx context.Context, keys []string) ([]*Region, error) {
	if len(keys) == 0 {
		return []*Region{}, nil
	}
	var models []RegionModel
	q := r.conn(ctx).Where("id IN ?", keys)
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) && tenantID == "" {
		return nil, status.Error(codes.PermissionDenied, "Region: no tenant on a tenant-scoped batch get")
	}
	if !middleware.IsSystemContext(ctx) {
		q = q.Where("account_id = ?", tenantID)
	}
	if err := q.Find(&models).Error; err != nil {
		return nil, fmt.Errorf("batch get Region: %w", err)
	}
	byID := make(map[string]*Region, len(models))
	for i := range models {
		byID[models[i].ID] = fromModel_Region(&models[i])
	}
	out := make([]*Region, 0, len(keys))
	for _, k := range keys {
		p, ok := byID[k]
		if !ok {
			return nil, persistence.ErrNotFound
		}
		out = append(out, p)
	}
	return out, nil
}

func (r *RegionRepository) BatchUpdate(ctx context.Context, items []persistence.BatchUpdateItem[*Region, string]) ([]*Region, error) {
	if len(items) == 0 {
		return []*Region{}, nil
	}
	out := make([]*Region, 0, len(items))
	run := func(txRepo *RegionRepository) error {
		for _, it := range items {
			updated, err := txRepo.Update(ctx, it.Key, it.Entity, it.FieldMask...)
			if err != nil {
				return err
			}
			out = append(out, updated)
		}
		return nil
	}
	if h, ok := persistence.TxFromContext(ctx); ok {
		if tx, ok := h.(*gorm.DB); ok {
			if err := run(&RegionRepository{db: tx}); err != nil {
				return nil, err
			}
			return out, nil
		}
	}
	err := r.db.Transaction(func(tx *gorm.DB) error {
		return run(&RegionRepository{db: tx})
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (r *RegionRepository) BatchDelete(ctx context.Context, keys []string) error {
	if len(keys) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(keys))
	uniq := make([]string, 0, len(keys))
	for _, k := range keys {
		if _, ok := seen[k]; ok {
			continue
		}
		seen[k] = struct{}{}
		uniq = append(uniq, k)
	}
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) && tenantID == "" {
		return status.Error(codes.PermissionDenied, "Region: no tenant on a tenant-scoped batch delete")
	}
	run := func(db *gorm.DB) error {
		q := db.WithContext(ctx).Where("id IN ?", uniq)
		if !middleware.IsSystemContext(ctx) {
			q = q.Where("account_id = ?", tenantID)
		}
		res := q.Unscoped().Delete(&RegionModel{})
		if res.Error != nil {
			return fmt.Errorf("batch delete Region: %w", res.Error)
		}
		if res.RowsAffected != int64(len(uniq)) {
			return persistence.ErrNotFound
		}
		return nil
	}
	if h, ok := persistence.TxFromContext(ctx); ok {
		if tx, ok := h.(*gorm.DB); ok {
			return run(tx)
		}
	}
	return r.db.Transaction(func(tx *gorm.DB) error {
		return run(tx)
	})
}

// compile-time check.
var _ persistence.BatchRepository[*Region, string] = (*RegionRepository)(nil)

// AssetModel is the GORM model for Asset.
type AssetModel struct {
	ID          string `gorm:"primaryKey;type:varchar(36)"`
	AccountId   string `gorm:"column:account_id"`
	DisplayName string `gorm:"column:display_name"`
	RegionId    string `gorm:"column:region_id"`
	ETag        string `gorm:"column:etag"`
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func toModel_Asset(p *Asset) *AssetModel {
	if p == nil {
		return nil
	}
	m := &AssetModel{ID: p.Id}
	m.AccountId = p.AccountId
	m.DisplayName = p.DisplayName
	m.RegionId = p.RegionId
	return m
}

func fromModel_Asset(m *AssetModel) *Asset {
	if m == nil {
		return nil
	}
	p := &Asset{Id: m.ID}
	p.AccountId = m.AccountId
	p.DisplayName = m.DisplayName
	p.RegionId = m.RegionId
	p.Etag = m.ETag
	if FromModelAssetCustom != nil {
		FromModelAssetCustom(m, p)
	}
	return p
}

// FromModelAssetCustom, if set, runs at the end of fromModel_Asset to populate
// fields the generator cannot derive (computed/derived values). Register it
// from your own (regen-safe) file — e.g. in an init(); never assigned here.
var FromModelAssetCustom func(m *AssetModel, p *Asset)

// ToModelAssetOnCreate, if set, runs in Create just before the database write,
// to set columns the generator does not (e.g. a custom-encoded field).
var ToModelAssetOnCreate func(p *Asset, m *AssetModel)

// ToModelAssetOnUpdate, if set, runs in Update just before the database write.
var ToModelAssetOnUpdate func(p *Asset, m *AssetModel)

// AssetColumns maps proto field names to DB column names for safe filter/order_by parsing.
var AssetColumns = map[string]string{
	"id":           "id",
	"account_id":   "account_id",
	"display_name": "display_name",
	"region_id":    "region_id",
}

// AssetNamePattern is the AIP-122 resource name pattern for Asset.
const AssetNamePattern = "assets/{asset}"

// FormatAssetName builds the resource name for the given ID.
func FormatAssetName(id string) string {
	name, _ := resourcename.Format(AssetNamePattern, map[string]string{"asset": id})
	return name
}

// ParseAssetName extracts the resource ID from the given name.
func ParseAssetName(name string) (string, error) {
	return resourcename.IDFromName(AssetNamePattern, name)
}

// AssetRepository is a GORM-backed persistence.Repository for *Asset.
type AssetRepository struct {
	db    *gorm.DB
	idGen persistence.IDGenerator
}

// NewAssetRepository creates a repository backed by db.
func NewAssetRepository(db *gorm.DB, opts ...persistence.RepoOption) *AssetRepository {
	cfg := persistence.NewRepoConfig(persistence.UUID7Generator(), opts...)
	return &AssetRepository{db: db, idGen: cfg.IDGenerator}
}

func (r *AssetRepository) conn(ctx context.Context) *gorm.DB {
	if h, ok := persistence.TxFromContext(ctx); ok {
		if tx, ok := h.(*gorm.DB); ok {
			return tx.WithContext(ctx)
		}
	}
	return r.db.WithContext(ctx)
}

func (r *AssetRepository) Get(ctx context.Context, key string) (*Asset, error) {
	var m AssetModel
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) && tenantID == "" {
		return nil, status.Error(codes.PermissionDenied, "Asset: no tenant on a tenant-scoped get")
	}
	q := r.conn(ctx).Where("id = ?", key)
	if !middleware.IsSystemContext(ctx) {
		q = q.Where("account_id = ?", tenantID)
	}
	if err := q.First(&m).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, persistence.ErrNotFound
		}
		return nil, fmt.Errorf("get Asset: %w", err)
	}
	return fromModel_Asset(&m), nil
}

func (r *AssetRepository) List(ctx context.Context, opts persistence.ListOptions) ([]*Asset, string, error) {
	var models []AssetModel
	q := r.conn(ctx)
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) && tenantID == "" {
		return nil, "", status.Error(codes.PermissionDenied, "Asset: no tenant on a tenant-scoped list")
	}
	if !middleware.IsSystemContext(ctx) {
		q = q.Where("account_id = ?", tenantID)
	}
	if opts.Filter != "" {
		cond, err := filter.Parse(opts.Filter, AssetColumns)
		if err != nil {
			return nil, "", status.Errorf(codes.InvalidArgument, "invalid filter: %v", err)
		}
		sql, args := cond.SQL()
		q = q.Where(sql, args...)
	}
	if opts.OrderBy != "" {
		clauses, err := filter.ParseOrderBy(opts.OrderBy, AssetColumns)
		if err != nil {
			return nil, "", status.Errorf(codes.InvalidArgument, "invalid order_by: %v", err)
		}
		for _, c := range clauses {
			q = q.Order(c.GORMExpr())
		}
	}
	pageSize := opts.PageSize
	if pageSize <= 0 {
		pageSize = 50
	}
	if pageSize > persistence.MaxPageSize {
		pageSize = persistence.MaxPageSize
	}
	offset := 0
	if opts.PageToken != "" {
		if dec, err := base64.StdEncoding.DecodeString(opts.PageToken); err == nil {
			offset, _ = strconv.Atoi(string(dec))
		}
	}
	if err := q.Limit(pageSize).Offset(offset).Find(&models).Error; err != nil {
		return nil, "", fmt.Errorf("list Asset: %w", err)
	}
	out := make([]*Asset, len(models))
	for i := range models {
		out[i] = fromModel_Asset(&models[i])
	}
	nextToken := ""
	if len(models) == pageSize {
		nextToken = base64.StdEncoding.EncodeToString([]byte(strconv.Itoa(offset + pageSize)))
	}
	return out, nextToken, nil
}

func (r *AssetRepository) Create(ctx context.Context, entity *Asset) (*Asset, error) {
	if entity.GetId() == "" {
		entity.Id = r.idGen.NewID()
	}
	m := toModel_Asset(entity)
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) && tenantID == "" {
		return nil, status.Error(codes.PermissionDenied, "Asset: no tenant on a tenant-scoped create")
	}
	if !middleware.IsSystemContext(ctx) {
		m.AccountId = tenantID
	}
	m.ETag = etag.New() // AIP-154: fresh ETag on create
	if ToModelAssetOnCreate != nil {
		ToModelAssetOnCreate(entity, m)
	}
	if err := r.conn(ctx).Create(m).Error; err != nil {
		// Map driver constraint violations to clean sentinels so callers see
		// AlreadyExists/FailedPrecondition (not 500), and no SQL leaks to the client.
		if ce := persistence.ConstraintError(err); ce != nil {
			return nil, ce
		}
		return nil, fmt.Errorf("create Asset: %w", err)
	}
	return fromModel_Asset(m), nil
}

func (r *AssetRepository) Update(ctx context.Context, key string, entity *Asset, fieldMask ...string) (*Asset, error) {
	m := toModel_Asset(entity)
	m.ID = key
	m.ETag = etag.New() // AIP-154: bump the ETag on every update
	if ToModelAssetOnUpdate != nil {
		ToModelAssetOnUpdate(entity, m)
	}
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) && tenantID == "" {
		return nil, status.Error(codes.PermissionDenied, "Asset: no tenant on a tenant-scoped update")
	}
	q := r.conn(ctx).Model(m).Where("id = ?", key)
	if !middleware.IsSystemContext(ctx) {
		q = q.Where("account_id = ?", tenantID)
	}
	ifMatch := etag.IfMatchFromContext(ctx)
	if ifMatch != "" {
		q = q.Where("etag = ?", ifMatch)
	}
	if len(fieldMask) > 0 {
		dbCols := make([]string, 0, len(fieldMask))
		for _, f := range fieldMask {
			col, ok := AssetColumns[f]
			if !ok {
				return nil, status.Errorf(codes.InvalidArgument, "unknown field in update_mask: %q", f)
			}
			if col == "account_id" {
				return nil, status.Errorf(codes.InvalidArgument, "account_id is the tenant key and cannot be updated")
			}
			dbCols = append(dbCols, col)
		}
		dbCols = append(dbCols, "etag") // a masked update still changes the resource
		// Select makes GORM write the named columns even when their value is
		// the zero value (false, 0, ""); a bare struct Updates would skip them.
		res := q.Select(dbCols).Updates(m)
		if err := res.Error; err != nil {
			if ce := persistence.ConstraintError(err); ce != nil {
				return nil, ce
			}
			return nil, fmt.Errorf("update Asset: %w", err)
		}
		if ifMatch != "" && res.RowsAffected == 0 {
			check := r.conn(ctx).Model(&AssetModel{}).Where("id = ?", key)
			if !middleware.IsSystemContext(ctx) {
				check = check.Where("account_id = ?", tenantID)
			}
			var n int64
			if err := check.Count(&n).Error; err != nil {
				return nil, fmt.Errorf("update Asset precondition: %w", err)
			}
			if n > 0 {
				// Row exists but its stored etag no longer matches If-Match → stale precondition.
				return nil, persistence.ErrPreconditionFailed
			}
			return nil, persistence.ErrNotFound
		}
	} else {
		// No field mask: full update of every writable column via a map, so
		// zero values (false, 0, "") persist — a struct Updates skips zero fields
		// and would silently drop "disable this" / "clear that" updates.
		updates := map[string]interface{}{
			"display_name": m.DisplayName,
			"region_id":    m.RegionId,
		}
		updates["etag"] = m.ETag
		res := q.Updates(updates)
		if err := res.Error; err != nil {
			if ce := persistence.ConstraintError(err); ce != nil {
				return nil, ce
			}
			return nil, fmt.Errorf("update Asset: %w", err)
		}
		if ifMatch != "" && res.RowsAffected == 0 {
			check := r.conn(ctx).Model(&AssetModel{}).Where("id = ?", key)
			if !middleware.IsSystemContext(ctx) {
				check = check.Where("account_id = ?", tenantID)
			}
			var n int64
			if err := check.Count(&n).Error; err != nil {
				return nil, fmt.Errorf("update Asset precondition: %w", err)
			}
			if n > 0 {
				// Row exists but its stored etag no longer matches If-Match → stale precondition.
				return nil, persistence.ErrPreconditionFailed
			}
			return nil, persistence.ErrNotFound
		}
	}
	return r.Get(ctx, key)
}

func (r *AssetRepository) Delete(ctx context.Context, key string) error {
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) && tenantID == "" {
		return status.Error(codes.PermissionDenied, "Asset: no tenant on a tenant-scoped delete")
	}
	q := r.conn(ctx).Where("id = ?", key)
	if !middleware.IsSystemContext(ctx) {
		q = q.Where("account_id = ?", tenantID)
	}
	res := q.Unscoped().Delete(&AssetModel{})
	if res.Error != nil {
		return fmt.Errorf("delete Asset: %w", res.Error)
	}
	if res.RowsAffected == 0 {
		return persistence.ErrNotFound
	}
	return nil
}

func (r *AssetRepository) Undelete(_ context.Context, _ string) (*Asset, error) {
	return nil, persistence.ErrNotFound
}

func (r *AssetRepository) BatchGet(ctx context.Context, keys []string) ([]*Asset, error) {
	if len(keys) == 0 {
		return []*Asset{}, nil
	}
	var models []AssetModel
	q := r.conn(ctx).Where("id IN ?", keys)
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) && tenantID == "" {
		return nil, status.Error(codes.PermissionDenied, "Asset: no tenant on a tenant-scoped batch get")
	}
	if !middleware.IsSystemContext(ctx) {
		q = q.Where("account_id = ?", tenantID)
	}
	if err := q.Find(&models).Error; err != nil {
		return nil, fmt.Errorf("batch get Asset: %w", err)
	}
	byID := make(map[string]*Asset, len(models))
	for i := range models {
		byID[models[i].ID] = fromModel_Asset(&models[i])
	}
	out := make([]*Asset, 0, len(keys))
	for _, k := range keys {
		p, ok := byID[k]
		if !ok {
			return nil, persistence.ErrNotFound
		}
		out = append(out, p)
	}
	return out, nil
}

func (r *AssetRepository) BatchUpdate(ctx context.Context, items []persistence.BatchUpdateItem[*Asset, string]) ([]*Asset, error) {
	if len(items) == 0 {
		return []*Asset{}, nil
	}
	out := make([]*Asset, 0, len(items))
	run := func(txRepo *AssetRepository) error {
		for _, it := range items {
			updated, err := txRepo.Update(ctx, it.Key, it.Entity, it.FieldMask...)
			if err != nil {
				return err
			}
			out = append(out, updated)
		}
		return nil
	}
	if h, ok := persistence.TxFromContext(ctx); ok {
		if tx, ok := h.(*gorm.DB); ok {
			if err := run(&AssetRepository{db: tx}); err != nil {
				return nil, err
			}
			return out, nil
		}
	}
	err := r.db.Transaction(func(tx *gorm.DB) error {
		return run(&AssetRepository{db: tx})
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (r *AssetRepository) BatchDelete(ctx context.Context, keys []string) error {
	if len(keys) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(keys))
	uniq := make([]string, 0, len(keys))
	for _, k := range keys {
		if _, ok := seen[k]; ok {
			continue
		}
		seen[k] = struct{}{}
		uniq = append(uniq, k)
	}
	tenantID := middleware.TenantIDFromContext(ctx)
	if !middleware.IsSystemContext(ctx) && tenantID == "" {
		return status.Error(codes.PermissionDenied, "Asset: no tenant on a tenant-scoped batch delete")
	}
	run := func(db *gorm.DB) error {
		q := db.WithContext(ctx).Where("id IN ?", uniq)
		if !middleware.IsSystemContext(ctx) {
			q = q.Where("account_id = ?", tenantID)
		}
		res := q.Unscoped().Delete(&AssetModel{})
		if res.Error != nil {
			return fmt.Errorf("batch delete Asset: %w", res.Error)
		}
		if res.RowsAffected != int64(len(uniq)) {
			return persistence.ErrNotFound
		}
		return nil
	}
	if h, ok := persistence.TxFromContext(ctx); ok {
		if tx, ok := h.(*gorm.DB); ok {
			return run(tx)
		}
	}
	return r.db.Transaction(func(tx *gorm.DB) error {
		return run(tx)
	})
}

// compile-time check.
var _ persistence.BatchRepository[*Asset, string] = (*AssetRepository)(nil)
