// Code generated by protoc-gen-ent. DO NOT EDIT.
package apikeyv1

import (
	"context"
	"fmt"
	"time"

	"github.com/infobloxopen/devedge-sdk/middleware"
	"github.com/infobloxopen/devedge-sdk/middleware/etag"
	"github.com/infobloxopen/devedge-sdk/persistence"
	"github.com/infobloxopen/devedge-sdk/persistence/entrepo"
	ent "github.com/infobloxopen/devedge-sdk/testdata/apikey/ent"
	entapikey "github.com/infobloxopen/devedge-sdk/testdata/apikey/ent/apikey"
	entpredicate "github.com/infobloxopen/devedge-sdk/testdata/apikey/ent/predicate"
)

// NewAPIKeySummaryEntRepository wires the generated ent client into a
// persistence.Repository[*APIKeySummary, string].
func NewAPIKeySummaryEntRepository(client *ent.Client, opts ...persistence.RepoOption) persistence.Repository[*APIKeySummary, string] {
	apikeyClient := func(ctx context.Context) *ent.APIKeyClient {
		if h, ok := persistence.TxFromContext(ctx); ok {
			if tx, ok := h.(*ent.Tx); ok {
				return tx.APIKey
			}
		}
		return client.APIKey
	}
	idGen := persistence.NewRepoConfig(persistence.UUID7Generator(), opts...).IDGenerator
	return &entrepo.EntRepository[*APIKeySummary, string]{
		Create_: func(ctx context.Context, entity *APIKeySummary) (*APIKeySummary, error) {
			if entity.GetId() == "" {
				entity.Id = idGen.NewID()
			}
			tenantID := middleware.TenantIDFromContext(ctx)
			if entity.GetAccountId() == "" && tenantID != "" {
				entity.AccountId = tenantID
			}
			b := apikeyClient(ctx).Create().
				SetID(entity.GetId()).
				SetAccountID(entity.GetAccountId()).
				SetKeyPrefix(entity.GetKeyPrefix()).
				SetLabel(entity.GetLabel())
			if ToEntAPIKeySummaryOnCreate != nil {
				ToEntAPIKeySummaryOnCreate(entity, b)
			}
			created, err := b.Save(ctx)
			if err != nil {
				if ce := persistence.ConstraintError(err); ce != nil {
					return nil, ce
				}
				return nil, fmt.Errorf("create apikey: %w", err)
			}
			return fromEntAPIKeySummary(created), nil
		},
		Get_: func(ctx context.Context, key string) (*APIKeySummary, error) {
			e, err := apikeyClient(ctx).Get(ctx, key)
			if err != nil {
				if ent.IsNotFound(err) {
					return nil, persistence.ErrNotFound
				}
				return nil, err
			}
			return fromEntAPIKeySummary(e), nil
		},
		List_: func(ctx context.Context, opts persistence.ListOptions) ([]*APIKeySummary, string, error) {
			if opts.ShowDeleted {
				ctx = entrepo.WithShowDeleted(ctx)
			}
			q := apikeyClient(ctx).Query()
			if opts.Filter != "" {
				pred, perr := entrepo.FilterPredicate(opts.Filter, APIKeySummaryEntColumns, nil)
				if perr != nil {
					return nil, "", perr
				}
				if pred != nil {
					q = q.Where(entpredicate.APIKey(pred))
				}
			}
			if opts.PageSize <= 0 {
				opts.PageSize = 50
			}
			offset := 0
			if opts.PageToken != "" {
				fmt.Sscanf(opts.PageToken, "%d", &offset) //nolint:errcheck
			}
			items, err := q.Limit(opts.PageSize).Offset(offset).All(ctx)
			if err != nil {
				return nil, "", err
			}
			out := make([]*APIKeySummary, len(items))
			for i, e := range items {
				out[i] = fromEntAPIKeySummary(e)
			}
			nextToken := ""
			if len(items) == opts.PageSize {
				nextToken = fmt.Sprintf("%d", offset+opts.PageSize)
			}
			return out, nextToken, nil
		},
		Update_: func(ctx context.Context, key string, entity *APIKeySummary, fieldMask ...string) (*APIKeySummary, error) {
			u := apikeyClient(ctx).UpdateOneID(key)
			if apikeysummaryInMask(fieldMask, "key_prefix") {
				u = u.SetKeyPrefix(entity.GetKeyPrefix())
			}
			if apikeysummaryInMask(fieldMask, "label") {
				u = u.SetLabel(entity.GetLabel())
			}
			if tenantID := middleware.TenantIDFromContext(ctx); tenantID != "" {
				u = u.Where(entapikey.AccountID(tenantID))
			}
			ifMatch := etag.IfMatchFromContext(ctx)
			if ifMatch != "" {
				u = u.Where(entapikey.Etag(ifMatch))
			}
			if ToEntAPIKeySummaryOnUpdate != nil {
				ToEntAPIKeySummaryOnUpdate(entity, u)
			}
			updated, err := u.Save(ctx)
			if err != nil {
				if ent.IsNotFound(err) && ifMatch != "" {
					check := apikeyClient(ctx).Query().Where(entapikey.ID(key))
					if tenantID := middleware.TenantIDFromContext(ctx); tenantID != "" {
						check = check.Where(entapikey.AccountID(tenantID))
					}
					check = check.Where(entapikey.DeleteTimeIsNil())
					exists, cerr := check.Exist(ctx)
					if cerr != nil {
						return nil, cerr
					}
					if exists {
						// Row present but its stored etag no longer matches If-Match → stale precondition.
						return nil, persistence.ErrPreconditionFailed
					}
					return nil, persistence.ErrNotFound
				}
				if ent.IsNotFound(err) {
					return nil, persistence.ErrNotFound
				}
				if ce := persistence.ConstraintError(err); ce != nil {
					return nil, ce
				}
				return nil, err
			}
			return fromEntAPIKeySummary(updated), nil
		},
		Delete_: func(ctx context.Context, key string) error {
			q := apikeyClient(ctx).UpdateOneID(key)
			if tenantID := middleware.TenantIDFromContext(ctx); tenantID != "" {
				q = q.Where(entapikey.AccountID(tenantID))
			}
			q = q.Where(entapikey.DeleteTimeIsNil())
			err := q.SetDeleteTime(time.Now()).Exec(ctx)
			if ent.IsNotFound(err) {
				return persistence.ErrNotFound
			}
			return err
		},
		Undelete_: func(ctx context.Context, key string) (*APIKeySummary, error) {
			showCtx := entrepo.WithShowDeleted(ctx)
			existing, err := apikeyClient(ctx).Query().Where(
				entapikey.ID(key),
				entapikey.DeleteTimeNotNil(),
			).Only(showCtx)
			if err != nil {
				if ent.IsNotFound(err) {
					return nil, persistence.ErrNotFound
				}
				return nil, fmt.Errorf("undelete apikey: %w", err)
			}
			restored, err := existing.Update().ClearDeleteTime().Save(ctx)
			if err != nil {
				if ce := persistence.ConstraintError(err); ce != nil {
					return nil, ce
				}
				return nil, fmt.Errorf("undelete apikey: %w", err)
			}
			return fromEntAPIKeySummary(restored), nil
		},
	}
}

// FromEntAPIKeySummaryCustom, if set, runs at the end of fromEntAPIKeySummary to populate fields the
// generator cannot derive (computed/derived values). Register it from your own
// (regen-safe) file — e.g. in an init(); this generated file never assigns it.
var FromEntAPIKeySummaryCustom func(e *ent.APIKey, p *APIKeySummary)

// ToEntAPIKeySummaryOnCreate / ToEntAPIKeySummaryOnUpdate, if set, run just before the ent builder is
// saved, to set columns the generator does not (e.g. a custom-encoded field).
var ToEntAPIKeySummaryOnCreate func(p *APIKeySummary, b *ent.APIKeyCreate)
var ToEntAPIKeySummaryOnUpdate func(p *APIKeySummary, u *ent.APIKeyUpdateOne)

// fromEntAPIKeySummary converts a generated ent.APIKey to the proto *APIKeySummary. Secret fields are
// intentionally omitted — they are never returned from storage after creation.
func fromEntAPIKeySummary(e *ent.APIKey) *APIKeySummary {
	if e == nil {
		return nil
	}
	p := &APIKeySummary{
		Id:        e.ID,
		AccountId: e.AccountID,
		KeyPrefix: e.KeyPrefix,
		Label:     e.Label,
	}
	if FromEntAPIKeySummaryCustom != nil {
		FromEntAPIKeySummaryCustom(e, p)
	}
	return p
}
