// Code generated by protoc-gen-ent. DO NOT EDIT.
package apikeyv1

import (
	"context"
	"fmt"
	"time"

	"github.com/infobloxopen/devedge-sdk/middleware"
	"github.com/infobloxopen/devedge-sdk/persistence"
	ent "github.com/infobloxopen/devedge-sdk/testdata/apikey/ent"
	entapikey "github.com/infobloxopen/devedge-sdk/testdata/apikey/ent/apikey"
)

// APIKeySummaryEntRepository adds atomic AIP-137 batch methods to the ent-backed APIKeySummary,
// making it a persistence.BatchRepository. Standard methods come from the
// embedded hand-written adapter.
type APIKeySummaryEntRepository struct {
	persistence.Repository[*APIKeySummary, string]
	client *ent.Client
}

// NewAPIKeySummaryEntBatchRepository wraps the hand-written ent adapter with batch support.
func NewAPIKeySummaryEntBatchRepository(client *ent.Client) *APIKeySummaryEntRepository {
	return &APIKeySummaryEntRepository{Repository: NewAPIKeySummaryEntRepository(client), client: client}
}

func apikeysummaryInMask(mask []string, field string) bool {
	if len(mask) == 0 {
		return true
	}
	for _, m := range mask {
		if m == field {
			return true
		}
	}
	return false
}

func (r *APIKeySummaryEntRepository) BatchGet(ctx context.Context, keys []string) ([]*APIKeySummary, error) {
	if len(keys) == 0 {
		return []*APIKeySummary{}, nil
	}
	rows, err := r.client.APIKey.Query().Where(entapikey.IDIn(keys...)).All(ctx)
	if err != nil {
		return nil, fmt.Errorf("batch get apikey: %w", err)
	}
	byID := make(map[string]*APIKeySummary, len(rows))
	for _, e := range rows {
		byID[e.ID] = fromEntAPIKeySummary(e)
	}
	out := make([]*APIKeySummary, 0, len(keys))
	for _, k := range keys {
		p, ok := byID[k]
		if !ok {
			return nil, persistence.ErrNotFound
		}
		out = append(out, p)
	}
	return out, nil
}

func (r *APIKeySummaryEntRepository) BatchUpdate(ctx context.Context, items []persistence.BatchUpdateItem[*APIKeySummary, string]) ([]*APIKeySummary, error) {
	if len(items) == 0 {
		return []*APIKeySummary{}, nil
	}
	tenantID := middleware.TenantIDFromContext(ctx)
	tx, err := r.client.Tx(ctx)
	if err != nil {
		return nil, fmt.Errorf("begin tx: %w", err)
	}
	out := make([]*APIKeySummary, 0, len(items))
	for _, it := range items {
		u := tx.APIKey.UpdateOneID(it.Key)
		if tenantID != "" {
			u = u.Where(entapikey.AccountID(tenantID))
		}
		u = u.Where(entapikey.DeleteTimeIsNil())
		if apikeysummaryInMask(it.FieldMask, "key_prefix") {
			u = u.SetKeyPrefix(it.Entity.GetKeyPrefix())
		}
		if apikeysummaryInMask(it.FieldMask, "label") {
			u = u.SetLabel(it.Entity.GetLabel())
		}
		saved, serr := u.Save(ctx)
		if serr != nil {
			_ = tx.Rollback()
			if ent.IsNotFound(serr) {
				return nil, persistence.ErrNotFound
			}
			return nil, fmt.Errorf("batch update apikey: %w", serr)
		}
		out = append(out, fromEntAPIKeySummary(saved))
	}
	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("commit tx: %w", err)
	}
	return out, nil
}

func (r *APIKeySummaryEntRepository) BatchDelete(ctx context.Context, keys []string) error {
	if len(keys) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(keys))
	uniq := make([]string, 0, len(keys))
	for _, k := range keys {
		if _, ok := seen[k]; ok {
			continue
		}
		seen[k] = struct{}{}
		uniq = append(uniq, k)
	}
	tenantID := middleware.TenantIDFromContext(ctx)
	tx, err := r.client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	upd := tx.APIKey.Update().Where(entapikey.IDIn(uniq...))
	if tenantID != "" {
		upd = upd.Where(entapikey.AccountID(tenantID))
	}
	upd = upd.Where(entapikey.DeleteTimeIsNil())
	n, derr := upd.SetDeleteTime(time.Now()).Save(ctx)
	if derr != nil {
		_ = tx.Rollback()
		return fmt.Errorf("batch delete apikey: %w", derr)
	}
	if n != len(uniq) {
		_ = tx.Rollback()
		return persistence.ErrNotFound
	}
	return tx.Commit()
}

// compile-time check.
var _ persistence.BatchRepository[*APIKeySummary, string] = (*APIKeySummaryEntRepository)(nil)
