// Code generated by protoc-gen-ent. DO NOT EDIT.
package apikeyv1

// APIKeyEntColumns maps proto field names to ent DB column names for safe
// AIP-160 filter / AIP-132 order_by parsing on the ent backend.
var APIKeyEntColumns = map[string]string{
	"id":          "id",
	"account_id":  "account_id",
	"key_prefix":  "key_prefix",
	"label":       "label",
	"delete_time": "delete_time",
	"expire_time": "expire_time",
}

// APIKeyEntJSONColumns maps tag (map<string,string>) field names to ent DB
// columns for `tags.<key>` filtering on the ent backend.
var APIKeyEntJSONColumns = map[string]string{
	"tags": "tags",
}
