// Code generated by protoc-gen-storage. DO NOT EDIT.
// source: (proto input)

package apikeyv1

import (
	"context"
	"encoding/base64"
	"fmt"
	"strconv"
	"time"

	"gorm.io/gorm"

	"github.com/infobloxopen/devedge-sdk/persistence"
	"github.com/infobloxopen/devedge-sdk/middleware"
	"github.com/infobloxopen/devedge-sdk/secret"
)

var (
	_ = base64.StdEncoding
	_ = fmt.Sprintf
	_ = strconv.Itoa
)

// APIKeyModel is the GORM model for APIKey.
type APIKeyModel struct {
	ID             string `gorm:"primaryKey;type:varchar(36)"`
	Name           string `gorm:"column:name"`
	AccountId      string `gorm:"column:account_id"`
	KeyValueHash   string `gorm:"column:key_value_hash;index"`
	KeyValueCipher string `gorm:"column:key_value_cipher"`
	KeyPrefix      string `gorm:"column:key_prefix"`
	ETag           string `gorm:"column:etag"`
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      gorm.DeletedAt `gorm:"index"`
}

func toModel_APIKey(p *APIKey) *APIKeyModel {
	if p == nil {
		return nil
	}
	m := &APIKeyModel{ID: p.Id}
	m.Name = p.Name
	m.AccountId = p.AccountId
	m.KeyPrefix = p.KeyPrefix
	return m
}

func fromModel_APIKey(m *APIKeyModel) *APIKey {
	if m == nil {
		return nil
	}
	p := &APIKey{Id: m.ID}
	p.Name = m.Name
	p.AccountId = m.AccountId
	p.KeyPrefix = m.KeyPrefix
	return p
}

// APIKeyRepository is a GORM-backed persistence.Repository for *APIKey.
type APIKeyRepository struct {
	db  *gorm.DB
	enc secret.Encryptor
}

// NewAPIKeyRepository creates a repository backed by db and enc.
func NewAPIKeyRepository(db *gorm.DB, enc secret.Encryptor) *APIKeyRepository {
	return &APIKeyRepository{db: db, enc: enc}
}

func (r *APIKeyRepository) Get(ctx context.Context, key string) (*APIKey, error) {
	var m APIKeyModel
	tenantID := middleware.TenantIDFromContext(ctx)
	q := r.db.WithContext(ctx).Where("id = ?", key)
	if tenantID != "" {
		q = q.Where("account_id = ?", tenantID)
	}
	if err := q.First(&m).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, persistence.ErrNotFound
		}
		return nil, fmt.Errorf("get APIKey: %w", err)
	}
	return fromModel_APIKey(&m), nil
}

func (r *APIKeyRepository) List(ctx context.Context, opts persistence.ListOptions) ([]*APIKey, string, error) {
	var models []APIKeyModel
	q := r.db.WithContext(ctx)
	tenantID := middleware.TenantIDFromContext(ctx)
	if tenantID != "" {
		q = q.Where("account_id = ?", tenantID)
	}
	if opts.Filter != "" {
		q = q.Where(opts.Filter)
	}
	pageSize := opts.PageSize
	if pageSize <= 0 {
		pageSize = 50
	}
	offset := 0
	if opts.PageToken != "" {
		if dec, err := base64.StdEncoding.DecodeString(opts.PageToken); err == nil {
			offset, _ = strconv.Atoi(string(dec))
		}
	}
	if err := q.Limit(pageSize).Offset(offset).Find(&models).Error; err != nil {
		return nil, "", fmt.Errorf("list APIKey: %w", err)
	}
	out := make([]*APIKey, len(models))
	for i := range models {
		out[i] = fromModel_APIKey(&models[i])
	}
	nextToken := ""
	if len(models) == pageSize {
		nextToken = base64.StdEncoding.EncodeToString([]byte(strconv.Itoa(offset + pageSize)))
	}
	return out, nextToken, nil
}

func (r *APIKeyRepository) Create(ctx context.Context, entity *APIKey) (*APIKey, error) {
	m := toModel_APIKey(entity)
	if entity.KeyValue != "" {
		h, err := r.enc.Hash(ctx, entity.KeyValue)
		if err != nil {
			return nil, fmt.Errorf("hash key_value: %w", err)
		}
		c, err := r.enc.Encrypt(ctx, entity.KeyValue)
		if err != nil {
			return nil, fmt.Errorf("encrypt key_value: %w", err)
		}
		m.KeyValueHash = h
		m.KeyValueCipher = c
	}
	if err := r.db.WithContext(ctx).Create(m).Error; err != nil {
		return nil, fmt.Errorf("create APIKey: %w", err)
	}
	return fromModel_APIKey(m), nil
}

func (r *APIKeyRepository) Update(ctx context.Context, key string, entity *APIKey, fieldMask ...string) (*APIKey, error) {
	m := toModel_APIKey(entity)
	m.ID = key
	if entity.KeyValue != "" {
		h, err := r.enc.Hash(ctx, entity.KeyValue)
		if err != nil {
			return nil, fmt.Errorf("hash key_value: %w", err)
		}
		c, err := r.enc.Encrypt(ctx, entity.KeyValue)
		if err != nil {
			return nil, fmt.Errorf("encrypt key_value: %w", err)
		}
		m.KeyValueHash = h
		m.KeyValueCipher = c
	}
	tenantID := middleware.TenantIDFromContext(ctx)
	q := r.db.WithContext(ctx).Model(m).Where("id = ?", key)
	if tenantID != "" {
		q = q.Where("account_id = ?", tenantID)
	}
	if len(fieldMask) > 0 {
		q = q.Select(fieldMask)
	}
	if err := q.Updates(m).Error; err != nil {
		return nil, fmt.Errorf("update APIKey: %w", err)
	}
	return r.Get(ctx, key)
}

func (r *APIKeyRepository) Delete(ctx context.Context, key string) error {
	tenantID := middleware.TenantIDFromContext(ctx)
	q := r.db.WithContext(ctx).Where("id = ?", key)
	if tenantID != "" {
		q = q.Where("account_id = ?", tenantID)
	}
	if err := q.Delete(&APIKeyModel{}).Error; err != nil {
		return fmt.Errorf("delete APIKey: %w", err)
	}
	return nil
}

// LookupByKeyValueHash finds the APIKey by the hash of its KeyValue field.
// Returns ErrNotFound when no record matches or when hash is empty.
func (r *APIKeyRepository) LookupByKeyValueHash(ctx context.Context, hash string) (*APIKey, error) {
	if hash == "" {
		return nil, persistence.ErrNotFound
	}
	tenantID := middleware.TenantIDFromContext(ctx)
	q := r.db.WithContext(ctx).Where("key_value_hash = ?", hash)
	if tenantID != "" {
		q = q.Where("account_id = ?", tenantID)
	}
	var m APIKeyModel
	if err := q.First(&m).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, persistence.ErrNotFound
		}
		return nil, fmt.Errorf("lookup aPIKey by key_value hash: %w", err)
	}
	return fromModel_APIKey(&m), nil
}

// compile-time check.
var _ persistence.Repository[*APIKey, string] = (*APIKeyRepository)(nil)
