// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"github.com/infobloxopen/devedge-sdk/testdata/iam/ent/account"
	"github.com/infobloxopen/devedge-sdk/testdata/iam/ent/apikey"
	"github.com/infobloxopen/devedge-sdk/testdata/iam/ent/group"
	"github.com/infobloxopen/devedge-sdk/testdata/iam/ent/idempotencykey"
	"github.com/infobloxopen/devedge-sdk/testdata/iam/ent/membership"
	"github.com/infobloxopen/devedge-sdk/testdata/iam/ent/outboxcursor"
	"github.com/infobloxopen/devedge-sdk/testdata/iam/ent/schema"
	"github.com/infobloxopen/devedge-sdk/testdata/iam/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountMixin := schema.Account{}.Mixin()
	accountMixinHooks0 := accountMixin[0].Hooks()
	account.Hooks[0] = accountMixinHooks0[0]
	apikeyMixin := schema.ApiKey{}.Mixin()
	apikeyMixinHooks1 := apikeyMixin[1].Hooks()
	apikey.Hooks[0] = apikeyMixinHooks1[0]
	apikeyMixinInters0 := apikeyMixin[0].Interceptors()
	apikey.Interceptors[0] = apikeyMixinInters0[0]
	apikeyMixinFields0 := apikeyMixin[0].Fields()
	_ = apikeyMixinFields0
	apikeyFields := schema.ApiKey{}.Fields()
	_ = apikeyFields
	// apikeyDescAccountID is the schema descriptor for account_id field.
	apikeyDescAccountID := apikeyMixinFields0[0].Descriptor()
	// apikey.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	apikey.AccountIDValidator = apikeyDescAccountID.Validators[0].(func(string) error)
	groupMixin := schema.Group{}.Mixin()
	groupMixinHooks1 := groupMixin[1].Hooks()
	group.Hooks[0] = groupMixinHooks1[0]
	groupMixinInters0 := groupMixin[0].Interceptors()
	group.Interceptors[0] = groupMixinInters0[0]
	groupMixinFields0 := groupMixin[0].Fields()
	_ = groupMixinFields0
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescAccountID is the schema descriptor for account_id field.
	groupDescAccountID := groupMixinFields0[0].Descriptor()
	// group.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	group.AccountIDValidator = groupDescAccountID.Validators[0].(func(string) error)
	idempotencykeyFields := schema.IdempotencyKey{}.Fields()
	_ = idempotencykeyFields
	// idempotencykeyDescAccountID is the schema descriptor for account_id field.
	idempotencykeyDescAccountID := idempotencykeyFields[1].Descriptor()
	// idempotencykey.DefaultAccountID holds the default value on creation for the account_id field.
	idempotencykey.DefaultAccountID = idempotencykeyDescAccountID.Default.(string)
	// idempotencykeyDescMethod is the schema descriptor for method field.
	idempotencykeyDescMethod := idempotencykeyFields[2].Descriptor()
	// idempotencykey.DefaultMethod holds the default value on creation for the method field.
	idempotencykey.DefaultMethod = idempotencykeyDescMethod.Default.(string)
	// idempotencykeyDescRequestID is the schema descriptor for request_id field.
	idempotencykeyDescRequestID := idempotencykeyFields[3].Descriptor()
	// idempotencykey.DefaultRequestID holds the default value on creation for the request_id field.
	idempotencykey.DefaultRequestID = idempotencykeyDescRequestID.Default.(string)
	// idempotencykeyDescStatus is the schema descriptor for status field.
	idempotencykeyDescStatus := idempotencykeyFields[4].Descriptor()
	// idempotencykey.DefaultStatus holds the default value on creation for the status field.
	idempotencykey.DefaultStatus = idempotencykeyDescStatus.Default.(string)
	// idempotencykeyDescResponseType is the schema descriptor for response_type field.
	idempotencykeyDescResponseType := idempotencykeyFields[5].Descriptor()
	// idempotencykey.DefaultResponseType holds the default value on creation for the response_type field.
	idempotencykey.DefaultResponseType = idempotencykeyDescResponseType.Default.(string)
	// idempotencykeyDescFingerprint is the schema descriptor for fingerprint field.
	idempotencykeyDescFingerprint := idempotencykeyFields[7].Descriptor()
	// idempotencykey.DefaultFingerprint holds the default value on creation for the fingerprint field.
	idempotencykey.DefaultFingerprint = idempotencykeyDescFingerprint.Default.(string)
	membershipMixin := schema.Membership{}.Mixin()
	membershipMixinInters0 := membershipMixin[0].Interceptors()
	membership.Interceptors[0] = membershipMixinInters0[0]
	membershipMixinFields0 := membershipMixin[0].Fields()
	_ = membershipMixinFields0
	membershipFields := schema.Membership{}.Fields()
	_ = membershipFields
	// membershipDescAccountID is the schema descriptor for account_id field.
	membershipDescAccountID := membershipMixinFields0[0].Descriptor()
	// membership.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	membership.AccountIDValidator = membershipDescAccountID.Validators[0].(func(string) error)
	outboxcursorFields := schema.OutboxCursor{}.Fields()
	_ = outboxcursorFields
	// outboxcursorDescHeadFailures is the schema descriptor for head_failures field.
	outboxcursorDescHeadFailures := outboxcursorFields[3].Descriptor()
	// outboxcursor.DefaultHeadFailures holds the default value on creation for the head_failures field.
	outboxcursor.DefaultHeadFailures = outboxcursorDescHeadFailures.Default.(int)
	userMixin := schema.User{}.Mixin()
	userMixinHooks1 := userMixin[1].Hooks()
	user.Hooks[0] = userMixinHooks1[0]
	userMixinInters0 := userMixin[0].Interceptors()
	user.Interceptors[0] = userMixinInters0[0]
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAccountID is the schema descriptor for account_id field.
	userDescAccountID := userMixinFields0[0].Descriptor()
	// user.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	user.AccountIDValidator = userDescAccountID.Validators[0].(func(string) error)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
