// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/infobloxopen/devedge-sdk/testdata/iam/ent/apikey"
	"github.com/infobloxopen/devedge-sdk/testdata/iam/ent/predicate"
)

// ApiKeyUpdate is the builder for updating ApiKey entities.
type ApiKeyUpdate struct {
	config
	hooks    []Hook
	mutation *ApiKeyMutation
}

// Where appends a list predicates to the ApiKeyUpdate builder.
func (_u *ApiKeyUpdate) Where(ps ...predicate.ApiKey) *ApiKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEtag sets the "etag" field.
func (_u *ApiKeyUpdate) SetEtag(v string) *ApiKeyUpdate {
	_u.mutation.SetEtag(v)
	return _u
}

// SetNillableEtag sets the "etag" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableEtag(v *string) *ApiKeyUpdate {
	if v != nil {
		_u.SetEtag(*v)
	}
	return _u
}

// ClearEtag clears the value of the "etag" field.
func (_u *ApiKeyUpdate) ClearEtag() *ApiKeyUpdate {
	_u.mutation.ClearEtag()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ApiKeyUpdate) SetUserID(v string) *ApiKeyUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableUserID(v *string) *ApiKeyUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ApiKeyUpdate) ClearUserID() *ApiKeyUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetKeyValueHash sets the "key_value_hash" field.
func (_u *ApiKeyUpdate) SetKeyValueHash(v string) *ApiKeyUpdate {
	_u.mutation.SetKeyValueHash(v)
	return _u
}

// SetNillableKeyValueHash sets the "key_value_hash" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableKeyValueHash(v *string) *ApiKeyUpdate {
	if v != nil {
		_u.SetKeyValueHash(*v)
	}
	return _u
}

// ClearKeyValueHash clears the value of the "key_value_hash" field.
func (_u *ApiKeyUpdate) ClearKeyValueHash() *ApiKeyUpdate {
	_u.mutation.ClearKeyValueHash()
	return _u
}

// SetKeyValueCipher sets the "key_value_cipher" field.
func (_u *ApiKeyUpdate) SetKeyValueCipher(v string) *ApiKeyUpdate {
	_u.mutation.SetKeyValueCipher(v)
	return _u
}

// SetNillableKeyValueCipher sets the "key_value_cipher" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableKeyValueCipher(v *string) *ApiKeyUpdate {
	if v != nil {
		_u.SetKeyValueCipher(*v)
	}
	return _u
}

// ClearKeyValueCipher clears the value of the "key_value_cipher" field.
func (_u *ApiKeyUpdate) ClearKeyValueCipher() *ApiKeyUpdate {
	_u.mutation.ClearKeyValueCipher()
	return _u
}

// SetKeyPrefix sets the "key_prefix" field.
func (_u *ApiKeyUpdate) SetKeyPrefix(v string) *ApiKeyUpdate {
	_u.mutation.SetKeyPrefix(v)
	return _u
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableKeyPrefix(v *string) *ApiKeyUpdate {
	if v != nil {
		_u.SetKeyPrefix(*v)
	}
	return _u
}

// ClearKeyPrefix clears the value of the "key_prefix" field.
func (_u *ApiKeyUpdate) ClearKeyPrefix() *ApiKeyUpdate {
	_u.mutation.ClearKeyPrefix()
	return _u
}

// Mutation returns the ApiKeyMutation object of the builder.
func (_u *ApiKeyUpdate) Mutation() *ApiKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApiKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApiKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ApiKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(apikey.Table, apikey.Columns, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Etag(); ok {
		_spec.SetField(apikey.FieldEtag, field.TypeString, value)
	}
	if _u.mutation.EtagCleared() {
		_spec.ClearField(apikey.FieldEtag, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(apikey.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(apikey.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.KeyValueHash(); ok {
		_spec.SetField(apikey.FieldKeyValueHash, field.TypeString, value)
	}
	if _u.mutation.KeyValueHashCleared() {
		_spec.ClearField(apikey.FieldKeyValueHash, field.TypeString)
	}
	if value, ok := _u.mutation.KeyValueCipher(); ok {
		_spec.SetField(apikey.FieldKeyValueCipher, field.TypeString, value)
	}
	if _u.mutation.KeyValueCipherCleared() {
		_spec.ClearField(apikey.FieldKeyValueCipher, field.TypeString)
	}
	if value, ok := _u.mutation.KeyPrefix(); ok {
		_spec.SetField(apikey.FieldKeyPrefix, field.TypeString, value)
	}
	if _u.mutation.KeyPrefixCleared() {
		_spec.ClearField(apikey.FieldKeyPrefix, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApiKeyUpdateOne is the builder for updating a single ApiKey entity.
type ApiKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApiKeyMutation
}

// SetEtag sets the "etag" field.
func (_u *ApiKeyUpdateOne) SetEtag(v string) *ApiKeyUpdateOne {
	_u.mutation.SetEtag(v)
	return _u
}

// SetNillableEtag sets the "etag" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableEtag(v *string) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetEtag(*v)
	}
	return _u
}

// ClearEtag clears the value of the "etag" field.
func (_u *ApiKeyUpdateOne) ClearEtag() *ApiKeyUpdateOne {
	_u.mutation.ClearEtag()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ApiKeyUpdateOne) SetUserID(v string) *ApiKeyUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableUserID(v *string) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ApiKeyUpdateOne) ClearUserID() *ApiKeyUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetKeyValueHash sets the "key_value_hash" field.
func (_u *ApiKeyUpdateOne) SetKeyValueHash(v string) *ApiKeyUpdateOne {
	_u.mutation.SetKeyValueHash(v)
	return _u
}

// SetNillableKeyValueHash sets the "key_value_hash" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableKeyValueHash(v *string) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetKeyValueHash(*v)
	}
	return _u
}

// ClearKeyValueHash clears the value of the "key_value_hash" field.
func (_u *ApiKeyUpdateOne) ClearKeyValueHash() *ApiKeyUpdateOne {
	_u.mutation.ClearKeyValueHash()
	return _u
}

// SetKeyValueCipher sets the "key_value_cipher" field.
func (_u *ApiKeyUpdateOne) SetKeyValueCipher(v string) *ApiKeyUpdateOne {
	_u.mutation.SetKeyValueCipher(v)
	return _u
}

// SetNillableKeyValueCipher sets the "key_value_cipher" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableKeyValueCipher(v *string) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetKeyValueCipher(*v)
	}
	return _u
}

// ClearKeyValueCipher clears the value of the "key_value_cipher" field.
func (_u *ApiKeyUpdateOne) ClearKeyValueCipher() *ApiKeyUpdateOne {
	_u.mutation.ClearKeyValueCipher()
	return _u
}

// SetKeyPrefix sets the "key_prefix" field.
func (_u *ApiKeyUpdateOne) SetKeyPrefix(v string) *ApiKeyUpdateOne {
	_u.mutation.SetKeyPrefix(v)
	return _u
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableKeyPrefix(v *string) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetKeyPrefix(*v)
	}
	return _u
}

// ClearKeyPrefix clears the value of the "key_prefix" field.
func (_u *ApiKeyUpdateOne) ClearKeyPrefix() *ApiKeyUpdateOne {
	_u.mutation.ClearKeyPrefix()
	return _u
}

// Mutation returns the ApiKeyMutation object of the builder.
func (_u *ApiKeyUpdateOne) Mutation() *ApiKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the ApiKeyUpdate builder.
func (_u *ApiKeyUpdateOne) Where(ps ...predicate.ApiKey) *ApiKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApiKeyUpdateOne) Select(field string, fields ...string) *ApiKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ApiKey entity.
func (_u *ApiKeyUpdateOne) Save(ctx context.Context) (*ApiKey, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiKeyUpdateOne) SaveX(ctx context.Context) *ApiKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApiKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ApiKeyUpdateOne) sqlSave(ctx context.Context) (_node *ApiKey, err error) {
	_spec := sqlgraph.NewUpdateSpec(apikey.Table, apikey.Columns, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApiKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikey.FieldID)
		for _, f := range fields {
			if !apikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Etag(); ok {
		_spec.SetField(apikey.FieldEtag, field.TypeString, value)
	}
	if _u.mutation.EtagCleared() {
		_spec.ClearField(apikey.FieldEtag, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(apikey.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(apikey.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.KeyValueHash(); ok {
		_spec.SetField(apikey.FieldKeyValueHash, field.TypeString, value)
	}
	if _u.mutation.KeyValueHashCleared() {
		_spec.ClearField(apikey.FieldKeyValueHash, field.TypeString)
	}
	if value, ok := _u.mutation.KeyValueCipher(); ok {
		_spec.SetField(apikey.FieldKeyValueCipher, field.TypeString, value)
	}
	if _u.mutation.KeyValueCipherCleared() {
		_spec.ClearField(apikey.FieldKeyValueCipher, field.TypeString)
	}
	if value, ok := _u.mutation.KeyPrefix(); ok {
		_spec.SetField(apikey.FieldKeyPrefix, field.TypeString, value)
	}
	if _u.mutation.KeyPrefixCleared() {
		_spec.ClearField(apikey.FieldKeyPrefix, field.TypeString)
	}
	_node = &ApiKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
