// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/infobloxopen/devedge-sdk/testdata/iam/ent/idemmarker"
	"github.com/infobloxopen/devedge-sdk/testdata/iam/ent/predicate"
)

// IdemMarkerUpdate is the builder for updating IdemMarker entities.
type IdemMarkerUpdate struct {
	config
	hooks    []Hook
	mutation *IdemMarkerMutation
}

// Where appends a list predicates to the IdemMarkerUpdate builder.
func (_u *IdemMarkerUpdate) Where(ps ...predicate.IdemMarker) *IdemMarkerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the IdemMarkerMutation object of the builder.
func (_u *IdemMarkerUpdate) Mutation() *IdemMarkerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IdemMarkerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IdemMarkerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IdemMarkerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IdemMarkerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *IdemMarkerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(idemmarker.Table, idemmarker.Columns, sqlgraph.NewFieldSpec(idemmarker.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idemmarker.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IdemMarkerUpdateOne is the builder for updating a single IdemMarker entity.
type IdemMarkerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IdemMarkerMutation
}

// Mutation returns the IdemMarkerMutation object of the builder.
func (_u *IdemMarkerUpdateOne) Mutation() *IdemMarkerMutation {
	return _u.mutation
}

// Where appends a list predicates to the IdemMarkerUpdate builder.
func (_u *IdemMarkerUpdateOne) Where(ps ...predicate.IdemMarker) *IdemMarkerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IdemMarkerUpdateOne) Select(field string, fields ...string) *IdemMarkerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IdemMarker entity.
func (_u *IdemMarkerUpdateOne) Save(ctx context.Context) (*IdemMarker, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IdemMarkerUpdateOne) SaveX(ctx context.Context) *IdemMarker {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IdemMarkerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IdemMarkerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *IdemMarkerUpdateOne) sqlSave(ctx context.Context) (_node *IdemMarker, err error) {
	_spec := sqlgraph.NewUpdateSpec(idemmarker.Table, idemmarker.Columns, sqlgraph.NewFieldSpec(idemmarker.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IdemMarker.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, idemmarker.FieldID)
		for _, f := range fields {
			if !idemmarker.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != idemmarker.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &IdemMarker{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idemmarker.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
