// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/infobloxopen/devedge-sdk/testdata/iam/ent/outboxdeadletter"
)

// OutboxDeadLetter is the model entity for the OutboxDeadLetter schema.
type OutboxDeadLetter struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CursorName holds the value of the "cursor_name" field.
	CursorName string `json:"cursor_name,omitempty"`
	// EventID holds the value of the "event_id" field.
	EventID string `json:"event_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// CreatedTime holds the value of the "created_time" field.
	CreatedTime time.Time `json:"created_time,omitempty"`
	// RecordedAt holds the value of the "recorded_at" field.
	RecordedAt   time.Time `json:"recorded_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OutboxDeadLetter) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case outboxdeadletter.FieldID:
			values[i] = new(sql.NullInt64)
		case outboxdeadletter.FieldCursorName, outboxdeadletter.FieldEventID, outboxdeadletter.FieldEventType, outboxdeadletter.FieldReason:
			values[i] = new(sql.NullString)
		case outboxdeadletter.FieldCreatedTime, outboxdeadletter.FieldRecordedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OutboxDeadLetter fields.
func (_m *OutboxDeadLetter) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case outboxdeadletter.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case outboxdeadletter.FieldCursorName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cursor_name", values[i])
			} else if value.Valid {
				_m.CursorName = value.String
			}
		case outboxdeadletter.FieldEventID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_id", values[i])
			} else if value.Valid {
				_m.EventID = value.String
			}
		case outboxdeadletter.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case outboxdeadletter.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case outboxdeadletter.FieldCreatedTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_time", values[i])
			} else if value.Valid {
				_m.CreatedTime = value.Time
			}
		case outboxdeadletter.FieldRecordedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field recorded_at", values[i])
			} else if value.Valid {
				_m.RecordedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OutboxDeadLetter.
// This includes values selected through modifiers, order, etc.
func (_m *OutboxDeadLetter) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OutboxDeadLetter.
// Note that you need to call OutboxDeadLetter.Unwrap() before calling this method if this OutboxDeadLetter
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OutboxDeadLetter) Update() *OutboxDeadLetterUpdateOne {
	return NewOutboxDeadLetterClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OutboxDeadLetter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OutboxDeadLetter) Unwrap() *OutboxDeadLetter {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OutboxDeadLetter is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OutboxDeadLetter) String() string {
	var builder strings.Builder
	builder.WriteString("OutboxDeadLetter(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("cursor_name=")
	builder.WriteString(_m.CursorName)
	builder.WriteString(", ")
	builder.WriteString("event_id=")
	builder.WriteString(_m.EventID)
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("created_time=")
	builder.WriteString(_m.CreatedTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("recorded_at=")
	builder.WriteString(_m.RecordedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OutboxDeadLetters is a parsable slice of OutboxDeadLetter.
type OutboxDeadLetters []*OutboxDeadLetter
