// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/infobloxopen/devedge-sdk/testdata/iam/ent/outbox"
	"github.com/infobloxopen/devedge-sdk/testdata/iam/ent/predicate"
)

// OutboxUpdate is the builder for updating Outbox entities.
type OutboxUpdate struct {
	config
	hooks    []Hook
	mutation *OutboxMutation
}

// Where appends a list predicates to the OutboxUpdate builder.
func (_u *OutboxUpdate) Where(ps ...predicate.Outbox) *OutboxUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OutboxUpdate) SetAccountID(v string) *OutboxUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OutboxUpdate) SetNillableAccountID(v *string) *OutboxUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *OutboxUpdate) ClearAccountID() *OutboxUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetAggregateType sets the "aggregate_type" field.
func (_u *OutboxUpdate) SetAggregateType(v string) *OutboxUpdate {
	_u.mutation.SetAggregateType(v)
	return _u
}

// SetNillableAggregateType sets the "aggregate_type" field if the given value is not nil.
func (_u *OutboxUpdate) SetNillableAggregateType(v *string) *OutboxUpdate {
	if v != nil {
		_u.SetAggregateType(*v)
	}
	return _u
}

// ClearAggregateType clears the value of the "aggregate_type" field.
func (_u *OutboxUpdate) ClearAggregateType() *OutboxUpdate {
	_u.mutation.ClearAggregateType()
	return _u
}

// SetAggregateID sets the "aggregate_id" field.
func (_u *OutboxUpdate) SetAggregateID(v string) *OutboxUpdate {
	_u.mutation.SetAggregateID(v)
	return _u
}

// SetNillableAggregateID sets the "aggregate_id" field if the given value is not nil.
func (_u *OutboxUpdate) SetNillableAggregateID(v *string) *OutboxUpdate {
	if v != nil {
		_u.SetAggregateID(*v)
	}
	return _u
}

// ClearAggregateID clears the value of the "aggregate_id" field.
func (_u *OutboxUpdate) ClearAggregateID() *OutboxUpdate {
	_u.mutation.ClearAggregateID()
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *OutboxUpdate) SetEventType(v string) *OutboxUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *OutboxUpdate) SetNillableEventType(v *string) *OutboxUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// ClearEventType clears the value of the "event_type" field.
func (_u *OutboxUpdate) ClearEventType() *OutboxUpdate {
	_u.mutation.ClearEventType()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *OutboxUpdate) SetPayload(v []byte) *OutboxUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *OutboxUpdate) ClearPayload() *OutboxUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetCreatedTime sets the "created_time" field.
func (_u *OutboxUpdate) SetCreatedTime(v time.Time) *OutboxUpdate {
	_u.mutation.SetCreatedTime(v)
	return _u
}

// SetNillableCreatedTime sets the "created_time" field if the given value is not nil.
func (_u *OutboxUpdate) SetNillableCreatedTime(v *time.Time) *OutboxUpdate {
	if v != nil {
		_u.SetCreatedTime(*v)
	}
	return _u
}

// ClearCreatedTime clears the value of the "created_time" field.
func (_u *OutboxUpdate) ClearCreatedTime() *OutboxUpdate {
	_u.mutation.ClearCreatedTime()
	return _u
}

// Mutation returns the OutboxMutation object of the builder.
func (_u *OutboxUpdate) Mutation() *OutboxMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OutboxUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutboxUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OutboxUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutboxUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OutboxUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(outbox.Table, outbox.Columns, sqlgraph.NewFieldSpec(outbox.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(outbox.FieldAccountID, field.TypeString, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(outbox.FieldAccountID, field.TypeString)
	}
	if value, ok := _u.mutation.AggregateType(); ok {
		_spec.SetField(outbox.FieldAggregateType, field.TypeString, value)
	}
	if _u.mutation.AggregateTypeCleared() {
		_spec.ClearField(outbox.FieldAggregateType, field.TypeString)
	}
	if value, ok := _u.mutation.AggregateID(); ok {
		_spec.SetField(outbox.FieldAggregateID, field.TypeString, value)
	}
	if _u.mutation.AggregateIDCleared() {
		_spec.ClearField(outbox.FieldAggregateID, field.TypeString)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(outbox.FieldEventType, field.TypeString, value)
	}
	if _u.mutation.EventTypeCleared() {
		_spec.ClearField(outbox.FieldEventType, field.TypeString)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(outbox.FieldPayload, field.TypeBytes, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(outbox.FieldPayload, field.TypeBytes)
	}
	if value, ok := _u.mutation.CreatedTime(); ok {
		_spec.SetField(outbox.FieldCreatedTime, field.TypeTime, value)
	}
	if _u.mutation.CreatedTimeCleared() {
		_spec.ClearField(outbox.FieldCreatedTime, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OutboxUpdateOne is the builder for updating a single Outbox entity.
type OutboxUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OutboxMutation
}

// SetAccountID sets the "account_id" field.
func (_u *OutboxUpdateOne) SetAccountID(v string) *OutboxUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OutboxUpdateOne) SetNillableAccountID(v *string) *OutboxUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *OutboxUpdateOne) ClearAccountID() *OutboxUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetAggregateType sets the "aggregate_type" field.
func (_u *OutboxUpdateOne) SetAggregateType(v string) *OutboxUpdateOne {
	_u.mutation.SetAggregateType(v)
	return _u
}

// SetNillableAggregateType sets the "aggregate_type" field if the given value is not nil.
func (_u *OutboxUpdateOne) SetNillableAggregateType(v *string) *OutboxUpdateOne {
	if v != nil {
		_u.SetAggregateType(*v)
	}
	return _u
}

// ClearAggregateType clears the value of the "aggregate_type" field.
func (_u *OutboxUpdateOne) ClearAggregateType() *OutboxUpdateOne {
	_u.mutation.ClearAggregateType()
	return _u
}

// SetAggregateID sets the "aggregate_id" field.
func (_u *OutboxUpdateOne) SetAggregateID(v string) *OutboxUpdateOne {
	_u.mutation.SetAggregateID(v)
	return _u
}

// SetNillableAggregateID sets the "aggregate_id" field if the given value is not nil.
func (_u *OutboxUpdateOne) SetNillableAggregateID(v *string) *OutboxUpdateOne {
	if v != nil {
		_u.SetAggregateID(*v)
	}
	return _u
}

// ClearAggregateID clears the value of the "aggregate_id" field.
func (_u *OutboxUpdateOne) ClearAggregateID() *OutboxUpdateOne {
	_u.mutation.ClearAggregateID()
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *OutboxUpdateOne) SetEventType(v string) *OutboxUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *OutboxUpdateOne) SetNillableEventType(v *string) *OutboxUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// ClearEventType clears the value of the "event_type" field.
func (_u *OutboxUpdateOne) ClearEventType() *OutboxUpdateOne {
	_u.mutation.ClearEventType()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *OutboxUpdateOne) SetPayload(v []byte) *OutboxUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *OutboxUpdateOne) ClearPayload() *OutboxUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetCreatedTime sets the "created_time" field.
func (_u *OutboxUpdateOne) SetCreatedTime(v time.Time) *OutboxUpdateOne {
	_u.mutation.SetCreatedTime(v)
	return _u
}

// SetNillableCreatedTime sets the "created_time" field if the given value is not nil.
func (_u *OutboxUpdateOne) SetNillableCreatedTime(v *time.Time) *OutboxUpdateOne {
	if v != nil {
		_u.SetCreatedTime(*v)
	}
	return _u
}

// ClearCreatedTime clears the value of the "created_time" field.
func (_u *OutboxUpdateOne) ClearCreatedTime() *OutboxUpdateOne {
	_u.mutation.ClearCreatedTime()
	return _u
}

// Mutation returns the OutboxMutation object of the builder.
func (_u *OutboxUpdateOne) Mutation() *OutboxMutation {
	return _u.mutation
}

// Where appends a list predicates to the OutboxUpdate builder.
func (_u *OutboxUpdateOne) Where(ps ...predicate.Outbox) *OutboxUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OutboxUpdateOne) Select(field string, fields ...string) *OutboxUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Outbox entity.
func (_u *OutboxUpdateOne) Save(ctx context.Context) (*Outbox, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutboxUpdateOne) SaveX(ctx context.Context) *Outbox {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OutboxUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutboxUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OutboxUpdateOne) sqlSave(ctx context.Context) (_node *Outbox, err error) {
	_spec := sqlgraph.NewUpdateSpec(outbox.Table, outbox.Columns, sqlgraph.NewFieldSpec(outbox.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Outbox.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, outbox.FieldID)
		for _, f := range fields {
			if !outbox.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != outbox.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(outbox.FieldAccountID, field.TypeString, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(outbox.FieldAccountID, field.TypeString)
	}
	if value, ok := _u.mutation.AggregateType(); ok {
		_spec.SetField(outbox.FieldAggregateType, field.TypeString, value)
	}
	if _u.mutation.AggregateTypeCleared() {
		_spec.ClearField(outbox.FieldAggregateType, field.TypeString)
	}
	if value, ok := _u.mutation.AggregateID(); ok {
		_spec.SetField(outbox.FieldAggregateID, field.TypeString, value)
	}
	if _u.mutation.AggregateIDCleared() {
		_spec.ClearField(outbox.FieldAggregateID, field.TypeString)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(outbox.FieldEventType, field.TypeString, value)
	}
	if _u.mutation.EventTypeCleared() {
		_spec.ClearField(outbox.FieldEventType, field.TypeString)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(outbox.FieldPayload, field.TypeBytes, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(outbox.FieldPayload, field.TypeBytes)
	}
	if value, ok := _u.mutation.CreatedTime(); ok {
		_spec.SetField(outbox.FieldCreatedTime, field.TypeTime, value)
	}
	if _u.mutation.CreatedTimeCleared() {
		_spec.ClearField(outbox.FieldCreatedTime, field.TypeTime)
	}
	_node = &Outbox{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
